---
title: "NAFLD-CCA"
author: "Yun Zhu"
date: "23/12/2021"
output: pdf_document
---
This document is for doing PS omit missing data.
```{r setup, include=FALSE}
library(tidyverse)
library(MatchIt)
library(twang)
library(glmnet)
library(ggplot2)
library(dplyr)
library(lsr)
library(survey)
library(rbounds)
library(naniar)
library(tableone)
library(optmatch)
library(mice)
library(plotmo)
library(corrplot)
library(ggplot2)
library(forestplot)
library(ggcorrplot)
library(MatchThem)
library(gtsummary)
library(rstatix)
```

```{r warning=FALSE}
setwd("/Users/Crystal/Desktop/Practicum/Data")
NAFLD <-read_csv("data_NAFLD_PS.csv",show_col_types = FALSE)
NAFLD<-NAFLD %>%mutate(Sex=as.factor(ifelse(Sex=="Male", 0, 1)))
NAFLD<-NAFLD[,c(3:4,7,8,10:12,14,27,41)]
variables<-c("Sex","LDL","Triglycerides","Glycated_haemoglobin__HbA1c_",
             "HDL_cholesterol","Waist_circumference","Systolic_Blood_Pressure","BMIdich")
```

```{r,warning=FALSE}
## show the percentage of missing data
gg_miss_var(NAFLD[variables], show_pct = TRUE)
```
```{r}
##############################################
############ CCA #################
##############################################
tbl_summary(NAFLD)
table1.1 <- 
  tbl_summary(
    NAFLD,
    by = NAFLD_status # split table by group
  ) %>%
  add_n() %>% # add column with total number of non-missing observations
  add_p() %>% # test for a difference between groups
  modify_header(label = "**Variable**") %>% # update the column header
  bold_labels() 
table1.1
table1.2 <- 
  tbl_summary(
    NAFLD,
    by = T2D # split table by group
  ) %>%
  add_n() %>% # add column with total number of non-missing observations
  add_p() %>% # test for a difference between groups
  modify_header(label = "**Variable**") %>% # update the column header
  bold_labels() 
table1.2
table1.3 <- 
  tbl_summary(
    NAFLD,
    by = BMIdich # split table by group
  ) %>%
  add_n() %>% # add column with total number of non-missing observations
  add_p() %>% # test for a difference between groups
  modify_header(label = "**Variable**") %>% # update the column header
  bold_labels() 
table1.3
```

```{r}
omitNAFLD<- na.omit(NAFLD)
tbl_summary(omitNAFLD)
table2.1 <- 
  tbl_summary(
    omitNAFLD,
    by = NAFLD_status, # split table by group
    missing = "no" # don't list missing data separately
  ) %>%
  add_n() %>% # add column with total number of non-missing observations
  add_p() %>% # test for a difference between groups
  modify_header(label = "**Variable**") %>% # update the column header
  bold_labels() 
table2.1

table2.2 <- 
  tbl_summary(
    omitNAFLD,
    by = T2D # split table by group
  ) %>%
  add_n() %>% # add column with total number of non-missing observations
  add_p() %>% # test for a difference between groups
  modify_header(label = "**Variable**") %>% # update the column header
  bold_labels() 
table2.2

table2.3 <- 
  tbl_summary(
    omitNAFLD,
    by = BMIdich # split table by group
  ) %>%
  add_n() %>% # add column with total number of non-missing observations
  add_p() %>% # test for a difference between groups
  modify_header(label = "**Variable**") %>% # update the column header
  bold_labels() 
table2.3
```

```{r}
df_numeric <- dplyr::select_if(NAFLD, is.numeric)
cor.mat <-df_numeric%>% cor_mat()
cor.mat %>%
  cor_reorder() %>%
  pull_lower_triangle() %>%
  cor_plot(label = TRUE)
cor.mat %>% cor_gather()
```

```{r}
df_numeric <- dplyr::select_if(omitNAFLD, is.numeric)
cor.mat <-df_numeric%>% cor_mat()
cor.mat %>%
  cor_reorder() %>%
  pull_lower_triangle() %>%
  cor_plot(label = TRUE)
cor.mat %>% cor_gather()
```

```{r}
out.formula1 <- as.formula((paste("NAFLD_status","~ ",paste(variables,collapse = "+"))))
out.formula2 <- as.formula((paste("T2D","~ ",paste(variables,collapse = "+"))))
out.formula3 <- as.formula((paste("NAFLD_status","~ ",paste(variables,collapse = "*"))))
out.formula4 <- as.formula((paste("T2D","~ ",paste(variables,collapse = "*"))))
```

```{r}
summary(glm(out.formula1, data = omitNAFLD))
summary(glm(out.formula2, data = omitNAFLD))
```


```{r}
# Normal LASSO
##Using lasso to figure out the predictors that both effect the T2D and NAFLD status
x1<-scale(model.matrix(out.formula1,omitNAFLD)[,-1])
y1 <- omitNAFLD$NAFLD_status
set.seed(123)
cv.l1 <- cv.glmnet(x1,y1,family="binomial",nfolds = 5,alpha=1)
best_lambda.l1<-cv.l1$lambda.min
l.mod1<- glmnet(x1,y1,family="binomial",alpha=1,lambda = best_lambda.l1)
coef.l.min1 <- coef(l.mod1)
feature1 <- rownames(coef.l.min1)[coef.l.min1[,1]!=0][-1]
feature1
```
```{r}
x2<-scale(model.matrix(out.formula2,omitNAFLD)[,-1])
y2 <- omitNAFLD$T2D
set.seed(123)
cv.l2 <- cv.glmnet(x2,y2,family="binomial",nfolds = 5,alpha=1)
best_lambda.l2<-cv.l2$lambda.min
l.mod2 <- glmnet(x2,y2,family="binomial", alpha=1,lambda = best_lambda.l2)
coef.l.min2 <- coef(l.mod2 )
feature2 <- rownames(coef.l.min2)[coef.l.min2[,1]!=0][-1]
feature2
```


```{r}
# Perform Boot straps with LASSO
boot_rep = 500 # Number of Boot straps
Feature.NAFLD<-data.frame(feature=variables)
for(i in 1:boot_rep ) {
  # Generate Bootstrap rows
  set.seed(i)
  bootrows = sample(1:nrow(omitNAFLD), nrow(omitNAFLD), replace = T)
  splitdf = omitNAFLD[bootrows,]
  
  # Bootstrapped data
  traindf = splitdf

  # Run LASSO with no covariate control: Continuous Outcome
  ## Convert dataframe into matrix
  X_cont = scale(model.matrix(out.formula1,traindf)[,-1])
  Y_cont = traindf$NAFLD_status
  # Find best lambda
  cvfit_cont = glmnet::cv.glmnet(x= X_cont, y = Y_cont,nfolds = 5, family="binomial", 
                                 alpha = 1, standardize = F)
  lambda = cvfit_cont$lambda.1se

  ## Run Lasso
  fit_cont = glmnet::glmnet(x= X_cont, y = Y_cont, family="binomial", alpha = 1, 
                            standardize = F, lambda = lambda)
  coef.l.min1 <- coef(fit_cont)[-1]
  Feature.NAFLD[i+1]<-coef.l.min1
}
for (j in 1:boot_rep+1) {
  Feature.NAFLD[j]<-ifelse(Feature.NAFLD[j]== 0, 0, 1)
  }
Feature.NAFLD$total = rowSums(Feature.NAFLD[-1])
print(Feature.NAFLD$feature[Feature.NAFLD$total>0.7*boot_rep])
## Variables related to NAFLD: Triglycerides","HDL_cholesterol","Waist_circumference",    "Systolic_Blood_Pressure"  
```

```{r}
# Perform Boot straps with LASSO
boot_rep = 500 # Number of Boot straps
Feature.T2D <-data.frame(feature=variables)
for(i in 1:boot_rep ) {
  # Generate Bootstrap rows
  set.seed(i)
  bootrows = sample(1:nrow(omitNAFLD), nrow(omitNAFLD), replace = T)
  splitdf = omitNAFLD[bootrows,]
  # Bootstrapped data
  traindf = splitdf

  # Run LASSO with no covariate control: Continuous Outcome
  ## Convert dataframe into matrix
  X_cont = scale(model.matrix(out.formula2,traindf)[,-1])
  Y_cont = traindf$T2D

  # Find best lambda
  cvfit_cont = glmnet::cv.glmnet(x= X_cont, y = Y_cont, nfolds = 5, family="binomial",
                                 alpha = 1, standardize = F)
  lambda = cvfit_cont$lambda.1se

  ## Run Lasso
  fit_cont = glmnet::glmnet(x= X_cont, y = Y_cont, family="binomial", alpha = 1, 
                            standardize = F, lambda = lambda)
  coef.l.min1 <- coef(fit_cont)[-1]
  Feature.T2D[i+1]<-coef.l.min1
}
for (j in 1:boot_rep+1) {
  Feature.T2D[j]<-ifelse(Feature.T2D[j]== 0, 0, 1)
  }
Feature.T2D$total = rowSums(Feature.T2D[-1])
print(Feature.T2D$feature[Feature.T2D$total>0.7*boot_rep])
## Variables related to T2D:"Glycated_haemoglobin__HbA1c_","Waist_circumference" 
```
```{r}
# Perform Boot straps with LASSO contain interaction
boot_rep = 500 # Number of Boot straps
sum.NAFLD<-summary(glm(out.formula3, data = omitNAFLD))
Feature.NAFLD.interaction<-data.frame(feature=rownames(coef(sum.NAFLD))[-1])
for(i in 1:boot_rep ) {
  # Generate Bootstrap rows
  set.seed(i)
  bootrows = sample(1:nrow(omitNAFLD), nrow(omitNAFLD), replace = T)
  splitdf = omitNAFLD[bootrows,]
  
  # Bootstrapped data
  traindf = splitdf

  # Run LASSO with no covariate control: Continuous Outcome
  ## Convert dataframe into matrix
  X_cont = scale(model.matrix(out.formula3,traindf)[,-1])
  Y_cont = traindf$NAFLD_status
  # Find best lambda
  cvfit_cont = glmnet::cv.glmnet(x= X_cont, y = Y_cont,nfolds = 5, family="binomial", 
                                 alpha = 1, standardize = F)
  lambda = cvfit_cont$lambda.1se

  ## Run Lasso
  fit_cont = glmnet::glmnet(x= X_cont, y = Y_cont, family="binomial", alpha = 1, 
                            standardize = F, lambda = lambda)
  coef.l.min1 <- coef(fit_cont)[-1]
  Feature.NAFLD.interaction[i+1]<-coef.l.min1
}
for (j in 1:boot_rep+1) {
  Feature.NAFLD.interaction[j]<-ifelse(Feature.NAFLD.interaction[j]== 0, 0, 1)
  }
Feature.NAFLD.interaction$total = rowSums(Feature.NAFLD.interaction[-1])
print(Feature.NAFLD.interaction$feature[Feature.NAFLD.interaction$total>0.8*boot_rep])
## Variables related to NAFLD: "Triglycerides","HDL_cholesterol","Waist_circumference"
```

```{r}
boot_rep = 500 # Number of Boot straps
sum.T2D<-summary(glm(out.formula4, data = omitNAFLD))
Feature.T2D.interaction<-data.frame(feature=rownames(coef(sum.T2D))[-1])

for(i in 1:boot_rep ) {
  # Generate Bootstrap rows
  set.seed(i)
  bootrows = sample(1:nrow(omitNAFLD), nrow(omitNAFLD), replace = T)
  splitdf = omitNAFLD[bootrows,]
  # Bootstrapped data
  traindf = splitdf

  # Run LASSO with no covariate control: Continuous Outcome
  ## Convert dataframe into matrix
  X_cont = scale(model.matrix(out.formula4,traindf)[,-1])
  Y_cont = traindf$T2D

  # Find best lambda
  cvfit_cont = glmnet::cv.glmnet(x= X_cont, y = Y_cont, nfolds = 5,family="binomial",
                                 alpha = 1, standardize = F)
  lambda = cvfit_cont$lambda.1se

  ## Run Lasso
  fit_cont = glmnet::glmnet(x= X_cont, y = Y_cont, family="binomial", alpha = 1, 
                            standardize = F, lambda = lambda)
  coef.l.min1 <- coef(fit_cont)[-1]
  Feature.T2D.interaction[i+1]<-coef.l.min1
}
for (j in 1:boot_rep+1) {
  Feature.T2D.interaction[j]<-ifelse(Feature.T2D.interaction[j]== 0, 0, 1)
  }
Feature.T2D.interaction$total = rowSums(Feature.T2D.interaction[-1])
print(Feature.T2D.interaction$feature[Feature.T2D.interaction$total>0.8*boot_rep])
## Variables related to T2D: "Glycated_haemoglobin__HbA1c_","Glycated_haemoglobin__HbA1c_:Waist_circumference" ,"Glycated_haemoglobin__HbA1c_:Waist_circumference:Systolic_Blood_Pressure"
```

```{r}
NAFLD.omit.status<-subset (omitNAFLD, select = -T2D)
NAFLD.omit.t2d<-subset (omitNAFLD, select = -NAFLD_status)
# Perform boot straps and feature sampling for LASSO
boot_rep = 500 # Number of Boot straps
numpred = 8 # Total number of predictors or independent variables used in the model.
outvar = "NAFLD_status" # name of the outcoem feature or variable
fakename = paste("X", 1:numpred, sep = "") # Create fakenames of input features/predictors to avoid coding issue due to special characters.
oriname = names(NAFLD.omit.status)[!names(NAFLD.omit.status) %in% outvar] # Original feature names

## Prepare the Models
res = lapply(1:boot_rep, function(seed) {
  # Generate Bootstrap rows
  set.seed(seed)
  bootrows = sample(1:nrow(NAFLD.omit.status), nrow(NAFLD.omit.status), replace = T)
  splitdf = NAFLD.omit.status[bootrows,]
  
  # Generate Feature sample
  featname = names(NAFLD.omit.status)[!names(NAFLD.omit.status) %in% outvar]# Get the names of all input features. "y" is used because it is the outcome variable. Hence it should not be selected.
  set.seed(seed)
  featnum = sample(2:numpred, 1, replace = F)
  set.seed(seed)
  selfeat = sample(featname, featnum, replace = F)
  
  # Bootstrapped data
  traindf = splitdf[, c(selfeat, outvar)]
  
  # Run LASSO with no covariate control: Continuous Outcome
  ## Convert dataframe into matrix
  X_cont = model.matrix(out.formula3,traindf)[,-1]
  Y_cont = traindf$NAFLD_status
  
  # Find best lambda
  cvfit_cont = glmnet::cv.glmnet(x= X_cont, y = Y_cont, nfolds = 5,family="binomial", alpha = 1, standardize = F)
  cvfit_cont
  plot(cvfit_cont)
  lambda = cvfit_cont$lambda.1se
  
  ## Run Lasso
  fit_cont = glmnet::glmnet(x= X_cont, y = Y_cont,nfolds = 5,family="binomial", alpha = 1, standardize = F, lambda = lambda)
  fit_cont
  # ## View selected features and coefficients
  # coef_cont = coefextract(model = fit_cont)
  # p <- ggplot(coef_cont[-1,], aes(x = variable, y = coefficient))+
  #   geom_bar(stat = "identity")+
  #   scale_y_continuous(limits = c(-0.5,1))+
  #   theme_bw()
  # p
  # print(p)
})

## Create a matrix of features for each model
var_organise = function (inputlist, symbol = "_") {
  org_var = lapply(inputlist, function(x) {
    a = stringi::stri_split_fixed(x, symbol)
    ifelse(length(a[[1]]) > 1, paste0(naturalsort::naturalsort(a[[1]]),
                                      collapse = symbol), a[[1]])
  })
  return(unlist(org_var))
}
perflistcreator = function(model_list = fitlist){
  # Extract Features selection for each model
  ranklist = lapply(1:length(model_list), function(x){
    # Extract coefficients of all the features including intercept term
    df = glmnet::coef.glmnet(model_list[[x]])
    # Create a data frame
    selfeat = data.frame(variable = rownames(df)[-1], importance=df[-1,1], stringsAsFactors = F)
    names(selfeat) = c("variable", "importance")
    selfeat$importance[is.na(selfeat$importance) | is.nan(selfeat$importance)] = 0
    selfeat$importance[selfeat$importance != 0] = 1
    selfeat
  })

  # Combine the list of selected features into a single dataframe
  res = ranklist
  res = Reduce(function(...) merge(..., by="variable", all=TRUE), res)
  tres = t(res[,-1])
  colnames(tres) = res[,1]
  tres = data.frame(tres)
  res = tres
  resrank2 = res
  return(res)
}
freqdf = perflistcreator(model_list = res)

## Calculate frequency
freq = colSums(freqdf, na.rm = T)/ sapply(freqdf, function(x) length(x[!is.na(x)]))
freq_clean = round(freq*100,2) # Gives frequency in percent and rounding off to two digits
## Replace fakenames with original names
names(freq_clean) = names(fakename[as.numeric(stringi::stri_replace_all_fixed(names(freq_clean), "X",""))])

```

```{r}
newvariables.normal<-c("LDL","Triglycerides","Glycated_haemoglobin__HbA1c_","Waist_circumference","Systolic_Blood_Pressure","BMIdich")
newvariables <- c("Glycated_haemoglobin__HbA1c_","Waist_circumference")
tab1e<-CreateTableOne(vars=newvariables,data=omitNAFLD,strata="T2D")
print(tab1e,smd=T)
```

```{r}
ps.formula <- as.formula((paste("T2D ~",paste(newvariables,collapse = "+"))))
param<-matchit(ps.formula,data = omitNAFLD)
omitNAFLD$param_ps<-param$distance
set.seed(123456)
nonparam<-ps(as.formula((paste("T2D ~ ",paste(newvariables,collapse = "+")))),
                  data = as.data.frame(omitNAFLD),n.trees=1000,interaction.depth=9,shrinkage=0.01,
                  stop.method="es.mean",estimand="ATT")
omitNAFLD$nonparam_ps<-nonparam$ps$es.mean
summary(nonparam$gbm.obj)
```

```{r}
ggplot(data = omitNAFLD,aes(param_ps,fill=factor(T2D)))+
  geom_histogram(binwidth = 0.005,alpha = 0.5,position="identity")
```

```{r}
omitNAFLD <- omitNAFLD %>% mutate(quintile = ntile(param_ps, 5))
d <- rep(NA, 5)
for (i in 1:5) {
  dat_q <- omitNAFLD[omitNAFLD$quintile == i,]
  d[i] <- cohensD(param_ps ~ T2D, data = dat_q)
  }
d

```

```{r}
logitPS<-sd(-log(1/omitNAFLD$param_ps-1))
## Greedy matching

greedy<-matchit(ps.formula,data=omitNAFLD,
                distance="logit",
                caliper=0.1*sd(logitPS),
                method="nearest")
greedy
greedy$nn <- c(3695, 1382)


## Optimal matching
optimal <- matchit(ps.formula,data= omitNAFLD,
                distance="logit",
                   method = "optimal")
optimal
optimal$nn <- c(3695, 1382)


## 1:2 matching
one_two <- matchit(ps.formula,data=omitNAFLD,
                distance="logit",
                caliper=0.1*sd(logitPS),
                   method = "nearest", ratio = 2)
one_two
one_two$nn <-c(3695, 2073)

## Full matching
full <- matchit(ps.formula,data=omitNAFLD,
                distance="logit",
                caliper=0.1*sd(logitPS),
                method = "full")
full
full$nn<- c(3695, 3695)
matching.t<-matrix(c(greedy$nn,optimal$nn,one_two$nn,full$nn), ncol=2, byrow=TRUE)
rownames(matching.t)<-c("Greedy matching","Optimal matching","1:2 matching","Full matching")
colnames(matching.t)<-c("Original Groups","Matched Groups")
knitr::kable(as.table(matching.t))

## Subclassification
omitNAFLD <- omitNAFLD %>% mutate(subclass = ntile(param_ps, 5))


## Subclassification with full matching
subc <- matchit(ps.formula, data = omitNAFLD,
                method = "subclass",
                subclass = 5)
subc
subc.t<-matrix(c(3695, 3695), ncol=2, byrow=TRUE)
colnames(subc.t)<-c("Original Groups","Matched Groups")
rownames(subc.t)<-"Subclasses"
knitr::kable(as.table(subc.t))
plot(subc, type = "jitter")

### Weighting

## IPTW with stabilization
omitNAFLD$iptw<- ifelse(omitNAFLD$T2D == 1, (mean(omitNAFLD$param_ps))/omitNAFLD$param_ps, (mean(1-omitNAFLD$param_ps))/(1-omitNAFLD$param_ps))
```

```{r}
## Calculate standardized difference in the covariates

# Greedy matching
summary(greedy, standardize = TRUE)

# Optimal matching
summary(optimal, standardize = TRUE)

# 1:2 matching
summary(one_two, standardized = TRUE)

# Full matching
summary(full, standardize = TRUE)

# Subclassification with full matching
summary(subc, standardize=TRUE)

# Weighting by IPTW with stabilization
iptw <- dx.wts(omitNAFLD$iptw, data = as.data.frame(omitNAFLD), var = newvariables, treat.var="T2D", 
               estimand = "ATE")
```



```{r}
# NAFLD_status~T2D
formula1<-as.formula((paste("NAFLD_status","~ T2D+ ",paste(newvariables,collapse = "+"))))
## Greedy matching
matched_greedy <- match.data(greedy,subclass = "block")
glm_NAFLD_greedy <- glm(formula1,
                          data = matched_greedy,
                          family = binomial)
summary_greedy <- summary(glm_NAFLD_greedy)
exp(coef(glm_NAFLD_greedy))


## Optimal matching
matched_optimal <- match.data(optimal,subclass = "block")
glm_NAFLD_optimal <- glm(formula1,
                           data = matched_optimal,
                           family = binomial)
summary_optimal <- summary(glm_NAFLD_optimal)
exp(coef(glm_NAFLD_optimal))


## 1:2 matching
matched_one_two <- match.data(one_two,subclass = "block")
glm_NAFLD_one_two <- glm(formula1, 
                           data = matched_one_two,
                           family = binomial)
summary_one_two <- summary(glm_NAFLD_one_two)
exp(coef(glm_NAFLD_one_two))


## Full matching
matched_full <- match.data(full,subclass = "block")
glm_NAFLD_full <- glm(formula1,
                        data = matched_full,
                        family = binomial, weights = weights)
summary_full <-summary(glm_NAFLD_full)
exp(coef(glm_NAFLD_full))


## Subclassification with full matching
subced <- match.data(subc,subclass = "block")
design <- svydesign(id = ~1, strata = ~subclass, weights = ~weights, nested = TRUE, data = subced)
svyglm_NAFLD_subc <- svyglm(formula1, design = design, family = binomial)
summary_subc <- summary(svyglm_NAFLD_subc)
exp(coef(svyglm_NAFLD_subc))


## Weighting by IPTW with stabilization
glm_NAFLD_iptw <- glm(formula1,
                        data = omitNAFLD,
                        weights = iptw,
                        family = binomial)
summary_iptw <-summary(glm_NAFLD_iptw)
exp(coef(glm_NAFLD_iptw))
```
```{r}
knitr::kable(summary_greedy$coefficients,digits = 3,caption = "summary table of greedy matching")
knitr::kable(summary_optimal$coefficients,digits = 3,caption = "summary table of optimal matching")
knitr::kable(summary_one_two$coefficients,digits = 3,caption = "summary table of 1:2 matching")
knitr::kable(summary_full$coefficients,digits = 3,caption = "summary table of full matching")
knitr::kable(summary_subc$coefficients,digits = 3,caption = "summary table of subclassification")
knitr::kable(summary_iptw$coefficients,digits = 3,caption = "summary table of weighting by iptw")
```


```{r}
NAFLD.T2D.HR.est<-c()
NAFLD.T2D.logHR.est<-c()
NAFLD.T2D.se<-c()
NAFLD.T2D.pvalue<-c()
NAFLD.T2D.lowerCI<-c()
NAFLD.T2D.upperCI<-c()

NAFLD.T2D.HR.est[1] <-exp(summary_greedy$coefficients[2,1])
NAFLD.T2D.logHR.est[1]<-summary_greedy$coefficients[2,1]
NAFLD.T2D.se[1]<-summary_greedy$coefficients[2,2]
NAFLD.T2D.pvalue[1]<-summary_greedy$coefficients[2,4]
NAFLD.T2D.lowerCI[1]<- exp(summary_greedy$coefficients[2,1]-1.96*summary_greedy$coefficients[2,2])
NAFLD.T2D.upperCI[1]<- exp(summary_greedy$coefficients[2,1]+1.96*summary_greedy$coefficients[2,2])

NAFLD.T2D.HR.est[2] <-exp(summary_optimal$coefficients[2,1])
NAFLD.T2D.logHR.est[2]<-summary_optimal$coefficients[2,1]
NAFLD.T2D.se[2]<-summary_optimal$coefficients[2,2]
NAFLD.T2D.pvalue[2]<-summary_optimal$coefficients[2,4]
NAFLD.T2D.lowerCI[2]<- exp(summary_optimal$coefficients[2,1]-1.96*summary_optimal$coefficients[2,2])
NAFLD.T2D.upperCI[2]<- exp(summary_optimal$coefficients[2,1]+1.96*summary_optimal$coefficients[2,2])

NAFLD.T2D.HR.est[3] <-exp(summary_one_two$coefficients[2,1])
NAFLD.T2D.logHR.est[3]<-summary_one_two$coefficients[2,1]
NAFLD.T2D.se[3]<-summary_one_two$coefficients[2,2]
NAFLD.T2D.pvalue[3]<-summary_one_two$coefficients[2,4]
NAFLD.T2D.lowerCI[3]<- exp(summary_one_two$coefficients[2,1]-1.96*summary_one_two$coefficients[2,2])
NAFLD.T2D.upperCI[3]<- exp(summary_one_two$coefficients[2,1]+1.96*summary_one_two$coefficients[2,2])

NAFLD.T2D.HR.est[4] <-exp(summary_full$coefficients[2,1])
NAFLD.T2D.logHR.est[4]<-summary_full$coefficients[2,1]
NAFLD.T2D.se[4]<-summary_full$coefficients[2,2]
NAFLD.T2D.pvalue[4]<-summary_full$coefficients[2,4]
NAFLD.T2D.lowerCI[4]<- exp(summary_full$coefficients[2,1]-1.96*summary_full$coefficients[2,2])
NAFLD.T2D.upperCI[4]<- exp(summary_full$coefficients[2,1]+1.96*summary_full$coefficients[2,2])

NAFLD.T2D.HR.est[5] <-exp(summary_subc$coefficients[2,1])
NAFLD.T2D.logHR.est[5]<-summary_subc$coefficients[2,1]
NAFLD.T2D.se[5]<-summary_subc$coefficients[2,2]
NAFLD.T2D.pvalue[5]<-summary_subc$coefficients[2,4]
NAFLD.T2D.lowerCI[5]<- exp(summary_subc$coefficients[2,1]-1.96*summary_subc$coefficients[2,2])
NAFLD.T2D.upperCI[5]<- exp(summary_subc$coefficients[2,1]+1.96*summary_subc$coefficients[2,2])

NAFLD.T2D.HR.est[6] <-exp(summary_iptw$coefficients[2,1])
NAFLD.T2D.logHR.est[6]<-summary_iptw$coefficients[2,1]
NAFLD.T2D.se[6]<-summary_iptw$coefficients[2,2]
NAFLD.T2D.pvalue[6]<-summary_iptw$coefficients[2,4]
NAFLD.T2D.lowerCI[6]<- exp(summary_iptw$coefficients[2,1]-1.96*summary_iptw$coefficients[2,2])
NAFLD.T2D.upperCI[6]<- exp(summary_iptw$coefficients[2,1]+1.96*summary_iptw$coefficients[2,2])
```

```{r}
NAFLDoutcome.T2D.result <- 
  structure(list(
    mean  = c(NA, NA, NAFLD.T2D.HR.est), 
    lower = c(NA, NA, NAFLD.T2D.lowerCI),
    upper = c(NA, NA, NAFLD.T2D.upperCI)),
    .Names = c("mean", "lower", "upper"), 
    row.names = c(NA, -8L), 
    class = "data.frame")

A <- cbind2(c("","Method","Greedy Matching","Optimal Matching","1:2 Matching","Full Matching","Subclassification", "IPTW"),
               c("","Effect", as.character(round(NAFLD.T2D.HR.est,3))))
B<- cbind2(c("","SE", as.character(round(NAFLD.T2D.se,3))),
           c("","p-value", ifelse(NAFLD.T2D.pvalue<0.001, "<0.001", round(NAFLD.T2D.pvalue,3))))
tabletext <- cbind2(A ,B)

forestplot(tabletext, 
           NAFLDoutcome.T2D.result,new_page = TRUE,
           col = fpColors(box="royalblue",line="darkblue"),
           xlab = "Estimate with 95% CI",
           hrzl_lines= gpar(col = "#444444"),
           is.summary = c(TRUE, TRUE, rep(FALSE, 10)),
           clip = c(0.5,5.5), zero=0.5,
           txt_gp=fpTxtGp(label = gpar(cex = 0.8),
                          title = gpar(cex = 1),
                          ticks = gpar(cex = 0.7),
                          xlab = gpar(cex = 0.7)),
           grid = structure(seq(0.5, 5.5, by=0.25), 
                            gp = gpar(lty = 2, col = "#CCCCFF")))
grid.text("Exposure of T2D on NAFLD", .5, 0.98, gp=gpar(fontface="bold"))
```

```{r}
##############################################
############ MI #################
##############################################
#Impute the data with 5 imputations (more is better)
mi.data<-mice(NAFLD, m = 5)
c.data<-complete(mi.data)
```

```{r}
tbl_summary(c.data)
table3.1 <- 
  tbl_summary(
    c.data,
    by = NAFLD_status # split table by group
  ) %>%
  add_n() %>% # add column with total number of non-missing observations
  add_p() %>% # test for a difference between groups
  modify_header(label = "**Variable**") %>% # update the column header
  bold_labels() 
table3.1
table3.2 <- 
  tbl_summary(
    c.data,
    by = T2D # split table by group
  ) %>%
  add_n() %>% # add column with total number of non-missing observations
  add_p() %>% # test for a difference between groups
  modify_header(label = "**Variable**") %>% # update the column header
  bold_labels() 
table3.2
table3.3 <- 
  tbl_summary(
    c.data,
    by = BMIdich # split table by group
  ) %>%
  add_n() %>% # add column with total number of non-missing observations
  add_p() %>% # test for a difference between groups
  modify_header(label = "**Variable**") %>% # update the column header
  bold_labels() 
table3.3
```
```{r}
df_numeric <- dplyr::select_if(c.data, is.numeric)
cor.mat <-df_numeric%>% cor_mat()
cor.mat %>%
  cor_reorder() %>%
  pull_lower_triangle() %>%
  cor_plot(label = TRUE)
cor.mat %>% cor_gather()
```

```{r}
############MIte#############
## Greedy matching
greedy.matched.MIte.datasets <- matchthem(ps.formula, mi.data,
                          approach = 'within',
                          method = 'nearest',
                          caliper = 0.05)
## Optimal matching
optimal.matched.MIte.datasets <- matchthem(ps.formula, mi.data,
                          approach = 'within',
                          method = 'optimal',
                          caliper = 0.05)
## 1:2 matching
one_two.matched.MIte.datasets <- matchthem(ps.formula, mi.data,
                          approach = 'within',
                          method = 'nearest',
                          caliper = 0.05, ratio = 2)
## Full matching
full.matched.MIte.datasets <- matchthem(ps.formula,mi.data,
                                 approach = 'within',
                                 caliper = 0.05,
                                 method = "full")

## Subclassification with full matching
subc.MIte.datasets <- matchthem(ps.formula, mi.data,
                           approach = 'within',
                method = "subclass",
                subclass = 5)
subc.MIte.datasets
plot(subc.MIte.datasets, type = "jitter")

# IPTW
weighted.MIte.datasets <- weightthem(ps.formula, mi.data,
                                approach = 'within', 
                                method = 'ps', estimand = 'ATM')
weighted.MIte.datasets
```

```{r}
library(cobalt)
bal.tab(greedy.matched.MIte.datasets, abs = TRUE)
bal.tab(optimal.matched.MIte.datasets, abs = TRUE)
bal.tab(one_two.matched.MIte.datasets, abs = TRUE)
bal.tab(full.matched.MIte.datasets, abs = TRUE)
bal.tab(subc.MIte.datasets, abs = TRUE)
bal.tab(weighted.MIte.datasets, abs = TRUE)
```

```{r}
library(survey)
formula1<-as.formula((paste("NAFLD_status","~ T2D+ ",paste(newvariables,collapse = "+"))))

greedy.matched.MIte.models <- with(data = greedy.matched.MIte.datasets,
                               expr = svyglm(formula1, family = quasibinomial))
greedy.matched.MIte.results <- pool(greedy.matched.MIte.models)
summary_MIte_greedy <- summary(greedy.matched.MIte.results, conf.int = TRUE)

optimal.matched.MIte.models <- with(data = optimal.matched.MIte.datasets,
                               expr = svyglm(formula1, family =quasibinomial))
optimal.matched.MIte.results <- pool(optimal.matched.MIte.models)
summary_MIte_optimal <-summary(optimal.matched.MIte.results, conf.int = TRUE)

one_two.matched.MIte.models <- with(data = one_two.matched.MIte.datasets,
                               expr = svyglm(formula1, family = quasibinomial))
one_two.matched.MIte.results <- pool(one_two.matched.MIte.models)
summary_MIte_one_two <- summary(one_two.matched.MIte.results, conf.int = TRUE)

full.matched.MIte.models <- with(data = full.matched.MIte.datasets,
                               expr = svyglm(formula1, family = quasibinomial))
full.matched.MIte.results <- pool(full.matched.MIte.models)
summary_MIte_full <- summary(full.matched.MIte.results, conf.int = TRUE)


subc.MIte.models <- with(data = subc.MIte.datasets,
                               expr = svyglm(formula1, family = quasibinomial))
subc.MIte.results <- pool(subc.MIte.models)
summary_MIte_subc <-summary(subc.MIte.results, conf.int = TRUE)

# IPTW
weighted.MIte.models <- with(data = weighted.MIte.datasets, expr = svyglm(formula1, family = quasibinomial))
weighted.MIte.results <- pool(weighted.MIte.models)
summary_MIte_iptw <-summary(weighted.MIte.results, conf.int = TRUE)
```

```{r}
NAFLD.T2D.MIte.HR.est<-c()
NAFLD.T2D.MIte.logHR.est<-c()
NAFLD.T2D.MIte.se<-c()
NAFLD.T2D.MIte.pvalue<-c()
NAFLD.T2D.MIte.lowerCI<-c()
NAFLD.T2D.MIte.upperCI<-c()

NAFLD.T2D.MIte.HR.est[1] <-exp(summary_MIte_greedy[2,2])
NAFLD.T2D.MIte.logHR.est[1]<-summary_MIte_greedy[2,2]
NAFLD.T2D.MIte.se[1]<-summary_MIte_greedy[2,3]
NAFLD.T2D.MIte.pvalue[1]<-summary_MIte_greedy[2,6]
NAFLD.T2D.MIte.lowerCI[1]<- exp(summary_MIte_greedy[2,7])
NAFLD.T2D.MIte.upperCI[1]<- exp(summary_MIte_greedy[2,8])

NAFLD.T2D.MIte.HR.est[2] <-exp(summary_MIte_optimal[2,2])
NAFLD.T2D.MIte.logHR.est[2]<-summary_MIte_optimal[2,2]
NAFLD.T2D.MIte.se[2]<-summary_MIte_optimal[2,3]
NAFLD.T2D.MIte.pvalue[2]<-summary_MIte_optimal[2,6]
NAFLD.T2D.MIte.lowerCI[2]<- exp(summary_MIte_optimal[2,7])
NAFLD.T2D.MIte.upperCI[2]<- exp(summary_MIte_optimal[2,8])

NAFLD.T2D.MIte.HR.est[3] <-exp(summary_MIte_one_two[2,2])
NAFLD.T2D.MIte.logHR.est[3]<-summary_MIte_one_two[2,2]
NAFLD.T2D.MIte.se[3]<-summary_MIte_one_two[2,3]
NAFLD.T2D.MIte.pvalue[3]<-summary_MIte_one_two[2,6]
NAFLD.T2D.MIte.lowerCI[3]<- exp(summary_MIte_one_two[2,7])
NAFLD.T2D.MIte.upperCI[3]<- exp(summary_MIte_one_two[2,8])

NAFLD.T2D.MIte.HR.est[4] <-exp(summary_MIte_full[2,2])
NAFLD.T2D.MIte.logHR.est[4]<-summary_MIte_full[2,2]
NAFLD.T2D.MIte.se[4]<-summary_MIte_full[2,3]
NAFLD.T2D.MIte.pvalue[4]<-summary_MIte_full[2,6]
NAFLD.T2D.MIte.lowerCI[4]<- exp(summary_MIte_full[2,7])
NAFLD.T2D.MIte.upperCI[4]<- exp(summary_MIte_full[2,8])

NAFLD.T2D.MIte.HR.est[5] <-exp(summary_MIte_subc[2,2])
NAFLD.T2D.MIte.logHR.est[5]<-summary_MIte_subc[2,2]
NAFLD.T2D.MIte.se[5]<-summary_MIte_subc[2,3]
NAFLD.T2D.MIte.pvalue[5]<-summary_MIte_subc[2,6]
NAFLD.T2D.MIte.lowerCI[5]<- exp(summary_MIte_subc[2,7])
NAFLD.T2D.MIte.upperCI[5]<- exp(summary_MIte_subc[2,8])

NAFLD.T2D.MIte.HR.est[6] <-exp(summary_MIte_iptw[2,2])
NAFLD.T2D.MIte.logHR.est[6]<-summary_MIte_iptw[2,2]
NAFLD.T2D.MIte.se[6]<-summary_MIte_iptw[2,3]
NAFLD.T2D.MIte.pvalue[6]<-summary_MIte_iptw[2,6]
NAFLD.T2D.MIte.lowerCI[6]<- exp(summary_MIte_iptw[2,7])
NAFLD.T2D.MIte.upperCI[6]<- exp(summary_MIte_iptw[2,8])
```

```{r}
NAFLDoutcome.T2D.MIte.result <- 
  structure(list(
    mean  = c(NA, NA, NAFLD.T2D.MIte.HR.est), 
    lower = c(NA, NA, NAFLD.T2D.MIte.lowerCI),
    upper = c(NA, NA, NAFLD.T2D.MIte.upperCI)),
    .Names = c("mean", "lower", "upper"), 
    row.names = c(NA, -8L), 
    class = "data.frame")

A <- cbind2(c("","Method","Greedy Matching","Optimal Matching","1:2 Matching","Full Matching","Subclassification", "IPTW"),
               c("","Effect", as.character(round(NAFLD.T2D.MIte.HR.est,3))))
B<- cbind2(c("","SE", as.character(round(NAFLD.T2D.MIte.se,3))),
           c("","p-value", ifelse(NAFLD.T2D.MIte.pvalue<0.001, "<0.001", round(NAFLD.T2D.MIte.pvalue,3))))
tabletext <- cbind2(A ,B)

forestplot(tabletext, 
           NAFLDoutcome.T2D.result,new_page = TRUE,
           col = fpColors(box="royalblue",line="darkblue"),
           xlab = "Estimate with 95% CI",
           hrzl_lines= gpar(col = "#444444"),
           is.summary = c(TRUE, TRUE, rep(FALSE, 10)),
           clip = c(0.5,5.5), zero=1,
           txt_gp=fpTxtGp(label = gpar(cex = 0.8),
                          title = gpar(cex = 1),
                          ticks = gpar(cex = 0.7),
                          xlab = gpar(cex = 0.7)),
           grid = structure(seq(1, 5.5, by=0.25), 
                            gp = gpar(lty = 2, col = "#CCCCFF")))
grid.text("Exposure of T2D on NAFLD by MIte", .5, 0.98, gp=gpar(fontface="bold"))
```

```{r}
##############MIps##############
## Greedy matching
greedy.matched.MIps.across.datasets <- matchthem(ps.formula, mi.data,
                          approach = 'across',
                          method = 'nearest',
                          caliper = 0.05)
## Optimal matching
optimal.matched.MIps.across.datasets <- matchthem(ps.formula, mi.data,
                          approach = 'across',
                          method = 'optimal',
                          caliper = 0.05)
## 1:2 matching
one_two.matched.MIps.across.datasets <- matchthem(ps.formula, mi.data,
                          approach = 'across',
                          method = 'nearest',
                          caliper = 0.05, ratio = 2)
## Full matching
full.matched.MIps.across.datasets <- matchthem(ps.formula,mi.data,
                                 approach = 'across',
                                 caliper = 0.05,
                                 method = "full")

## Subclassification with full matching
subc.MIps.across.datasets <- matchthem(ps.formula, mi.data,
                           approach = 'across',
                method = "subclass",
                subclass = 5)
subc.MIps.across.datasets
plot(subc.MIps.across.datasets, type = "jitter")

# IPTW
weighted.across.datasets <- weightthem(ps.formula, mi.data,
                                approach = 'across', 
                                method = 'ps', estimand = 'ATM')
weighted.across.datasets
```

```{r}
bal.tab(greedy.matched.MIps.across.datasets, abs = TRUE)
bal.tab(optimal.matched.MIps.across.datasets, abs = TRUE)
bal.tab(one_two.matched.MIps.across.datasets, abs = TRUE)
bal.tab(full.matched.MIps.across.datasets, abs = TRUE)
bal.tab(subc.MIps.across.datasets, abs = TRUE)
bal.tab(weighted.across.datasets, abs = TRUE)
```

```{r}
formula1<-as.formula((paste("NAFLD_status","~ T2D+ ",paste(newvariables,collapse = "+"))))

greedy.matched.MIps.across.models <- with(data = greedy.matched.MIps.across.datasets,
                               expr = svyglm(formula1, family = quasibinomial))
greedy.matched.MIps.across.results <- pool(greedy.matched.MIps.across.models)
summary_MIps_greedy <- summary(greedy.matched.MIps.across.results, conf.int = TRUE)

optimal.matched.MIps.across.models <- with(data = optimal.matched.MIps.across.datasets,
                               expr = svyglm(formula1, family =quasibinomial))
optimal.matched.MIps.across.results <- pool(optimal.matched.MIps.across.models)
summary_MIps_optimal <-summary(optimal.matched.MIps.across.results, conf.int = TRUE)

one_two.matched.MIps.across.models <- with(data = one_two.matched.MIps.across.datasets,
                               expr = svyglm(formula1, family = quasibinomial))
one_two.matched.MIps.across.results <- pool(one_two.matched.MIps.across.models)
summary_MIps_one_two <- summary(one_two.matched.MIps.across.results, conf.int = TRUE)

full.matched.MIps.across.models <- with(data = full.matched.MIps.across.datasets,
                               expr = svyglm(formula1, family = quasibinomial))
full.matched.MIps.across.results <- pool(full.matched.MIps.across.models)
summary_MIps_full <- summary(full.matched.MIps.across.results, conf.int = TRUE)


subc.MIps.across.models <- with(data = subc.MIps.across.datasets,
                               expr = svyglm(formula1, family = quasibinomial))
subc.MIps.across.results <- pool(subc.MIps.across.models)
summary_MIps_subc <-summary(subc.MIps.across.results, conf.int = TRUE)

# IPTW

weighted.across.models <- with(data = weighted.across.datasets, expr = svyglm(formula1, family = quasibinomial))
weighted.across.results <- pool(weighted.across.models)
summary_MIps_iptw <-summary(weighted.across.results, conf.int = TRUE)

```

```{r}
NAFLD.T2D.MIps.HR.est<-c()
NAFLD.T2D.MIps.logHR.est<-c()
NAFLD.T2D.MIps.se<-c()
NAFLD.T2D.MIps.pvalue<-c()
NAFLD.T2D.MIps.lowerCI<-c()
NAFLD.T2D.MIps.upperCI<-c()

NAFLD.T2D.MIps.HR.est[1] <-exp(summary_MIps_greedy[2,2])
NAFLD.T2D.MIps.logHR.est[1]<-summary_MIps_greedy[2,2]
NAFLD.T2D.MIps.se[1]<-summary_MIps_greedy[2,3]
NAFLD.T2D.MIps.pvalue[1]<-summary_MIps_greedy[2,6]
NAFLD.T2D.MIps.lowerCI[1]<- exp(summary_MIps_greedy[2,7])
NAFLD.T2D.MIps.upperCI[1]<- exp(summary_MIps_greedy[2,8])

NAFLD.T2D.MIps.HR.est[2] <-exp(summary_MIps_optimal[2,2])
NAFLD.T2D.MIps.logHR.est[2]<-summary_MIps_optimal[2,2]
NAFLD.T2D.MIps.se[2]<-summary_MIps_optimal[2,3]
NAFLD.T2D.MIps.pvalue[2]<-summary_MIps_optimal[2,6]
NAFLD.T2D.MIps.lowerCI[2]<- exp(summary_MIps_optimal[2,7])
NAFLD.T2D.MIps.upperCI[2]<- exp(summary_MIps_optimal[2,8])

NAFLD.T2D.MIps.HR.est[3] <-exp(summary_MIps_one_two[2,2])
NAFLD.T2D.MIps.logHR.est[3]<-summary_MIps_one_two[2,2]
NAFLD.T2D.MIps.se[3]<-summary_MIps_one_two[2,3]
NAFLD.T2D.MIps.pvalue[3]<-summary_MIps_one_two[2,6]
NAFLD.T2D.MIps.lowerCI[3]<- exp(summary_MIps_one_two[2,7])
NAFLD.T2D.MIps.upperCI[3]<- exp(summary_MIps_one_two[2,8])

NAFLD.T2D.MIps.HR.est[4] <-exp(summary_MIps_full[2,2])
NAFLD.T2D.MIps.logHR.est[4]<-summary_MIps_full[2,2]
NAFLD.T2D.MIps.se[4]<-summary_MIps_full[2,3]
NAFLD.T2D.MIps.pvalue[4]<-summary_MIps_full[2,6]
NAFLD.T2D.MIps.lowerCI[4]<- exp(summary_MIps_full[2,7])
NAFLD.T2D.MIps.upperCI[4]<- exp(summary_MIps_full[2,8])

NAFLD.T2D.MIps.HR.est[5] <-exp(summary_MIps_subc[2,2])
NAFLD.T2D.MIps.logHR.est[5]<-summary_MIps_subc[2,2]
NAFLD.T2D.MIps.se[5]<-summary_MIps_subc[2,3]
NAFLD.T2D.MIps.pvalue[5]<-summary_MIps_subc[2,6]
NAFLD.T2D.MIps.lowerCI[5]<- exp(summary_MIps_subc[2,7])
NAFLD.T2D.MIps.upperCI[5]<- exp(summary_MIps_subc[2,8])

NAFLD.T2D.MIps.HR.est[6] <-exp(summary_MIps_iptw[2,2])
NAFLD.T2D.MIps.logHR.est[6]<-summary_MIps_iptw[2,2]
NAFLD.T2D.MIps.se[6]<-summary_MIps_iptw[2,3]
NAFLD.T2D.MIps.pvalue[6]<-summary_MIps_iptw[2,6]
NAFLD.T2D.MIps.lowerCI[6]<- exp(summary_MIps_iptw[2,7])
NAFLD.T2D.MIps.upperCI[6]<- exp(summary_MIps_iptw[2,8])
```

```{r}

NAFLDoutcome.T2D.MIps.result <- 
  structure(list(
    mean  = c(NA, NA, NAFLD.T2D.MIps.HR.est), 
    lower = c(NA, NA, NAFLD.T2D.MIps.lowerCI),
    upper = c(NA, NA, NAFLD.T2D.MIps.upperCI)),
    .Names = c("mean", "lower", "upper"), 
    row.names = c(NA, -8L), 
    class = "data.frame")

tabletext <- cbind(c("","Method","Greedy Matching","Optimal Matching","1:2 Matching","Full Matching","Subclassification", "IPTW"), c("","Effect", as.character(round(NAFLD.T2D.MIps.HR.est,3))), c("","SE", as.character(round(NAFLD.T2D.MIps.se,3))),c("","p-value", ifelse(NAFLD.T2D.MIps.pvalue<0.001, "<0.001", round(NAFLD.T2D.MIps.pvalue,3))))
                   
forestplot(tabletext, 
           NAFLDoutcome.T2D.result,new_page = TRUE,
           col = fpColors(box="royalblue",line="darkblue"),
           xlab = "Estimate with 95% CI",
           hrzl_lines= gpar(col = "#444444"),
           is.summary = c(TRUE, TRUE, rep(FALSE, 10)),
           clip = c(0.5,5.5), zero=1,
           txt_gp=fpTxtGp(label = gpar(cex = 0.8),
                          title = gpar(cex = 1),
                          ticks = gpar(cex = 0.8),
                          xlab = gpar(cex = 0.7)),
           grid = structure(seq(1, 5.5, by=0.25), 
                            gp = gpar(lty = 2, col = "#CCCCFF")))
grid.text("Exposure of T2D on NAFLD by MIps", .5, 0.98, gp=gpar(fontface="bold"))
```


```{r}
NAFLD.T2D<-data.frame(method=c(rep("CCA",6),rep("MIte",6),rep("MIps",6)),PSmethod=c(rep(c("Greedy Matching","Optimal Matching","1:2 Matching","Full Matching","Subclassification", "IPTW"),3)),est=c(round(NAFLD.T2D.HR.est,3),round(NAFLD.T2D.MIte.HR.est,3),round(NAFLD.T2D.MIps.HR.est,3)),log.est=c(round(NAFLD.T2D.logHR.est,3),round(NAFLD.T2D.MIte.logHR.est,3),round(NAFLD.T2D.MIps.logHR.est,3)),se=c(round(NAFLD.T2D.se,3),round(NAFLD.T2D.MIte.se,3),round(NAFLD.T2D.MIps.se,3)),pvalue=c(round(NAFLD.T2D.pvalue,3),round(NAFLD.T2D.MIte.pvalue,3),round(NAFLD.T2D.MIps.pvalue,3)),lowerCI=c(round(NAFLD.T2D.lowerCI,3),round(NAFLD.T2D.MIte.lowerCI,3),round(NAFLD.T2D.MIps.lowerCI,3)),upperCI=c(round(NAFLD.T2D.upperCI,3),round(NAFLD.T2D.MIte.upperCI,3),round(NAFLD.T2D.MIps.upperCI,3)))

NAFLD.T2D.greedy<-subset(NAFLD.T2D,PSmethod=="Greedy Matching")
NAFLD.T2D.optimal<-subset(NAFLD.T2D,PSmethod=="Optimal Matching")
NAFLD.T2D.one_two<-subset(NAFLD.T2D,PSmethod=="1:2 Matching")
NAFLD.T2D.full<-subset(NAFLD.T2D,PSmethod=="Full Matching")
NAFLD.T2D.subc<-subset(NAFLD.T2D,PSmethod=="Subclassification")
NAFLD.T2D.iptw<-subset(NAFLD.T2D,PSmethod=="IPTW")


Forstplot<-function(method,title){
  tabletext <- cbind(c("","Method","CCA","MIte","MIps"), c("","Effect", as.character(method$est)), 
                     c("","SE", as.character(method$se)),c("","p-value", 
                                                           ifelse(method$pvalue<0.001, "<0.001", method$pvalue)))
  NAFLD.T2D.result <- 
  structure(list(
    mean  = c(NA, NA, method$est), 
    lower = c(NA, NA, method$lowerCI),
    upper = c(NA, NA, method$upperCI)),
    .Names = c("mean", "lower", "upper"), 
    row.names = c(NA, -5L), 
    class = "data.frame")
  
  forestplot(tabletext, 
           NAFLD.T2D.result,
           new_page = TRUE,
           xlab = "Estimate with 95% CI",
           col = fpColors(box="royalblue",line="darkblue"),
           hrzl_lines= gpar(col = "#444444"),
           is.summary = c(TRUE, TRUE, rep(FALSE, 18)),
           clip = c(0.5,5.5), zero=1,
           txt_gp=fpTxtGp(label = gpar(cex = 0.8),
                          title = gpar(cex = 1),
                          ticks = gpar(cex = 0.7),
                          xlab = gpar(cex = 0.7)),
           grid = structure(seq(1, 5.5, by=0.5), 
                            gp = gpar(lty = 2, col = "#CCCCFF")),
           title=title)
}

Forstplot(NAFLD.T2D.greedy,"Exposure of T2D on of Greedy Matching")
Forstplot(NAFLD.T2D.optimal,"Exposure of T2D on of Optimal Matching")
Forstplot(NAFLD.T2D.one_two,"Exposure of T2D on of 1:2 Matching")
Forstplot(NAFLD.T2D.full,"Exposure of T2D on of Full Matching")
Forstplot(NAFLD.T2D.subc,"Exposure of T2D on of Subclassification Matching")
Forstplot(NAFLD.T2D.iptw,"Exposure of T2D on of IPTW ")
```

