---
title: "MI"
author: "Yun Zhu"
date: "09/11/2021"
output: pdf_document
---
This document is for doing PS omit missing data.
```{r setup, include=FALSE}
library(tidyverse)
library(MatchIt)
library(twang)
library(ggplot2)
library(dplyr)
library(lsr)
library(survey)
library(rbounds)
library(naniar)
library(tableone)
library(optmatch)
library(mice)
```

```{r warning=FALSE}
setwd("/Users/Crystal/Desktop/Practicum/Data")
NAFLD <-read_csv("data_NAFLD_PS.csv",show_col_types = FALSE)
NAFLD<-NAFLD %>%mutate(rs1260326_T=factor(rs1260326_T, levels = 0:2)) %>% 
  mutate(rs1044498_C=factor(rs1044498_C, levels = 0:2)) %>% 
  mutate(rs58542926_T=factor(rs58542926_T, levels = 0:2)) %>% 
  mutate(rs738409_G=factor(rs738409_G, levels = 0:2)) %>% 
  mutate(rs3480_G=factor(rs3480_G, levels = 0:2)) %>% 
  mutate(rs780094_T=factor(rs780094_T, levels = 0:2)) %>% 
  mutate(rs4374383_A=factor(rs4374383_A, levels = 0:2)) %>% 
  mutate(rs72613567_TA=factor(rs72613567_TA, levels = 0:2)) %>% 
  mutate(rs62305723_A=factor(rs62305723_A, levels = 0:2)) %>% 
  mutate(rs4880_A=factor(rs4880_A, levels = 0:2))%>% 
  mutate(rs3750861_T=factor(rs3750861_T, levels = 0:2))%>% 
  mutate(rs236918_C=factor(rs236918_C, levels = 0:2))%>% 
  mutate(rs12979860_T=factor(rs12979860_T, levels = 0:2))%>%
  mutate(Smoking_status_2=as.factor(ifelse(Smoking_status_2=="Never", 0, 
                         ifelse(Smoking_status_2=="Previous" | Smoking_status_2=="Current", 1, NA)))) %>%
  mutate(Alcohol_drinker_status_2=as.factor(ifelse(Alcohol_drinker_status_2=="Never", 0, 
                                  ifelse(Alcohol_drinker_status_2=="Previous" |Alcohol_drinker_status_2== "Current", 1, NA)))) %>%
  mutate(BMIdich=as.factor(ifelse(BMIdich=="<25", 0, 1))) %>%
  mutate(Sex=as.factor(ifelse(Sex=="Male", 0, 1)))
variables<-c("Sex","Age","LDL","BMI","Glucose","Triglycerides","Glycated_haemoglobin__HbA1c_","HDL_cholesterol","Waist_circumference","Disastolic_Blood_pressure_automa","Systolic_Blood_Pressure","Visceral_adipose_tissue_volume__","White_blood_cell__leukocyte__cou","Red_blood_cell__erythrocyte__cou","Albumin","Alanine_aminotransferase","Cholesterol","Creatinine","Glycated_haemoglobin__HbA1c__1","Urate","Vitamin_D","Smoking_status_2","Alcohol_drinker_status_2","BMIdich","rs1260326_T","rs1044498_C","rs58542926_T","rs738409_G","rs3480_G","rs780094_T","rs4374383_A","rs72613567_TA","rs62305723_A","rs4880_A","rs3750861_T","rs236918_C","rs12979860_T" )
```

```{r}
##############################################
############ MI #################
##############################################
#Impute the data with 10 imputations (more is better)
mi.data<-mice(NAFLD, m=10, method = "cart")
```


```{r}
c.data <- complete(mi.data, 7)
```

```{r}
out.formula1 <- as.formula((paste("NAFLD_status","~ ",paste(variables,collapse = "+"))))
out.formula2 <- as.formula((paste("T2D","~ ",paste(variables,collapse = "+"))))
```

```{r}
##Using lasso to figure out the predictors that both effect the T2D adn NAFLD status
x1<-model.matrix(out.formula1, c.data)[,-1]
y1 <- c.data$NAFLD_status
set.seed(100)
cv.l1 <- cv.glmnet(x1,y1,family="binomial",nfolds = 5,alpha=1)
best_lambda.l1<-cv.l1$lambda.min
l.mod1<- glmnet(x1,y1,family="binomial",alpha=1,lambda = best_lambda.l1)
coef.l.min1 <- coef(l.mod1)
knitr::kable(as.matrix(coef.l.min1),caption="coefficients of predictors for the optimal lambda value using lasso method")
feature1 <- rownames(coef.l.min1)[coef.l.min1[,1]!=0][-1]
feature1
```

```{r}
x2<-model.matrix(out.formula2,c.data)[,-1]
y2 <- c.data$T2D
set.seed(100)
cv.l2 <- cv.glmnet(x2,y2,family="binomial",nfolds = 5,alpha=1)
best_lambda.l2<-cv.l2$lambda.min
l.mod2 <- glmnet(x2,y2,family="binomial", alpha=1,lambda = best_lambda.l2)
coef.l.min2 <- coef(l.mod2)
knitr::kable(as.matrix(coef.l.min2),caption="coefficients of predictors for the optimal lambda value using lasso method")
feature2 <- rownames(coef.l.min2)[coef.l.min2[,1]!=0][-1]
feature2
```


```{r}
## remove glucose because it is directly related to t2d
newvariables <- c("LDL","Waist_circumference", "Albumin","Creatinine","Urate","rs1044498_C","rs3480_G","rs4880_A","rs236918_C")
tab1e<-CreateTableOne(vars=newvariables,data=c.data,strata="T2D")
print(tab1e,smd=T)
```



```{r}
ps.formula <- as.formula((paste("T2D ~",paste(newvariables,collapse = "+"))))
param<-matchit(ps.formula,data = c.data)
c.data$param_ps<-param$distance
set.seed(123456)
nonparam<-ps(as.formula((paste("T2D ~ ",paste(newvariables,collapse = "+")))),
                  data = as.data.frame(c.data),n.trees=1000,interaction.depth=9,shrinkage=0.01,
                  stop.method="es.mean",estimand="ATT")
c.data$nonparam_ps<-nonparam$ps$es.mean
summary(nonparam$gbm.obj)
```

```{r}
ggplot(data = c.data,aes(param_ps,fill=factor(T2D)))+
  geom_histogram(binwidth = 0.005,alpha = 0.5,position="identity")

```
```{r}
c.data<- omitNAFLD %>% mutate(quintile = ntile(param_ps, 5))
d <- rep(NA, 5)
for (i in 1:5) {
  dat_q <- c.data[c.data$quintile == i,]
  d[i] <- cohensD(param_ps ~ T2D, data = dat_q)
  }
d

```

```{r}
logitPS<-sd(-log(1/c.data$param_ps-1))
## Greedy matching

greedy<-matchit(ps.formula,data=c.data,
                distance="logit",
                caliper=0.1*sd(logitPS),
                method="nearest")
greedy$nn


## Optimal matching
optimal <- matchit(ps.formula,data= c.data,
                distance="logit",
                   method = "optimal")
optimal$nn


## 1:2 matching
one_two <- matchit(ps.formula,data=c.data,
                distance="logit",
                caliper=0.1*sd(logitPS),
                   method = "nearest", ratio = 2)
one_two$nn

## Full matching
full <- matchit(ps.formula,data=c.data,
                distance="logit",
                caliper=0.1*sd(logitPS),
                method = "full")
full$nn
knitr::kables(list(knitr::kable(greedy$nn,caption = "Greedy matching"),knitr::kable(optimal$nn,caption = "Optimal matching"),knitr::kable(one_two$nn,caption = "1:2 matching"),knitr::kable(full$nn,caption = "Full matching")))
```

```{r}
## Subclassification
c.data <- c.data %>% mutate(subclass = ntile(param_ps, 5))


## Subclassification with full matching
subc <- matchit(ps.formula, data = c.data,
                method = "subclass",
                subclass = 5)
knitr::kable(subc$nn,caption = "subclasses")
plot(subc, type = "jitter")
```

```{r}
### Weighting

## Odds
c.data$odds <- ifelse(c.data$T2D == 1, 1, c.data$param_ps/(1-c.data$param_ps))

## IPTW with stabilization
c.data$iptw<- ifelse(c.data$T2D == 1, (mean(c.data$param_ps))/c.data$param_ps, (mean(1-c.data$param_ps))/(1-c.data$param_ps))
```

```{r}
## Calculate standardized difference in the covariates

# Greedy matching
summary(greedy, standardize = TRUE)

# Optimal matching
summary(optimal, standardize = TRUE)

# 1:2 matching
summary(one_two, standardized = TRUE)

# Full matching
summary(full, standardize = TRUE)

# Subclassification with full matching
summary(subc, standardize=TRUE)
```
```{r}
# Weighting by odds
odds <- dx.wts(c.data$odds, data = as.data.frame(c.data), var = newvariables, treat.var="T2D", 
               estimand = "ATT")
bal.table(odds)

# Weighting by IPTW with stabilization
iptw <- dx.wts(c.data$iptw, data = as.data.frame(c.data), var = newvariables, treat.var="T2D", 
               estimand = "ATE")
bal.table(iptw)
```
```{r}
## Create Q-Q plots

# Greedy matching
plot(greedy)

# Optimal matching
plot(optimal)

# 1:2 matching
plot(one_two)

# Full matching
plot(full)

# Subclassification with full matching
plot(subc)
```

```{r}
## Create density plots

# Full matching
matched_full <- match.data(full, subclass = "block")
ggplot(data = matched_full, aes(LDL, fill = factor(T2D)), weight = weights) + geom_density(alpha = 0.5, position = "identity")
ggplot(data = matched_full, aes(Waist_circumference, fill = factor(T2D)), weight = weights) + geom_density(alpha = 0.5, position = "identity")

# Weighting by odds
ggplot(data = c.data, aes(LDL, fill = factor(T2D)), weight = odds) + geom_density(alpha = 0.5, position = "identity")
ggplot(data = c.data, aes(Waist_circumference, fill = factor(T2D)), weight = odds) + geom_density(alpha = 0.5, position = "identity")

# Weighting by IPTW with stabilization
ggplot(data = c.data, aes(LDL, fill = factor(T2D)), weight = iptw) + geom_density(alpha = 0.5, position = "identity")
ggplot(data = c.data, aes(Waist_circumference, fill = factor(T2D)), weight = iptw) + geom_density(alpha = 0.5, position = "identity")

```

```{r}
formula1<-as.formula((paste("NAFLD_status","~ T2D+ ",paste(newvariables,collapse = "+"))))
## Greedy matching
matched_greedy <- match.data(greedy,subclass = "block")
glm_NAFLD_greedy <- glm(formula1,
                          data = matched_greedy,
                          family = binomial)
summary(glm_NAFLD_greedy)
exp(coef(glm_NAFLD_greedy))


## Optimal matching
matched_optimal <- match.data(optimal,subclass = "block")
glm_NAFLD_optimal <- glm(formula1,
                           data = matched_optimal,
                           family = binomial)
summary(glm_NAFLD_optimal)
exp(coef(glm_NAFLD_optimal))


## 1:2 matching
matched_one_two <- match.data(one_two,subclass = "block")
glm_NAFLD_one_two <- glm(formula1, 
                           data = matched_one_two,
                           family = binomial)
summary(glm_NAFLD_one_two)
exp(coef(glm_NAFLD_one_two))


## Full matching
matched_full <- match.data(full,subclass = "block")
glm_NAFLD_full <- glm(formula1,
                        data = matched_full,
                        family = binomial, weights = weights)
summary(glm_NAFLD_full)
exp(coef(glm_NAFLD_full))


## Subclassification with full matching
subced <- match.data(subc,subclass = "block")
design <- svydesign(id = ~1, strata = ~subclass, weights = ~weights, nested = TRUE, data = subced)
svyglm_NAFLD_subc <- svyglm(formula1, design = design, family = binomial)
summary(svyglm_NAFLD_subc)
exp(coef(svyglm_NAFLD_subc))


## Weighting by the odds
glm_NAFLD_odds <- glm(formula1, 
                        data = c.data,
                        weights = odds,
                        family = binomial)
summary(glm_NAFLD_odds)
exp(coef(glm_NAFLD_odds))


## Weighting by IPTW with stabilization
glm_NAFLD_iptw <- glm(formula1,
                        data = c.data,
                        weights = iptw,
                        family = binomial)
summary(glm_NAFLD_iptw)
exp(coef(glm_NAFLD_iptw))
```

```{r,fig.cap="Results of a sensitivity analysis: Having a new conviction."}
matched_optimal <- match.data(optimal,subclass = "block")
mytable <- table(matched_optimal$T2D, matched_optimal$NAFLD_status)
binarysens(mytable[1, 2], mytable[2, 1], Gamma = 6, GammaInc = 1)
# the upper bound of the p-value is 0.00043 at gamma=3.The treatment effect estimate for this outcome is robust to hidden bias from unmeasured covariates up to gamma=3.
```
