---
title: "MI"
author: "Yun Zhu"
date: "09/11/2021"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(MatchIt)
library(MatchThem)
library(twang)
library(ggplot2)
library(dplyr)
library(lsr)
library(survey)
library(rbounds)
library(naniar)
library(tableone)
library(optmatch)
library(mice)
library(forestplot)
library(gtsummary)
```

```{r warning=FALSE}
setwd("/Users/Crystal/Desktop/Practicum/Data")
NAFLD <-read_csv("data_NAFLD_PS.csv",show_col_types = FALSE)
NAFLD<-NAFLD %>%mutate(Sex=as.factor(ifelse(Sex=="Male", 0, 1)))
NAFLD<-NAFLD[,c(3:4,7,8,10:12,14,41)]
variables<-c("Sex","LDL","Triglycerides","Glycated_haemoglobin__HbA1c_","HDL_cholesterol",
             "Waist_circumference","Systolic_Blood_Pressure")
```

```{r}
##############################################
############ MI #################
##############################################
#Impute the data with 5 imputations (more is better)
mi.data<-mice(NAFLD, m = 5)
c.data<-complete(mi.data)
```

```{r}
tbl_summary(c.data)
table3.1 <- 
  tbl_summary(
    c.data,
    by = NAFLD_status # split table by group
  ) %>%
  add_n() %>% # add column with total number of non-missing observations
  add_p() %>% # test for a difference between groups
  modify_header(label = "**Variable**") %>% # update the column header
  bold_labels() 
table3.1
table3.2 <- 
  tbl_summary(
    c.data,
    by = T2D # split table by group
  ) %>%
  add_n() %>% # add column with total number of non-missing observations
  add_p() %>% # test for a difference between groups
  modify_header(label = "**Variable**") %>% # update the column header
  bold_labels() 
table3.2
table3.3 <- 
  tbl_summary(
    c.data,
    by = BMIdich # split table by group
  ) %>%
  add_n() %>% # add column with total number of non-missing observations
  add_p() %>% # test for a difference between groups
  modify_header(label = "**Variable**") %>% # update the column header
  bold_labels() 
table3.3
```

```{r}
out.formula1 <- as.formula((paste("NAFLD_status","~ ",paste(variables,collapse = "+"))))
out.formula2 <- as.formula((paste("T2D","~ ",paste(variables,collapse = "+"))))
```


```{r}
## remove glucose because it is directly related to t2d
newvariables <- c("Glycated_haemoglobin__HbA1c_","Waist_circumference")
```

```{r}
ps.formula <- as.formula((paste("T2D ~",paste(newvariables,collapse = "+"))))
#
estimate_ps<-function(equation, dat){
  ps_model <- glm(equation, family = binomial, data=dat)
  dat$ps<-predict(ps_model, type = "response")
  for(i in 1:length(dat$ps)){
  dat$iptw[i] <- ifelse(dat$T2D[i] == "1", 1/as.numeric(dat$ps[i]), 1/(1-as.numeric(dat$ps[i])))
}
  return(dat)
}

```



```{r}
############MIte#############
## Greedy matching
greedy.matched.datasets <- matchthem(ps.formula, mi.data,
                          approach = 'within',
                          method = 'nearest',
                          caliper = 0.05)
## Optimal matching
optimal.matched.datasets <- matchthem(ps.formula, mi.data,
                          approach = 'within',
                          method = 'optimal',
                          caliper = 0.05)
## 1:2 matching
one_two.matched.datasets <- matchthem(ps.formula, mi.data,
                          approach = 'within',
                          method = 'nearest',
                          caliper = 0.05, ratio = 2)
## Full matching
full.matched.datasets <- matchthem(ps.formula,mi.data,
                                 approach = 'within',
                                 caliper = 0.05,
                                 method = "full")

## Subclassification with full matching
subc.datasets <- matchthem(ps.formula, mi.data,
                           approach = 'within',
                method = "subclass",
                subclass = 5)
subc.datasets
plot(subc.datasets, type = "jitter")

# IPTW
weighted.datasets <- weightthem(ps.formula, mi.data,
                                approach = 'within', 
                                method = 'ps', estimand = 'ATM')
weighted.datasets
```

```{r}
library(cobalt)
bal.tab(greedy.matched.datasets, abs = TRUE)
bal.tab(optimal.matched.datasets, abs = TRUE)
bal.tab(one_two.matched.datasets, abs = TRUE)
bal.tab(full.matched.datasets, abs = TRUE)
bal.tab(subc.datasets, abs = TRUE)
bal.tab(weighted.datasets, abs = TRUE)
```
```{r}
library(survey)
formula1<-as.formula((paste("NAFLD_status","~ T2D+ ",paste(newvariables,collapse = "+"))))

greedy.matched.models <- with(data = greedy.matched.datasets,
                               expr = svyglm(formula1, family = quasibinomial))
greedy.matched.results <- pool(greedy.matched.models)
summary_greedy <- summary(greedy.matched.results, conf.int = TRUE)

optimal.matched.models <- with(data = optimal.matched.datasets,
                               expr = svyglm(formula1, family =quasibinomial))
optimal.matched.results <- pool(optimal.matched.models)
summary_optimal <-summary(optimal.matched.results, conf.int = TRUE)

one_two.matched.models <- with(data = one_two.matched.datasets,
                               expr = svyglm(formula1, family = quasibinomial))
one_two.matched.results <- pool(one_two.matched.models)
summary_one_two <- summary(one_two.matched.results, conf.int = TRUE)

full.matched.models <- with(data = full.matched.datasets,
                               expr = svyglm(formula1, family = quasibinomial))
full.matched.results <- pool(full.matched.models)
summary_full <- summary(full.matched.results, conf.int = TRUE)


subc.models <- with(data = subc.datasets,
                               expr = svyglm(formula1, family = quasibinomial))
subc.results <- pool(subc.models)
summary_subc <-summary(subc.results, conf.int = TRUE)

# IPTW

weighted.models <- with(data = weighted.datasets, expr = svyglm(formula1, family = quasibinomial))
weighted.results <- pool(weighted.models)
summary_iptw <-summary(weighted.results, conf.int = TRUE)

```
```{r}
knitr::kable(summary_greedy,digits = 3,caption = "summary table of greedy matching")
knitr::kable(summary_optimal,digits = 3,caption = "summary table of optimal matching")
knitr::kable(summary_one_two,digits = 3,caption = "summary table of 1:2 matching")
knitr::kable(summary_full,digits = 3,caption = "summary table of full matching")
knitr::kable(summary_subc,digits = 3,caption = "summary table of subclassification")
knitr::kable(summary_iptw,digits = 3,caption = "summary table of weighting by iptw")
```

```{r}
NAFLD.T2D.MIte.HR.est<-c()
NAFLD.T2D.MIte.logHR.est<-c()
NAFLD.T2D.MIte.se<-c()
NAFLD.T2D.MIte.pvalue<-c()
NAFLD.T2D.MIte.lowerCI<-c()
NAFLD.T2D.MIte.upperCI<-c()

NAFLD.T2D.MIte.HR.est[1] <-exp(summary_greedy[2,2])
NAFLD.T2D.MIte.logHR.est[1]<-summary_greedy[2,2]
NAFLD.T2D.MIte.se[1]<-summary_greedy[2,3]
NAFLD.T2D.MIte.pvalue[1]<-summary_greedy[2,6]
NAFLD.T2D.MIte.lowerCI[1]<- exp(summary_greedy[2,7])
NAFLD.T2D.MIte.upperCI[1]<- exp(summary_greedy[2,8])

NAFLD.T2D.MIte.HR.est[2] <-exp(summary_optimal[2,2])
NAFLD.T2D.MIte.logHR.est[2]<-summary_optimal[2,2]
NAFLD.T2D.MIte.se[2]<-summary_optimal[2,3]
NAFLD.T2D.MIte.pvalue[2]<-summary_optimal[2,6]
NAFLD.T2D.MIte.lowerCI[2]<- exp(summary_optimal[2,7])
NAFLD.T2D.MIte.upperCI[2]<- exp(summary_optimal[2,8])

NAFLD.T2D.MIte.HR.est[3] <-exp(summary_one_two[2,2])
NAFLD.T2D.MIte.logHR.est[3]<-summary_one_two[2,2]
NAFLD.T2D.MIte.se[3]<-summary_one_two[2,3]
NAFLD.T2D.MIte.pvalue[3]<-summary_one_two[2,6]
NAFLD.T2D.MIte.lowerCI[3]<- exp(summary_one_two[2,7])
NAFLD.T2D.MIte.upperCI[3]<- exp(summary_one_two[2,8])

NAFLD.T2D.MIte.HR.est[4] <-exp(summary_full[2,2])
NAFLD.T2D.MIte.logHR.est[4]<-summary_full[2,2]
NAFLD.T2D.MIte.se[4]<-summary_full[2,3]
NAFLD.T2D.MIte.pvalue[4]<-summary_full[2,6]
NAFLD.T2D.MIte.lowerCI[4]<- exp(summary_full[2,7])
NAFLD.T2D.MIte.upperCI[4]<- exp(summary_full[2,8])

NAFLD.T2D.MIte.HR.est[5] <-exp(summary_subc[2,2])
NAFLD.T2D.MIte.logHR.est[5]<-summary_subc[2,2]
NAFLD.T2D.MIte.se[5]<-summary_subc[2,3]
NAFLD.T2D.MIte.pvalue[5]<-summary_subc[2,6]
NAFLD.T2D.MIte.lowerCI[5]<- exp(summary_subc[2,7])
NAFLD.T2D.MIte.upperCI[5]<- exp(summary_subc[2,8])

NAFLD.T2D.MIte.HR.est[6] <-exp(summary_iptw[2,2])
NAFLD.T2D.MIte.logHR.est[6]<-summary_iptw[2,2]
NAFLD.T2D.MIte.se[6]<-summary_iptw[2,3]
NAFLD.T2D.MIte.pvalue[6]<-summary_iptw[2,6]
NAFLD.T2D.MIte.lowerCI[6]<- exp(summary_iptw[2,7])
NAFLD.T2D.MIte.upperCI[6]<- exp(summary_iptw[2,8])
```

```{r}
NAFLDoutcome.T2D.result <- 
  structure(list(
    mean  = c(NA, NA, NAFLD.T2D.MIte.HR.est), 
    lower = c(NA, NA, NAFLD.T2D.MIte.lowerCI),
    upper = c(NA, NA, NAFLD.T2D.MIte.upperCI)),
    .Names = c("mean", "lower", "upper"), 
    row.names = c(NA, -8L), 
    class = "data.frame")

A <- cbind2(c("","Method","Greedy Matching","Optimal Matching","1:2 Matching","Full Matching","Subclassification", "IPTW"),
               c("","Effect", as.character(round(NAFLD.T2D.MIte.HR.est,3))))
B<- cbind2(c("","SE", as.character(round(NAFLD.T2D.MIte.se,3))),
           c("","p-value", ifelse(NAFLD.T2D.MIte.pvalue<0.001, "<0.001", round(NAFLD.T2D.MIte.pvalue,3))))
tabletext <- cbind2(A ,B)

forestplot(tabletext, 
           NAFLDoutcome.T2D.result,new_page = TRUE,
           col = fpColors(box="royalblue",line="darkblue"),
           xlab = "Estimate with 95% CI",
           hrzl_lines= gpar(col = "#444444"),
           is.summary = c(TRUE, TRUE, rep(FALSE, 10)),
           clip = c(0.5,5.5), zero=1,
           txt_gp=fpTxtGp(label = gpar(cex = 0.8),
                          title = gpar(cex = 1),
                          ticks = gpar(cex = 0.7),
                          xlab = gpar(cex = 0.7)),
           grid = structure(seq(0.5, 5.5, by=0.25), 
                            gp = gpar(lty = 2, col = "#CCCCFF")))
grid.text("Exposure of T2D on NAFLD", .5, 0.98, gp=gpar(fontface="bold"))
```
```{r}
##############MIps##############
## Greedy matching
greedy.matched.across.datasets <- matchthem(ps.formula, mi.data,
                          approach = 'across',
                          method = 'nearest',
                          caliper = 0.05)
## Optimal matching
optimal.matched.across.datasets <- matchthem(ps.formula, mi.data,
                          approach = 'across',
                          method = 'optimal',
                          caliper = 0.05)
## 1:2 matching
one_two.matched.across.datasets <- matchthem(ps.formula, mi.data,
                          approach = 'across',
                          method = 'nearest',
                          caliper = 0.05, ratio = 2)
## Full matching
full.matched.across.datasets <- matchthem(ps.formula,mi.data,
                                 approach = 'across',
                                 caliper = 0.05,
                                 method = "full")

## Subclassification with full matching
subc.across.datasets <- matchthem(ps.formula, mi.data,
                           approach = 'across',
                method = "subclass",
                subclass = 5)
subc.across.datasets
plot(subc.across.datasets, type = "jitter")

# IPTW
weighted.across.datasets <- weightthem(ps.formula, mi.data,
                                approach = 'across', 
                                method = 'ps', estimand = 'ATM')
weighted.across.datasets
```
```{r}
library(cobalt)
bal.tab(greedy.matched.across.datasets, abs = TRUE)
bal.tab(optimal.matched.across.datasets, abs = TRUE)
bal.tab(one_two.matched.across.datasets, abs = TRUE)
bal.tab(full.matched.across.datasets, abs = TRUE)
bal.tab(subc.across.datasets, abs = TRUE)
bal.tab(weighted.across.datasets, abs = TRUE)
```

```{r}
library(survey)
formula1<-as.formula((paste("NAFLD_status","~ T2D+ ",paste(newvariables,collapse = "+"))))

greedy.matched.across.models <- with(data = greedy.matched.across.datasets,
                               expr = svyglm(formula1, family = quasibinomial))
greedy.matched.across.results <- pool(greedy.matched.across.models)
summary_greedy <- summary(greedy.matched.across.results, conf.int = TRUE)

optimal.matched.across.models <- with(data = optimal.matched.across.datasets,
                               expr = svyglm(formula1, family =quasibinomial))
optimal.matched.across.results <- pool(optimal.matched.across.models)
summary_optimal <-summary(optimal.matched.across.results, conf.int = TRUE)

one_two.matched.across.models <- with(data = one_two.matched.across.datasets,
                               expr = svyglm(formula1, family = quasibinomial))
one_two.matched.across.results <- pool(one_two.matched.across.models)
summary_one_two <- summary(one_two.matched.across.results, conf.int = TRUE)

full.matched.across.models <- with(data = full.matched.across.datasets,
                               expr = svyglm(formula1, family = quasibinomial))
full.matched.across.results <- pool(full.matched.across.models)
summary_full <- summary(full.matched.across.results, conf.int = TRUE)


subc.across.models <- with(data = subc.across.datasets,
                               expr = svyglm(formula1, family = quasibinomial))
subc.across.results <- pool(subc.across.models)
summary_subc <-summary(subc.across.results, conf.int = TRUE)

# IPTW

weighted.across.models <- with(data = weighted.across.datasets, expr = svyglm(formula1, family = quasibinomial))
weighted.across.results <- pool(weighted.across.models)
summary_iptw <-summary(weighted.across.results, conf.int = TRUE)

```
```{r}
knitr::kable(summary_greedy,digits = 3,caption = "summary table of greedy matching")
knitr::kable(summary_optimal,digits = 3,caption = "summary table of optimal matching")
knitr::kable(summary_one_two,digits = 3,caption = "summary table of 1:2 matching")
knitr::kable(summary_full,digits = 3,caption = "summary table of full matching")
knitr::kable(summary_subc,digits = 3,caption = "summary table of subclassification")
knitr::kable(summary_iptw,digits = 3,caption = "summary table of weighting by iptw")
```

```{r}
NAFLD.T2D.MIps.HR.est<-c()
NAFLD.T2D.MIps.logHR.est<-c()
NAFLD.T2D.MIps.se<-c()
NAFLD.T2D.MIps.pvalue<-c()
NAFLD.T2D.MIps.lowerCI<-c()
NAFLD.T2D.MIps.upperCI<-c()

NAFLD.T2D.MIps.HR.est[1] <-exp(summary_greedy[2,2])
NAFLD.T2D.MIps.logHR.est[1]<-summary_greedy[2,2]
NAFLD.T2D.MIps.se[1]<-summary_greedy[2,3]
NAFLD.T2D.MIps.pvalue[1]<-summary_greedy[2,6]
NAFLD.T2D.MIps.lowerCI[1]<- exp(summary_greedy[2,7])
NAFLD.T2D.MIps.upperCI[1]<- exp(summary_greedy[2,8])

NAFLD.T2D.MIps.HR.est[2] <-exp(summary_optimal[2,2])
NAFLD.T2D.MIps.logHR.est[2]<-summary_optimal[2,2]
NAFLD.T2D.MIps.se[2]<-summary_optimal[2,3]
NAFLD.T2D.MIps.pvalue[2]<-summary_optimal[2,6]
NAFLD.T2D.MIps.lowerCI[2]<- exp(summary_optimal[2,7])
NAFLD.T2D.MIps.upperCI[2]<- exp(summary_optimal[2,8])

NAFLD.T2D.MIps.HR.est[3] <-exp(summary_one_two[2,2])
NAFLD.T2D.MIps.logHR.est[3]<-summary_one_two[2,2]
NAFLD.T2D.MIps.se[3]<-summary_one_two[2,3]
NAFLD.T2D.MIps.pvalue[3]<-summary_one_two[2,6]
NAFLD.T2D.MIps.lowerCI[3]<- exp(summary_one_two[2,7])
NAFLD.T2D.MIps.upperCI[3]<- exp(summary_one_two[2,8])

NAFLD.T2D.MIps.HR.est[4] <-exp(summary_full[2,2])
NAFLD.T2D.MIps.logHR.est[4]<-summary_full[2,2]
NAFLD.T2D.MIps.se[4]<-summary_full[2,3]
NAFLD.T2D.MIps.pvalue[4]<-summary_full[2,6]
NAFLD.T2D.MIps.lowerCI[4]<- exp(summary_full[2,7])
NAFLD.T2D.MIps.upperCI[4]<- exp(summary_full[2,8])

NAFLD.T2D.MIps.HR.est[5] <-exp(summary_subc[2,2])
NAFLD.T2D.MIps.logHR.est[5]<-summary_subc[2,2]
NAFLD.T2D.MIps.se[5]<-summary_subc[2,3]
NAFLD.T2D.MIps.pvalue[5]<-summary_subc[2,6]
NAFLD.T2D.MIps.lowerCI[5]<- exp(summary_subc[2,7])
NAFLD.T2D.MIps.upperCI[5]<- exp(summary_subc[2,8])

NAFLD.T2D.MIps.HR.est[6] <-exp(summary_iptw[2,2])
NAFLD.T2D.MIps.logHR.est[6]<-summary_iptw[2,2]
NAFLD.T2D.MIps.se[6]<-summary_iptw[2,3]
NAFLD.T2D.MIps.pvalue[6]<-summary_iptw[2,6]
NAFLD.T2D.MIps.lowerCI[6]<- exp(summary_iptw[2,7])
NAFLD.T2D.MIps.upperCI[6]<- exp(summary_iptw[2,8])
```

```{r}
NAFLDoutcome.T2D.result <- 
  structure(list(
    mean  = c(NA, NA, NAFLD.T2D.MIps.HR.est), 
    lower = c(NA, NA, NAFLD.T2D.MIps.lowerCI),
    upper = c(NA, NA, NAFLD.T2D.MIps.upperCI)),
    .Names = c("mean", "lower", "upper"), 
    row.names = c(NA, -8L), 
    class = "data.frame")

A <- cbind2(c("","Method","Greedy Matching","Optimal Matching","1:2 Matching","Full Matching","Subclassification", "IPTW"),
               c("","Effect", as.character(round(NAFLD.T2D.MIps.HR.est,3))))
B<- cbind2(c("","SE", as.character(round(NAFLD.T2D.MIps.se,3))),
           c("","p-value", ifelse(NAFLD.T2D.MIps.pvalue<0.001, "<0.001", round(NAFLD.T2D.MIps.pvalue,3))))
tabletext <- cbind2(A ,B)

forestplot(tabletext, 
           NAFLDoutcome.T2D.result,new_page = TRUE,
           col = fpColors(box="royalblue",line="darkblue"),
           xlab = "Estimate with 95% CI",
           hrzl_lines= gpar(col = "#444444"),
           is.summary = c(TRUE, TRUE, rep(FALSE, 10)),
           clip = c(0.5,5.5), zero=1,
           txt_gp=fpTxtGp(label = gpar(cex = 0.8),
                          title = gpar(cex = 1),
                          ticks = gpar(cex = 0.7),
                          xlab = gpar(cex = 0.7)),
           grid = structure(seq(0.5, 5.5, by=0.25), 
                            gp = gpar(lty = 2, col = "#CCCCFF")))
grid.text("Exposure of T2D on NAFLD by MIps", .5, 0.98, gp=gpar(fontface="bold"))
```

