---
title: "Results for T2D"
author: "Yun Zhu"
date: "08/03/2022"
output: pdf_document
---

```{r}
library(tidyverse)
library(MatchIt)
library(twang)
library(glmnet)
library(ggplot2)
library(dplyr)
library(lsr)
library(survey)
library(rbounds)
library(naniar)
library(tableone)
library(optmatch)
library(mice)
library(plotmo)
library(corrplot)
library(ggplot2)
library(forestplot)
library(ggcorrplot)
library(MatchThem)
library(gtsummary)
library(rstatix)
```

```{r}
setwd("/Users/Crystal/Desktop/Practicum/Data")
NAFLD <-read_csv("data_NAFLD_PS.csv",show_col_types = FALSE)
NAFLD<-NAFLD %>%mutate(Sex=as.factor(ifelse(Sex=="Male", 0, 1)))
NAFLD<-NAFLD[,c(3:4,7,8,10:12,14,27,41)]
variables<-c("Sex","LDL","Triglycerides","Glycated_haemoglobin__HbA1c_",
             "HDL_cholesterol","Waist_circumference","Systolic_Blood_Pressure","BMIdich")
```

```{r}
################################
############# CCA ##############
################################
# Omit all the missing value
omitNAFLD<- na.omit(NAFLD)
summary_glm<-summary(glm(NAFLD_status~T2D,family ="binomial",data = omitNAFLD))

################################
############# MI ###############
################################

#Impute the data with 10 imputations (more is better)
set.seed(1234)
mi.data<-mice(NAFLD,m=10)
c.data<-complete(mi.data)
summary_glm_mi<-summary(glm(NAFLD_status~T2D,data = c.data))
```
# Normal LASSO
## CCA
```{r}
################################
############# CCA ##############
################################
newvariables.normal<-c("LDL", "Triglycerides", "Glycated_haemoglobin__HbA1c_", "Waist_circumference","Systolic_Blood_Pressure", "BMIdich")
ps.formula <- as.formula((paste("T2D ~",paste(newvariables.normal,collapse = "+"))))
set.seed(1234)
param<-matchit(ps.formula,data = omitNAFLD)
omitNAFLD$param_ps<-param$distance
ggplot(data = omitNAFLD,aes(param_ps,fill=factor(T2D)))+
  geom_histogram(binwidth = 0.005,alpha = 0.5,position="identity")
logitPS<-sd(-log(1/omitNAFLD$param_ps-1))
set.seed(1234)
## Greedy matching
greedy<-matchit(ps.formula,data=omitNAFLD,
                distance="logit",
                caliper=0.1*sd(logitPS),
                method="nearest")
greedy
set.seed(1234)
## Optimal matching
optimal <- matchit(ps.formula,data= omitNAFLD,
                   distance="logit",
                   method = "optimal")
optimal
set.seed(1234)
## 1:2 matching
one_two <- matchit(ps.formula,data=omitNAFLD,
                   distance="logit",
                   caliper=0.1*sd(logitPS),
                   method = "nearest", ratio = 2)
one_two
set.seed(1234)
## Full matching
full <- matchit(ps.formula,data=omitNAFLD,
                distance="logit",
                caliper=0.1*sd(logitPS),
                method = "full")
full
set.seed(1234)
## Subclassification
omitNAFLD <- omitNAFLD %>% mutate(subclass = ntile(param_ps, 5))

## Subclassification with full matching
subc <- matchit(ps.formula, data = omitNAFLD,
                method = "subclass",
                subclass = 5)
subc

plot(subc, type = "jitter")

### Weighting
set.seed(1234)
## IPTW with stabilization
omitNAFLD$iptw<- ifelse(omitNAFLD$T2D == 1, (mean(omitNAFLD$param_ps))/omitNAFLD$param_ps, 
                        (mean(1-omitNAFLD$param_ps))/(1-omitNAFLD$param_ps))

iptw <- dx.wts(omitNAFLD$iptw, data = as.data.frame(omitNAFLD), treat.var="T2D", 
               estimand = "ATT")

# NAFLD_status~T2D
formula1<-as.formula((paste("NAFLD_status","~ T2D+ ",paste(newvariables.normal,collapse = "+"))))
set.seed(1234)
## Greedy matching
matched_greedy <- match.data(greedy,subclass = "block")
glm_NAFLD_greedy <- glm(formula1,data = matched_greedy,family = binomial)
summary_greedy <- summary(glm_NAFLD_greedy)
exp(coef(glm_NAFLD_greedy))

set.seed(1234)
## Optimal matching
matched_optimal <- match.data(optimal,subclass = "block")
glm_NAFLD_optimal <- glm(formula1,
                         data = matched_optimal,
                         family = binomial)
summary_optimal <- summary(glm_NAFLD_optimal)
exp(coef(glm_NAFLD_optimal))

set.seed(1234)
## 1:2 matching
matched_one_two <- match.data(one_two,subclass = "block")
glm_NAFLD_one_two <- glm(formula1, 
                         data = matched_one_two,
                         family = binomial)
summary_one_two <- summary(glm_NAFLD_one_two)
exp(coef(glm_NAFLD_one_two))

set.seed(1234)
## Full matching
matched_full <- match.data(full,subclass = "block")
glm_NAFLD_full <- glm(formula1,
                      data = matched_full,
                      family = binomial, weights = weights)
summary_full <-summary(glm_NAFLD_full)
exp(coef(glm_NAFLD_full))

set.seed(1234)
## Subclassification with full matching
subced <- match.data(subc,subclass = "block")
design <- svydesign(id = ~1, strata = ~subclass, weights = ~weights, nested = TRUE, data = subced)
svyglm_NAFLD_subc <- svyglm(formula1, design = design, family = binomial)
summary_subc <- summary(svyglm_NAFLD_subc)
exp(coef(svyglm_NAFLD_subc))

set.seed(1234)
## Weighting by IPTW with stabilization
glm_NAFLD_iptw <- glm(formula1,
                      data = omitNAFLD,
                      weights = iptw,
                      family = "binomial")
summary_iptw <-summary(glm_NAFLD_iptw)
exp(coef(glm_NAFLD_iptw))

NAFLD.T2D.HR.est<-c()
NAFLD.T2D.logHR.est<-c()
NAFLD.T2D.se<-c()
NAFLD.T2D.pvalue<-c()
NAFLD.T2D.lowerCI<-c()
NAFLD.T2D.upperCI<-c()

NAFLD.T2D.HR.est[1] <-exp(summary_greedy$coefficients[2,1])
NAFLD.T2D.logHR.est[1]<-summary_greedy$coefficients[2,1]
NAFLD.T2D.se[1]<-summary_greedy$coefficients[2,2]
NAFLD.T2D.pvalue[1]<-summary_greedy$coefficients[2,4]
NAFLD.T2D.lowerCI[1]<- exp(summary_greedy$coefficients[2,1]-1.96*summary_greedy$coefficients[2,2])
NAFLD.T2D.upperCI[1]<- exp(summary_greedy$coefficients[2,1]+1.96*summary_greedy$coefficients[2,2])

NAFLD.T2D.HR.est[2] <-exp(summary_optimal$coefficients[2,1])
NAFLD.T2D.logHR.est[2]<-summary_optimal$coefficients[2,1]
NAFLD.T2D.se[2]<-summary_optimal$coefficients[2,2]
NAFLD.T2D.pvalue[2]<-summary_optimal$coefficients[2,4]
NAFLD.T2D.lowerCI[2]<- exp(summary_optimal$coefficients[2,1]-1.96*summary_optimal$coefficients[2,2])
NAFLD.T2D.upperCI[2]<- exp(summary_optimal$coefficients[2,1]+1.96*summary_optimal$coefficients[2,2])

NAFLD.T2D.HR.est[3] <-exp(summary_one_two$coefficients[2,1])
NAFLD.T2D.logHR.est[3]<-summary_one_two$coefficients[2,1]
NAFLD.T2D.se[3]<-summary_one_two$coefficients[2,2]
NAFLD.T2D.pvalue[3]<-summary_one_two$coefficients[2,4]
NAFLD.T2D.lowerCI[3]<- exp(summary_one_two$coefficients[2,1]-1.96*summary_one_two$coefficients[2,2])
NAFLD.T2D.upperCI[3]<- exp(summary_one_two$coefficients[2,1]+1.96*summary_one_two$coefficients[2,2])

NAFLD.T2D.HR.est[4] <-exp(summary_full$coefficients[2,1])
NAFLD.T2D.logHR.est[4]<-summary_full$coefficients[2,1]
NAFLD.T2D.se[4]<-summary_full$coefficients[2,2]
NAFLD.T2D.pvalue[4]<-summary_full$coefficients[2,4]
NAFLD.T2D.lowerCI[4]<- exp(summary_full$coefficients[2,1]-1.96*summary_full$coefficients[2,2])
NAFLD.T2D.upperCI[4]<- exp(summary_full$coefficients[2,1]+1.96*summary_full$coefficients[2,2])

NAFLD.T2D.HR.est[5] <-exp(summary_subc$coefficients[2,1])
NAFLD.T2D.logHR.est[5]<-summary_subc$coefficients[2,1]
NAFLD.T2D.se[5]<-summary_subc$coefficients[2,2]
NAFLD.T2D.pvalue[5]<-summary_subc$coefficients[2,4]
NAFLD.T2D.lowerCI[5]<- exp(summary_subc$coefficients[2,1]-1.96*summary_subc$coefficients[2,2])
NAFLD.T2D.upperCI[5]<- exp(summary_subc$coefficients[2,1]+1.96*summary_subc$coefficients[2,2])

NAFLD.T2D.HR.est[6] <-exp(summary_iptw$coefficients[2,1])
NAFLD.T2D.logHR.est[6]<-summary_iptw$coefficients[2,1]
NAFLD.T2D.se[6]<-summary_iptw$coefficients[2,2]
NAFLD.T2D.pvalue[6]<-summary_iptw$coefficients[2,4]
NAFLD.T2D.lowerCI[6]<- exp(summary_iptw$coefficients[2,1]-1.96*summary_iptw$coefficients[2,2])
NAFLD.T2D.upperCI[6]<- exp(summary_iptw$coefficients[2,1]+1.96*summary_iptw$coefficients[2,2])

NAFLD.T2D.HR.est[7] <-exp(summary_glm$coefficients[2,1])
NAFLD.T2D.logHR.est[7]<-summary_glm$coefficients[2,1]
NAFLD.T2D.se[7]<-summary_glm$coefficients[2,2]
NAFLD.T2D.pvalue[7]<-summary_glm$coefficients[2,4]
NAFLD.T2D.lowerCI[7]<- exp(summary_glm$coefficients[2,1]-1.96*summary_glm$coefficients[2,2])
NAFLD.T2D.upperCI[7]<- exp(summary_glm$coefficients[2,1]+1.96*summary_glm$coefficients[2,2])

NAFLDoutcome.T2D.result <- 
  structure(list(
    mean  = c(NA, NA, NAFLD.T2D.HR.est), 
    lower = c(NA, NA, NAFLD.T2D.lowerCI),
    upper = c(NA, NA, NAFLD.T2D.upperCI)),
    .Names = c("mean", "lower", "upper"), 
    row.names = c(NA, -8L), 
    class = "data.frame")

A <- cbind2(c("","Method","Greedy Matching","Optimal Matching","1:2 Matching",
              "Full Matching","Stratification with 5 groups", "IPTW","Crude"),
                 c("","Effect", as.character(round(NAFLD.T2D.HR.est,3))))
B<- cbind2(c("","SE", as.character(round(NAFLD.T2D.se,3))),
           c("","p-value", ifelse(NAFLD.T2D.pvalue<0.001, "<0.001", round(NAFLD.T2D.pvalue,3))))
tabletext <- cbind2(A ,B)

forestplot(tabletext, 
           NAFLDoutcome.T2D.result,new_page = TRUE,
           col = fpColors(box="royalblue",line="darkblue"),
           xlab = "Estimate with 95% CI",
           hrzl_lines= gpar(col = "#444444"),
           is.summary = c(TRUE, TRUE, rep(FALSE, 10)),
           clip = c(0.5,5.5), zero=1,
           txt_gp=fpTxtGp(label = gpar(cex = 0.8),
                          title = gpar(cex = 1),
                          ticks = gpar(cex = 0.7),
                          xlab = gpar(cex = 0.7)),
           xticks=(c(0.5,1, 1.5)))
grid.text("Exposure of T2D on NAFLD", .5, 0.98, gp=gpar(fontface="bold"))
```

```{r}
## Calculate standardized difference in the covariates
# Greedy matching
sum_greedy_CCA_normallasso<-summary(greedy, standardize = TRUE)

# Optimal matching
sum_optimal_CCA_normallasso<-summary(optimal, standardize = TRUE)

# 1:2 matching
sum_one_two_CCA_normallasso<-summary(one_two, standardized = TRUE)

# Full matching
sum_full_CCA_normallasso<-summary(full, standardize = TRUE)

# Subclassification with full matching
sum_subc_CCA_normallasso<-summary(subc, standardize=TRUE)


sum_CCA_normallasso<-bind_cols(sum_greedy_CCA_normallasso$sum.all[3,],sum_optimal_CCA_normallasso$sum.all[3,],sum_one_two_CCA_normallasso$sum.all[3,],sum_full_CCA_normallasso$sum.all[3,],sum_subc_CCA_normallasso$sum.all[3,],sum_iptw_CCA_normallasso$sum.all[3,])
colnames(sum_CCA_normallasso)<-c("Greedy Matching","Optimal Matching","1:2 Matching",
              "Full Matching","Stratification with 5 groups", "IPTW")

ggplot(data = matched_full, aes(T2D, fill = factor(NAFLD_status)),
       weight = weights) + geom_density(alpha = 0.5, position = "identity")
```

## MIte
```{r}
################################
############# MI ###############
################################



################################
############MIte################
################################
set.seed(1234)
## Greedy matching
greedy.matched.MIte.datasets <- matchthem(ps.formula, mi.data,
                                          approach = 'within',
                                          method = 'nearest',
                                          caliper = 0.05)
greedy.matched.MIte.datasets

set.seed(1234)
## Optimal matching
optimal.matched.MIte.datasets <- matchthem(ps.formula, mi.data,
                                           approach = 'within',
                                           method = 'optimal',
                                           caliper = 0.05)
optimal.matched.MIte.datasets

set.seed(1234)
## 1:2 matching
one_two.matched.MIte.datasets <- matchthem(ps.formula, mi.data,
                                           approach = 'within',
                                           method = 'nearest',
                                           caliper = 0.05, ratio = 2)
one_two.matched.MIte.datasets 

set.seed(1234)
## Full matching
full.matched.MIte.datasets <- matchthem(ps.formula,mi.data,
                                        approach = 'within',
                                        caliper = 0.05,
                                        method = "full")
full.matched.MIte.datasets

set.seed(1234)
## Subclassification with full matching
subc.MIte.datasets <- matchthem(ps.formula, mi.data,
                                approach = 'within',
                                method = "subclass",
                                subclass = 5)
subc.MIte.datasets
plot(subc.MIte.datasets, type = "jitter")

set.seed(1234)
# IPTW
weighted.MIte.datasets <- weightthem(ps.formula, mi.data,
                                     approach = 'within', 
                                     method = 'ps', estimand = 'ATM')
weighted.MIte.datasets

library(cobalt)
sum_greedy_MIte_normallasso<-bal.tab(greedy.matched.MIte.datasets, abs = TRUE)
sum_optimal_MIte_normallasso<-bal.tab(optimal.matched.MIte.datasets, abs = TRUE)
sum_one_two_MIte_normallasso<-bal.tab(one_two.matched.MIte.datasets, abs = TRUE)
sum_full_MIte_normallasso<-bal.tab(full.matched.MIte.datasets, abs = TRUE)
sum_subc_MIte_normallasso<-bal.tab(subc.MIte.datasets, abs = TRUE)
sum_iptw_MIte_normallasso<-bal.tab(weighted.MIte.datasets, abs = TRUE)

sum_MIte_normallasso<-cbind(sum_greedy_MIte_normallasso$Balance.Across.Imputations[6],sum_optimal_MIte_normallasso$Balance.Across.Imputations[6],sum_one_two_MIte_normallasso$Balance.Across.Imputations[6],sum_full_MIte_normallasso$Balance.Across.Imputations[6],sum_subc_MIte_normallasso$Balance.Across.Imputations[6],sum_iptw_MIte_normallasso$Balance.Across.Imputations[6])
colnames(sum_MIte_normallasso)<-c("Greedy Matching","Optimal Matching","1:2 Matching",
              "Full Matching","Stratification with 5 groups", "IPTW")

library(survey)
formula1<-as.formula((paste("NAFLD_status","~ T2D+ ",paste(newvariables.normal,collapse = "+"))))
set.seed(1234)
greedy.matched.MIte.models <- with(data = greedy.matched.MIte.datasets,
                                   expr = svyglm(formula1, family = quasibinomial))
set.seed(1234)
greedy.matched.MIte.results <- pool(greedy.matched.MIte.models)
summary_MIte_greedy <- summary(greedy.matched.MIte.results, conf.int = TRUE)

set.seed(1234)
optimal.matched.MIte.models <- with(data = optimal.matched.MIte.datasets,
                                    expr = svyglm(formula1, family =quasibinomial))
set.seed(1234)
optimal.matched.MIte.results <- pool(optimal.matched.MIte.models)
summary_MIte_optimal <-summary(optimal.matched.MIte.results, conf.int = TRUE)

set.seed(1234)
one_two.matched.MIte.models <- with(data = one_two.matched.MIte.datasets,
                                    expr = svyglm(formula1, family = quasibinomial))
set.seed(1234)
one_two.matched.MIte.results <- pool(one_two.matched.MIte.models)
summary_MIte_one_two <- summary(one_two.matched.MIte.results, conf.int = TRUE)

set.seed(1234)
full.matched.MIte.models <- with(data = full.matched.MIte.datasets,
                                 expr = svyglm(formula1, family = quasibinomial))
set.seed(1234)
full.matched.MIte.results <- pool(full.matched.MIte.models)
summary_MIte_full <- summary(full.matched.MIte.results, conf.int = TRUE)

set.seed(1234)
subc.MIte.models <- with(data = subc.MIte.datasets,
                         expr = svyglm(formula1, family = quasibinomial))
set.seed(1234)
subc.MIte.results <- pool(subc.MIte.models)
summary_MIte_subc <-summary(subc.MIte.results, conf.int = TRUE)

# IPTW
set.seed(1234)
weighted.MIte.models <- with(data = weighted.MIte.datasets, expr = svyglm(formula1, family = quasibinomial))
set.seed(1234)
weighted.MIte.results <- pool(weighted.MIte.models)
summary_MIte_iptw <-summary(weighted.MIte.results, conf.int = TRUE)

NAFLD.T2D.MIte.HR.est<-c()
NAFLD.T2D.MIte.logHR.est<-c()
NAFLD.T2D.MIte.se<-c()
NAFLD.T2D.MIte.pvalue<-c()
NAFLD.T2D.MIte.lowerCI<-c()
NAFLD.T2D.MIte.upperCI<-c()

NAFLD.T2D.MIte.HR.est[1] <-exp(summary_MIte_greedy[2,2])
NAFLD.T2D.MIte.logHR.est[1]<-summary_MIte_greedy[2,2]
NAFLD.T2D.MIte.se[1]<-summary_MIte_greedy[2,3]
NAFLD.T2D.MIte.pvalue[1]<-summary_MIte_greedy[2,6]
NAFLD.T2D.MIte.lowerCI[1]<- exp(summary_MIte_greedy[2,7])
NAFLD.T2D.MIte.upperCI[1]<- exp(summary_MIte_greedy[2,8])

NAFLD.T2D.MIte.HR.est[2] <-exp(summary_MIte_optimal[2,2])
NAFLD.T2D.MIte.logHR.est[2]<-summary_MIte_optimal[2,2]
NAFLD.T2D.MIte.se[2]<-summary_MIte_optimal[2,3]
NAFLD.T2D.MIte.pvalue[2]<-summary_MIte_optimal[2,6]
NAFLD.T2D.MIte.lowerCI[2]<- exp(summary_MIte_optimal[2,7])
NAFLD.T2D.MIte.upperCI[2]<- exp(summary_MIte_optimal[2,8])

NAFLD.T2D.MIte.HR.est[3] <-exp(summary_MIte_one_two[2,2])
NAFLD.T2D.MIte.logHR.est[3]<-summary_MIte_one_two[2,2]
NAFLD.T2D.MIte.se[3]<-summary_MIte_one_two[2,3]
NAFLD.T2D.MIte.pvalue[3]<-summary_MIte_one_two[2,6]
NAFLD.T2D.MIte.lowerCI[3]<- exp(summary_MIte_one_two[2,7])
NAFLD.T2D.MIte.upperCI[3]<- exp(summary_MIte_one_two[2,8])

NAFLD.T2D.MIte.HR.est[4] <-exp(summary_MIte_full[2,2])
NAFLD.T2D.MIte.logHR.est[4]<-summary_MIte_full[2,2]
NAFLD.T2D.MIte.se[4]<-summary_MIte_full[2,3]
NAFLD.T2D.MIte.pvalue[4]<-summary_MIte_full[2,6]
NAFLD.T2D.MIte.lowerCI[4]<- exp(summary_MIte_full[2,7])
NAFLD.T2D.MIte.upperCI[4]<- exp(summary_MIte_full[2,8])

NAFLD.T2D.MIte.HR.est[5] <-exp(summary_MIte_subc[2,2])
NAFLD.T2D.MIte.logHR.est[5]<-summary_MIte_subc[2,2]
NAFLD.T2D.MIte.se[5]<-summary_MIte_subc[2,3]
NAFLD.T2D.MIte.pvalue[5]<-summary_MIte_subc[2,6]
NAFLD.T2D.MIte.lowerCI[5]<- exp(summary_MIte_subc[2,7])
NAFLD.T2D.MIte.upperCI[5]<- exp(summary_MIte_subc[2,8])

NAFLD.T2D.MIte.HR.est[6] <-exp(summary_MIte_iptw[2,2])
NAFLD.T2D.MIte.logHR.est[6]<-summary_MIte_iptw[2,2]
NAFLD.T2D.MIte.se[6]<-summary_MIte_iptw[2,3]
NAFLD.T2D.MIte.pvalue[6]<-summary_MIte_iptw[2,6]
NAFLD.T2D.MIte.lowerCI[6]<- exp(summary_MIte_iptw[2,7])
NAFLD.T2D.MIte.upperCI[6]<- exp(summary_MIte_iptw[2,8])

NAFLD.T2D.MIte.HR.est[7] <-exp(summary_glm_mi$coefficients[2,1])
NAFLD.T2D.MIte.logHR.est[7]<-summary_glm_mi$coefficients[2,1]
NAFLD.T2D.MIte.se[7]<-summary_glm_mi$coefficients[2,2]
NAFLD.T2D.MIte.pvalue[7]<-summary_glm_mi$coefficients[2,4]
NAFLD.T2D.MIte.lowerCI[7]<- exp(summary_glm_mi$coefficients[2,1]-1.96*summary_glm_mi$coefficients[2,2])
NAFLD.T2D.MIte.upperCI[7]<- exp(summary_glm_mi$coefficients[2,1]+1.96*summary_glm_mi$coefficients[2,2])

NAFLDoutcome.T2D.MIte.result <- 
  structure(list(
    mean  = c(NA, NA, NAFLD.T2D.MIte.HR.est), 
    lower = c(NA, NA, NAFLD.T2D.MIte.lowerCI),
    upper = c(NA, NA, NAFLD.T2D.MIte.upperCI)),
    .Names = c("mean", "lower", "upper"), 
    row.names = c(NA, -8L), 
    class = "data.frame")

A <- cbind2(c("","Method","Greedy Matching","Optimal Matching","1:2 Matching",
              "Full Matching","Stratification with 5 groups", "IPTW","Crude"),
            c("","Effect", as.character(round(NAFLD.T2D.MIte.HR.est,3))))
B<- cbind2(c("","SE", as.character(round(NAFLD.T2D.MIte.se,3))),
           c("","p-value", ifelse(NAFLD.T2D.MIte.pvalue<0.001, "<0.001", round(NAFLD.T2D.MIte.pvalue,3))))
tabletext <- cbind2(A ,B)

forestplot(tabletext, 
           NAFLDoutcome.T2D.MIte.result,new_page = TRUE,
           col = fpColors(box="royalblue",line="darkblue"),
           xlab = "Estimate with 95% CI",
           hrzl_lines= gpar(col = "#444444"),
           is.summary = c(TRUE, TRUE, rep(FALSE, 10)),
           clip = c(0,5.5), zero=1,
           txt_gp=fpTxtGp(label = gpar(cex = 0.8),
                          title = gpar(cex = 1),
                          ticks = gpar(cex = 0.7),
                          xlab = gpar(cex = 0.7)),
           xticks=(c(0.5,1, 1.5)))
grid.text("Exposure of T2D on NAFLD by MIte", .5, 0.98, gp=gpar(fontface="bold"))
```
## MIps
```{r}
################################
############MIps################
################################
set.seed(1234)
## Greedy matching
greedy.matched.MIps.across.datasets <- matchthem(ps.formula, mi.data,
                                                 approach = 'across',
                                                 method = 'nearest',
                                                 caliper = 0.05)
greedy.matched.MIps.across.datasets

set.seed(1234)
## Optimal matching
optimal.matched.MIps.across.datasets <- matchthem(ps.formula, mi.data,
                                                  approach = 'across',
                                                  method = 'optimal',
                                                  caliper = 0.05)
optimal.matched.MIps.across.datasets

set.seed(1234)
## 1:2 matching
one_two.matched.MIps.across.datasets <- matchthem(ps.formula, mi.data,
                                                  approach = 'across',
                                                  method = 'nearest',
                                                  caliper = 0.05, ratio = 2)
one_two.matched.MIps.across.datasets

set.seed(1234)
## Full matching
full.matched.MIps.across.datasets <- matchthem(ps.formula,mi.data,
                                               approach = 'across',
                                               caliper = 0.05,
                                               method = "full")
full.matched.MIps.across.datasets

set.seed(1234)
## Subclassification with full matching
subc.MIps.across.datasets <- matchthem(ps.formula, mi.data,
                                       approach = 'across',
                                       method = "subclass",
                                       subclass = 5)
subc.MIps.across.datasets
plot(subc.MIps.across.datasets, type = "jitter")

set.seed(1234)
# IPTW
weighted.across.datasets <- weightthem(ps.formula, mi.data,
                                       approach = 'across', 
                                       method = 'ps', estimand = 'ATM')
weighted.across.datasets

sum_greedy_MIps_normallasso<-bal.tab(greedy.matched.MIps.across.datasets, abs = TRUE)
sum_optimal_MIps_normallasso<-bal.tab(optimal.matched.MIps.across.datasets, abs = TRUE)
sum_one_two_MIps_normallasso<-bal.tab(one_two.matched.MIps.across.datasets, abs = TRUE)
sum_full_MIps_normallasso<-bal.tab(full.matched.MIps.across.datasets, abs = TRUE)
sum_subc_MIps_normallasso<-bal.tab(subc.MIps.across.datasets, abs = TRUE)
sum_iptw_MIps_normallasso<-bal.tab(weighted.across.datasets, abs = TRUE)

sum_MIps_normallasso<-cbind(sum_iptw_MIps_normallasso$Balance.Across.Imputations[6],sum_optimal_MIps_normallasso$Balance.Across.Imputations[6],sum_one_two_MIps_normallasso$Balance.Across.Imputations[6],sum_full_MIps_normallasso$Balance.Across.Imputations[6],sum_subc_MIps_normallasso$Balance.Across.Imputations[6],sum_iptw_MIps_normallasso$Balance.Across.Imputations[6])
colnames(sum_MIps_normallasso)<-c("Greedy Matching","Optimal Matching","1:2 Matching",
              "Full Matching","Stratification with 5 groups", "IPTW")


formula1<-as.formula((paste("NAFLD_status","~ T2D+ ",paste(newvariables.normal,collapse = "+"))))
set.seed(1234)
greedy.matched.MIps.across.models <- with(data = greedy.matched.MIps.across.datasets,
                                          expr = svyglm(formula1, family = quasibinomial))
greedy.matched.MIps.across.results <- pool(greedy.matched.MIps.across.models)
summary_MIps_greedy <- summary(greedy.matched.MIps.across.results, conf.int = TRUE)

set.seed(1234)
optimal.matched.MIps.across.models <- with(data = optimal.matched.MIps.across.datasets,
                                           expr = svyglm(formula1, family =quasibinomial))
optimal.matched.MIps.across.results <- pool(optimal.matched.MIps.across.models)
summary_MIps_optimal <-summary(optimal.matched.MIps.across.results, conf.int = TRUE)

set.seed(1234)
one_two.matched.MIps.across.models <- with(data = one_two.matched.MIps.across.datasets,
                                           expr = svyglm(formula1, family = quasibinomial))
one_two.matched.MIps.across.results <- pool(one_two.matched.MIps.across.models)
summary_MIps_one_two <- summary(one_two.matched.MIps.across.results, conf.int = TRUE)

set.seed(1234)
full.matched.MIps.across.models <- with(data = full.matched.MIps.across.datasets,
                                        expr = svyglm(formula1, family = quasibinomial))
full.matched.MIps.across.results <- pool(full.matched.MIps.across.models)
summary_MIps_full <- summary(full.matched.MIps.across.results, conf.int = TRUE)

set.seed(1234)
subc.MIps.across.models <- with(data = subc.MIps.across.datasets,
                                expr = svyglm(formula1, family = quasibinomial))
subc.MIps.across.results <- pool(subc.MIps.across.models)
summary_MIps_subc <-summary(subc.MIps.across.results, conf.int = TRUE)

# IPTW
set.seed(1234)
weighted.across.models <- with(data = weighted.across.datasets, expr = svyglm(formula1, family = quasibinomial))
weighted.across.results <- pool(weighted.across.models)
summary_MIps_iptw <-summary(weighted.across.results, conf.int = TRUE)

NAFLD.T2D.MIps.HR.est<-c()
NAFLD.T2D.MIps.logHR.est<-c()
NAFLD.T2D.MIps.se<-c()
NAFLD.T2D.MIps.pvalue<-c()
NAFLD.T2D.MIps.lowerCI<-c()
NAFLD.T2D.MIps.upperCI<-c()

NAFLD.T2D.MIps.HR.est[1] <-exp(summary_MIps_greedy[2,2])
NAFLD.T2D.MIps.logHR.est[1]<-summary_MIps_greedy[2,2]
NAFLD.T2D.MIps.se[1]<-summary_MIps_greedy[2,3]
NAFLD.T2D.MIps.pvalue[1]<-summary_MIps_greedy[2,6]
NAFLD.T2D.MIps.lowerCI[1]<- exp(summary_MIps_greedy[2,7])
NAFLD.T2D.MIps.upperCI[1]<- exp(summary_MIps_greedy[2,8])

NAFLD.T2D.MIps.HR.est[2] <-exp(summary_MIps_optimal[2,2])
NAFLD.T2D.MIps.logHR.est[2]<-summary_MIps_optimal[2,2]
NAFLD.T2D.MIps.se[2]<-summary_MIps_optimal[2,3]
NAFLD.T2D.MIps.pvalue[2]<-summary_MIps_optimal[2,6]
NAFLD.T2D.MIps.lowerCI[2]<- exp(summary_MIps_optimal[2,7])
NAFLD.T2D.MIps.upperCI[2]<- exp(summary_MIps_optimal[2,8])

NAFLD.T2D.MIps.HR.est[3] <-exp(summary_MIps_one_two[2,2])
NAFLD.T2D.MIps.logHR.est[3]<-summary_MIps_one_two[2,2]
NAFLD.T2D.MIps.se[3]<-summary_MIps_one_two[2,3]
NAFLD.T2D.MIps.pvalue[3]<-summary_MIps_one_two[2,6]
NAFLD.T2D.MIps.lowerCI[3]<- exp(summary_MIps_one_two[2,7])
NAFLD.T2D.MIps.upperCI[3]<- exp(summary_MIps_one_two[2,8])

NAFLD.T2D.MIps.HR.est[4] <-exp(summary_MIps_full[2,2])
NAFLD.T2D.MIps.logHR.est[4]<-summary_MIps_full[2,2]
NAFLD.T2D.MIps.se[4]<-summary_MIps_full[2,3]
NAFLD.T2D.MIps.pvalue[4]<-summary_MIps_full[2,6]
NAFLD.T2D.MIps.lowerCI[4]<- exp(summary_MIps_full[2,7])
NAFLD.T2D.MIps.upperCI[4]<- exp(summary_MIps_full[2,8])

NAFLD.T2D.MIps.HR.est[5] <-exp(summary_MIps_subc[2,2])
NAFLD.T2D.MIps.logHR.est[5]<-summary_MIps_subc[2,2]
NAFLD.T2D.MIps.se[5]<-summary_MIps_subc[2,3]
NAFLD.T2D.MIps.pvalue[5]<-summary_MIps_subc[2,6]
NAFLD.T2D.MIps.lowerCI[5]<- exp(summary_MIps_subc[2,7])
NAFLD.T2D.MIps.upperCI[5]<- exp(summary_MIps_subc[2,8])

NAFLD.T2D.MIps.HR.est[6] <-exp(summary_MIps_iptw[2,2])
NAFLD.T2D.MIps.logHR.est[6]<-summary_MIps_iptw[2,2]
NAFLD.T2D.MIps.se[6]<-summary_MIps_iptw[2,3]
NAFLD.T2D.MIps.pvalue[6]<-summary_MIps_iptw[2,6]
NAFLD.T2D.MIps.lowerCI[6]<- exp(summary_MIps_iptw[2,7])
NAFLD.T2D.MIps.upperCI[6]<- exp(summary_MIps_iptw[2,8])

NAFLD.T2D.MIps.HR.est[7] <-exp(summary_glm_mi$coefficients[2,1])
NAFLD.T2D.MIps.logHR.est[7]<-summary_glm_mi$coefficients[2,1]
NAFLD.T2D.MIps.se[7]<-summary_glm_mi$coefficients[2,2]
NAFLD.T2D.MIps.pvalue[7]<-summary_glm_mi$coefficients[2,4]
NAFLD.T2D.MIps.lowerCI[7]<- exp(summary_glm_mi$coefficients[2,1]-1.96*summary_glm_mi$coefficients[2,2])
NAFLD.T2D.MIps.upperCI[7]<- exp(summary_glm_mi$coefficients[2,1]+1.96*summary_glm_mi$coefficients[2,2])

NAFLDoutcome.T2D.MIps.result <- 
  structure(list(
    mean  = c(NA, NA, NAFLD.T2D.MIps.HR.est), 
    lower = c(NA, NA, NAFLD.T2D.MIps.lowerCI),
    upper = c(NA, NA, NAFLD.T2D.MIps.upperCI)),
    .Names = c("mean", "lower", "upper"), 
    row.names = c(NA, -9L), 
    class = "data.frame")


A <- cbind2(c("","Method","Greedy Matching","Optimal Matching","1:2 Matching",
              "Full Matching","Stratification with 5 groups", "IPTW","Crude"),
               c("","Effect", as.character(round(NAFLD.T2D.MIps.HR.est,3))))
B<- cbind2(c("","SE", as.character(round(NAFLD.T2D.MIps.se,3))),
           c("","p-value", ifelse(NAFLD.T2D.MIps.pvalue<0.001, "<0.001", 
                                          round(NAFLD.T2D.MIps.pvalue,3))))
tabletext <- cbind2(A ,B)

forestplot(tabletext, 
           NAFLDoutcome.T2D.MIps.result,new_page = TRUE,
           col = fpColors(box="royalblue",line="darkblue"),
           xlab = "Estimate with 95% CI",
           hrzl_lines= gpar(col = "#444444"),
           is.summary = c(TRUE, TRUE, rep(FALSE, 10)),
           clip = c(0,5.5), zero=1,
           txt_gp=fpTxtGp(label = gpar(cex = 0.8),
                          title = gpar(cex = 1),
                          ticks = gpar(cex = 0.7),
                          xlab = gpar(cex = 0.7)),
           xticks=(c(0.5,1, 1.5)))
grid.text("Exposure of T2D on NAFLD by MIps", .5, 0.98, gp=gpar(fontface="bold"))
```

```{r}
NAFLD.T2D.normal<-data.frame(MLapproach=rep("Normal LASSO",21),MIapproach=c(rep("CCA",7),rep("MIte",7),rep("MIps",7)),
                      PSmethod=c(rep(c("Greedy Matching","Optimal Matching","1:2 Matching",
                                       "Full Matching","Stratification with 5 groups", "IPTW","Crude"),3)),
                      est=c(round(NAFLD.T2D.HR.est,3),round(NAFLD.T2D.MIte.HR.est,3),
                            round(NAFLD.T2D.MIps.HR.est,3)),
                      log.est=c(round(NAFLD.T2D.logHR.est,3),round(NAFLD.T2D.MIte.logHR.est,3),round(NAFLD.T2D.MIps.logHR.est,3)),
                      se=c(round(NAFLD.T2D.se,3),round(NAFLD.T2D.MIte.se,3),round(NAFLD.T2D.MIps.se,3)),
                      pvalue=c(round(NAFLD.T2D.pvalue,3),round(NAFLD.T2D.MIte.pvalue,3),round(NAFLD.T2D.MIps.pvalue,3)),
                      lowerCI=c(round(NAFLD.T2D.lowerCI,3),round(NAFLD.T2D.MIte.lowerCI,3),round(NAFLD.T2D.MIps.lowerCI,3)),
                      upperCI=c(round(NAFLD.T2D.upperCI,3),round(NAFLD.T2D.MIte.upperCI,3),round(NAFLD.T2D.MIps.upperCI,3)))

NAFLD.T2D.greedy<-subset(NAFLD.T2D.normal,PSmethod=="Greedy Matching")
NAFLD.T2D.optimal<-subset(NAFLD.T2D.normal,PSmethod=="Optimal Matching")
NAFLD.T2D.one_two<-subset(NAFLD.T2D.normal,PSmethod=="1:2 Matching")
NAFLD.T2D.full<-subset(NAFLD.T2D.normal,PSmethod=="Full Matching")
NAFLD.T2D.subc<-subset(NAFLD.T2D.normal,PSmethod=="Stratification with 5 groups")
NAFLD.T2D.iptw<-subset(NAFLD.T2D.normal,PSmethod=="IPTW")
NAFLD.T2D.crude<-subset(NAFLD.T2D.normal,PSmethod=="Crude")


Forstplot<-function(method,title){
  
  A <- cbind2(c("","MI Approach","CCA","MIte","MIps"), 
                     c("","Effect", as.character(method$est)))

  B <-cbind2(c("","SE", as.character(method$se)),
                     c("","p-value", ifelse(method$pvalue<0.001, "<0.001", method$pvalue)))
  
  tabletext <- cbind2(A,B)
  NAFLD.T2D.result <- 
    structure(list(
      mean  = c(NA, NA, method$est), 
      lower = c(NA, NA, method$lowerCI),
      upper = c(NA, NA, method$upperCI)),
      .Names = c("mean", "lower", "upper"), 
      row.names = c(NA, -5L), 
      class = "data.frame")
  
  forestplot(tabletext, 
             NAFLD.T2D.result,
             new_page = TRUE,
             xlab = "Estimate with 95% CI",
             col = fpColors(box="royalblue",line="darkblue"),
             hrzl_lines= gpar(col = "#444444"),
             is.summary = c(TRUE, TRUE, rep(FALSE, 18)),
             clip = c(0.5,5.5), zero=1,
             txt_gp=fpTxtGp(label = gpar(cex = 0.8),
                            title = gpar(cex = 1),
                            ticks = gpar(cex = 0.7),
                            xlab = gpar(cex = 0.7)),
             grid = structure(seq(1, 5.5, by=0.5), 
                              gp = gpar(lty = 2, col = "#CCCCFF")),
           xticks=c(0.5,1, 1.5),
             title=title)
}

Forstplot(NAFLD.T2D.greedy,"Exposure of T2D on of Greedy Matching")
Forstplot(NAFLD.T2D.optimal,"Exposure of T2D on of Optimal Matching")
Forstplot(NAFLD.T2D.one_two,"Exposure of T2D on of 1:2 Matching")
Forstplot(NAFLD.T2D.full,"Exposure of T2D on of Full Matching")
Forstplot(NAFLD.T2D.subc,"Exposure of T2D on of Stratification with 5 groups")
Forstplot(NAFLD.T2D.iptw,"Exposure of T2D on of IPTW ")
```

```{r}

A<-c("","PS Method","Greedy Matching","","","","Optimal Matching","","","","1:2 Matching","","","",
                                       "Full Matching","","","","Stratification with 5 groups", "","","","IPTW","","","","Crude","","")
  
B <- cbind2(c("","MI Approach",rep(c("CCA","MIte","MIps"," "),6),"CCA","MIte","MIps"), 
                     c("","Effect", NAFLD.T2D.greedy$est,"",NAFLD.T2D.optimal$est,"",NAFLD.T2D.one_two$est,"",NAFLD.T2D.full$est,"",NAFLD.T2D.subc$est,"",NAFLD.T2D.iptw$est,"",NAFLD.T2D.crude$est))
  
C <-cbind2(c("","SE", as.character(NAFLD.T2D.greedy$se),"",as.character(NAFLD.T2D.optimal$se),"",
               as.character(NAFLD.T2D.one_two$se),"",as.character(NAFLD.T2D.full$se),"",
               as.character(NAFLD.T2D.subc$se),"",as.character(NAFLD.T2D.iptw$se),"",
               as.character(NAFLD.T2D.crude$se)),
             c("","p-value", as.character(ifelse(NAFLD.T2D.greedy$pvalue<0.001, "<0.001",
                                                 round(NAFLD.T2D.greedy$pvalue,3))),"",
               as.character(ifelse(NAFLD.T2D.optimal$pvalue<0.001, "<0.001",
                                   round(NAFLD.T2D.optimal$pvalue,3))),"",
               as.character(ifelse(NAFLD.T2D.one_two$pvalue<0.001, "<0.001", 
                                          round(NAFLD.T2D.one_two$pvalue,3))),
               "",as.character(ifelse(NAFLD.T2D.full$pvalue<0.001, "<0.001", round(NAFLD.T2D.full$pvalue,3))),"",
               as.character(ifelse(NAFLD.T2D.subc$pvalue<0.001, "<0.001", round(NAFLD.T2D.subc$pvalue,3))),"",
               as.character(ifelse(NAFLD.T2D.iptw$pvalue<0.001, "<0.001", round(NAFLD.T2D.iptw$pvalue,3))),"",
               as.character(ifelse(NAFLD.T2D.crude$pvalue<0.001, "<0.001", round(NAFLD.T2D.curde$pvalue,3)))))
                                                                                                                             
D <-cbind2(A,B)
tabletext <- cbind2(D,C)
NAFLD.T2D.result <- 
    structure(list(
      mean  = c(NA, NA, NAFLD.T2D.greedy$est,NA,NAFLD.T2D.optimal$est,NA,NAFLD.T2D.one_two$est,NA,NAFLD.T2D.full$est,NA,NAFLD.T2D.subc$est,NA,NAFLD.T2D.iptw$est,NA,NAFLD.T2D.crude$est), 
      lower = c(NA, NA, NAFLD.T2D.greedy$lowerCI,NA,NAFLD.T2D.optimal$lowerCI,NA,NAFLD.T2D.one_two$lowerCI,NA,NAFLD.T2D.full$lowerCI,NA,NAFLD.T2D.subc$lowerCI,NA,NAFLD.T2D.iptw$lowerCI,NA,NAFLD.T2D.crude$lowerCI),
      upper = c(NA, NA, NAFLD.T2D.greedy$upperCI,NA,NAFLD.T2D.optimal$upperCI,NA,NAFLD.T2D.one_two$upperCI,NA,NAFLD.T2D.full$upperCI,NA,NAFLD.T2D.subc$upperCI,NA,NAFLD.T2D.iptw$upperCI,NA,NAFLD.T2D.crude$upperCI)),
      .Names = c("mean", "lower", "upper"), 
      row.names = c(NA, -29L), 
      class = "data.frame")

forestplot(tabletext, 
             NAFLD.T2D.result,
             new_page = TRUE,
             col = fpColors(box="royalblue",line="darkblue"),
             hrzl_lines= gpar(col = "#444444"),
             is.summary = c(TRUE, TRUE, rep(FALSE, 29)),
             clip = c(0.5,2.5), zero=1,
             txt_gp=fpTxtGp(label = gpar(cex = 0.8),
                            title = gpar(cex = 1),
                            ticks = gpar(cex = 0.7),
                            xlab = gpar(cex = 0.7)),
             grid = structure(seq(0, 1, by=0.5), 
                              gp = gpar(lty = 0.5, col = "#CCCCFF")),
           xticks=(c(0.5,1, 1.5)),
           xlab = "Estimate with 95% CI",
           title="Forest Plot of Normal LASSO")

```

# Bootstrap LASSO

```{r}
###############################
####### Bootstrap LASSO #######
###############################
newvariables.bootstrap<-c("Glycated_haemoglobin__HbA1c_", "Waist_circumference")
ps.formula <- as.formula((paste("T2D ~",paste(newvariables.bootstrap,collapse = "+"))))
set.seed(1234)
param<-matchit(ps.formula,data = omitNAFLD)
omitNAFLD$param_ps<-param$distance
ggplot(data = omitNAFLD,aes(param_ps,fill=factor(T2D)))+
  geom_histogram(binwidth = 0.005,alpha = 0.5,position="identity")
logitPS<-sd(-log(1/omitNAFLD$param_ps-1))
```
## CCA
```{r}
################################
############# CCA ##############
################################
set.seed(1234)
## Greedy matching
greedy<-matchit(ps.formula,data=omitNAFLD,
                distance="logit",
                caliper=0.1*sd(logitPS),
                method="nearest")
greedy

set.seed(1234)
## Optimal matching
optimal <- matchit(ps.formula,data= omitNAFLD,
                   distance="logit",
                   method = "optimal")
optimal

set.seed(1234)
## 1:2 matching
one_two <- matchit(ps.formula,data=omitNAFLD,
                   distance="logit",
                   caliper=0.1*sd(logitPS),
                   method = "nearest", ratio = 2)
one_two

set.seed(1234)
## Full matching
full <- matchit(ps.formula,data=omitNAFLD,
                distance="logit",
                caliper=0.1*sd(logitPS),
                method = "full")
full

set.seed(1234)
## Subclassification
omitNAFLD <- omitNAFLD %>% mutate(subclass = ntile(param_ps, 5))
set.seed(1234)
## Subclassification with full matching
subc <- matchit(ps.formula, data = omitNAFLD,
                method = "subclass",
                subclass = 5)
subc

plot(subc, type = "jitter")

### Weighting
set.seed(1234)
## IPTW with stabilization
omitNAFLD$iptw<- ifelse(omitNAFLD$T2D == 1, (mean(omitNAFLD$param_ps))/omitNAFLD$param_ps, 
                        (mean(1-omitNAFLD$param_ps))/(1-omitNAFLD$param_ps))
iptw <- dx.wts(omitNAFLD$iptw, data = as.data.frame(omitNAFLD),  treat.var="T2D", 
               estimand = "ATE")
# NAFLD_status~T2D
formula1<-as.formula((paste("NAFLD_status","~ T2D+ ",paste(newvariables.bootstrap,collapse = "+"))))

set.seed(1234)
## Greedy matching
matched_greedy <- match.data(greedy,subclass = "block")
glm_NAFLD_greedy <- glm(formula1,
                        data = matched_greedy,
                        family = binomial)
summary_greedy <- summary(glm_NAFLD_greedy)
exp(coef(glm_NAFLD_greedy))

set.seed(1234)
## Optimal matching
matched_optimal <- match.data(optimal,subclass = "block")
glm_NAFLD_optimal <- glm(formula1,
                         data = matched_optimal,
                         family = binomial)
summary_optimal <- summary(glm_NAFLD_optimal)
exp(coef(glm_NAFLD_optimal))

set.seed(1234)
## 1:2 matching
matched_one_two <- match.data(one_two,subclass = "block")
glm_NAFLD_one_two <- glm(formula1, 
                         data = matched_one_two,
                         family = binomial)
summary_one_two <- summary(glm_NAFLD_one_two)
exp(coef(glm_NAFLD_one_two))

set.seed(1234)
## Full matching
matched_full <- match.data(full,subclass = "block")
glm_NAFLD_full <- glm(formula1,
                      data = matched_full,
                      family = binomial, weights = weights)
summary_full <-summary(glm_NAFLD_full)
exp(coef(glm_NAFLD_full))

set.seed(1234)
## Subclassification with full matching
subced <- match.data(subc,subclass = "block")
design <- svydesign(id = ~1, strata = ~subclass, weights = ~weights, nested = TRUE, data = subced)
svyglm_NAFLD_subc <- svyglm(formula1, design = design, family = binomial)
summary_subc <- summary(svyglm_NAFLD_subc)
exp(coef(svyglm_NAFLD_subc))

set.seed(1234)
## Weighting by IPTW with stabilization
glm_NAFLD_iptw <- glm(formula1,
                      data = omitNAFLD,
                      weights = iptw,
                      family = binomial)
summary_iptw <-summary(glm_NAFLD_iptw)
exp(coef(glm_NAFLD_iptw))

NAFLD.T2D.HR.est<-c()
NAFLD.T2D.logHR.est<-c()
NAFLD.T2D.se<-c()
NAFLD.T2D.pvalue<-c()
NAFLD.T2D.lowerCI<-c()
NAFLD.T2D.upperCI<-c()

NAFLD.T2D.HR.est[1] <-exp(summary_greedy$coefficients[2,1])
NAFLD.T2D.logHR.est[1]<-summary_greedy$coefficients[2,1]
NAFLD.T2D.se[1]<-summary_greedy$coefficients[2,2]
NAFLD.T2D.pvalue[1]<-summary_greedy$coefficients[2,4]
NAFLD.T2D.lowerCI[1]<- exp(summary_greedy$coefficients[2,1]-1.96*summary_greedy$coefficients[2,2])
NAFLD.T2D.upperCI[1]<- exp(summary_greedy$coefficients[2,1]+1.96*summary_greedy$coefficients[2,2])

NAFLD.T2D.HR.est[2] <-exp(summary_optimal$coefficients[2,1])
NAFLD.T2D.logHR.est[2]<-summary_optimal$coefficients[2,1]
NAFLD.T2D.se[2]<-summary_optimal$coefficients[2,2]
NAFLD.T2D.pvalue[2]<-summary_optimal$coefficients[2,4]
NAFLD.T2D.lowerCI[2]<- exp(summary_optimal$coefficients[2,1]-1.96*summary_optimal$coefficients[2,2])
NAFLD.T2D.upperCI[2]<- exp(summary_optimal$coefficients[2,1]+1.96*summary_optimal$coefficients[2,2])

NAFLD.T2D.HR.est[3] <-exp(summary_one_two$coefficients[2,1])
NAFLD.T2D.logHR.est[3]<-summary_one_two$coefficients[2,1]
NAFLD.T2D.se[3]<-summary_one_two$coefficients[2,2]
NAFLD.T2D.pvalue[3]<-summary_one_two$coefficients[2,4]
NAFLD.T2D.lowerCI[3]<- exp(summary_one_two$coefficients[2,1]-1.96*summary_one_two$coefficients[2,2])
NAFLD.T2D.upperCI[3]<- exp(summary_one_two$coefficients[2,1]+1.96*summary_one_two$coefficients[2,2])

NAFLD.T2D.HR.est[4] <-exp(summary_full$coefficients[2,1])
NAFLD.T2D.logHR.est[4]<-summary_full$coefficients[2,1]
NAFLD.T2D.se[4]<-summary_full$coefficients[2,2]
NAFLD.T2D.pvalue[4]<-summary_full$coefficients[2,4]
NAFLD.T2D.lowerCI[4]<- exp(summary_full$coefficients[2,1]-1.96*summary_full$coefficients[2,2])
NAFLD.T2D.upperCI[4]<- exp(summary_full$coefficients[2,1]+1.96*summary_full$coefficients[2,2])

NAFLD.T2D.HR.est[5] <-exp(summary_subc$coefficients[2,1])
NAFLD.T2D.logHR.est[5]<-summary_subc$coefficients[2,1]
NAFLD.T2D.se[5]<-summary_subc$coefficients[2,2]
NAFLD.T2D.pvalue[5]<-summary_subc$coefficients[2,4]
NAFLD.T2D.lowerCI[5]<- exp(summary_subc$coefficients[2,1]-1.96*summary_subc$coefficients[2,2])
NAFLD.T2D.upperCI[5]<- exp(summary_subc$coefficients[2,1]+1.96*summary_subc$coefficients[2,2])

NAFLD.T2D.HR.est[6] <-exp(summary_iptw$coefficients[2,1])
NAFLD.T2D.logHR.est[6]<-summary_iptw$coefficients[2,1]
NAFLD.T2D.se[6]<-summary_iptw$coefficients[2,2]
NAFLD.T2D.pvalue[6]<-summary_iptw$coefficients[2,4]
NAFLD.T2D.lowerCI[6]<- exp(summary_iptw$coefficients[2,1]-1.96*summary_iptw$coefficients[2,2])
NAFLD.T2D.upperCI[6]<- exp(summary_iptw$coefficients[2,1]+1.96*summary_iptw$coefficients[2,2])

NAFLD.T2D.HR.est[7] <-exp(summary_glm$coefficients[2,1])
NAFLD.T2D.logHR.est[7]<-summary_glm$coefficients[2,1]
NAFLD.T2D.se[7]<-summary_glm$coefficients[2,2]
NAFLD.T2D.pvalue[7]<-summary_glm$coefficients[2,4]
NAFLD.T2D.lowerCI[7]<- exp(summary_glm$coefficients[2,1]-1.96*summary_glm$coefficients[2,2])
NAFLD.T2D.upperCI[7]<- exp(summary_glm$coefficients[2,1]+1.96*summary_glm$coefficients[2,2])

NAFLDoutcome.T2D.result <- 
  structure(list(
    mean  = c(NA, NA, NAFLD.T2D.HR.est), 
    lower = c(NA, NA, NAFLD.T2D.lowerCI),
    upper = c(NA, NA, NAFLD.T2D.upperCI)),
    .Names = c("mean", "lower", "upper"), 
    row.names = c(NA, -8L), 
    class = "data.frame")

A <- cbind2(c("","Method","Greedy Matching","Optimal Matching","1:2 Matching",
              "Full Matching","Stratification with 5 groups", "IPTW","Crude"),
                 c("","Effect", as.character(round(NAFLD.T2D.HR.est,3))))
B<- cbind2(c("","SE", as.character(round(NAFLD.T2D.se,3))),
           c("","p-value", ifelse(NAFLD.T2D.pvalue<0.001, "<0.001", round(NAFLD.T2D.pvalue,3))))
tabletext <- cbind2(A ,B)

forestplot(tabletext, 
           NAFLDoutcome.T2D.result,new_page = TRUE,
           col = fpColors(box="royalblue",line="darkblue"),
           xlab = "Estimate with 95% CI",
           hrzl_lines= gpar(col = "#444444"),
           is.summary = c(TRUE, TRUE, rep(FALSE, 10)),
           clip = c(0.5,5.5), zero=0.5,
           txt_gp=fpTxtGp(label = gpar(cex = 0.8),
                          title = gpar(cex = 1),
                          ticks = gpar(cex = 0.7),
                          xlab = gpar(cex = 0.7)),
           grid = structure(seq(0.5, 5.5, by=0.25), 
                            gp = gpar(lty = 2, col = "#CCCCFF")),
           xticks=c(0.5,1, 1.5))
grid.text("Exposure of T2D on NAFLD", .5, 0.98, gp=gpar(fontface="bold"))
```
## MIte
```{r}
################################
############# MI ###############
################################



################################
############MIte################
################################
set.seed(1234)
## Greedy matching
greedy.matched.MIte.datasets <- matchthem(ps.formula, mi.data,
                                          approach = 'within',
                                          method = 'nearest',
                                          caliper = 0.05)
greedy.matched.MIte.datasets

set.seed(1234)
## Optimal matching
optimal.matched.MIte.datasets <- matchthem(ps.formula, mi.data,
                                           approach = 'within',
                                           method = 'optimal',
                                           caliper = 0.05)
optimal.matched.MIte.datasets

set.seed(1234)
## 1:2 matching
one_two.matched.MIte.datasets <- matchthem(ps.formula, mi.data,
                                           approach = 'within',
                                           method = 'nearest',
                                           caliper = 0.05, ratio = 2)
one_two.matched.MIte.datasets 

set.seed(1234)
## Full matching
full.matched.MIte.datasets <- matchthem(ps.formula,mi.data,
                                        approach = 'within',
                                        caliper = 0.05,
                                        method = "full")
full.matched.MIte.datasets

set.seed(1234)
## Subclassification with full matching
subc.MIte.datasets <- matchthem(ps.formula, mi.data,
                                approach = 'within',
                                method = "subclass",
                                subclass = 5)
subc.MIte.datasets
plot(subc.MIte.datasets, type = "jitter")

set.seed(1234)
# IPTW
weighted.MIte.datasets <- weightthem(ps.formula, mi.data,
                                     approach = 'within', 
                                     method = 'ps', estimand = 'ATM')
weighted.MIte.datasets

library(cobalt)
bal.tab(greedy.matched.MIte.datasets, abs = TRUE)
bal.tab(optimal.matched.MIte.datasets, abs = TRUE)
bal.tab(one_two.matched.MIte.datasets, abs = TRUE)
bal.tab(full.matched.MIte.datasets, abs = TRUE)
bal.tab(subc.MIte.datasets, abs = TRUE)
bal.tab(weighted.MIte.datasets, abs = TRUE)

library(survey)
formula1<-as.formula((paste("NAFLD_status","~ T2D+ ",paste(newvariables.bootstrap,collapse = "+"))))
set.seed(1234)
greedy.matched.MIte.models <- with(data = greedy.matched.MIte.datasets,
                                   expr = svyglm(formula1, family = quasibinomial))
greedy.matched.MIte.results <- pool(greedy.matched.MIte.models)
summary_MIte_greedy <- summary(greedy.matched.MIte.results, conf.int = TRUE)
set.seed(1234)
optimal.matched.MIte.models <- with(data = optimal.matched.MIte.datasets,
                                    expr = svyglm(formula1, family =quasibinomial))
optimal.matched.MIte.results <- pool(optimal.matched.MIte.models)
summary_MIte_optimal <-summary(optimal.matched.MIte.results, conf.int = TRUE)
set.seed(1234)
one_two.matched.MIte.models <- with(data = one_two.matched.MIte.datasets,
                                    expr = svyglm(formula1, family = quasibinomial))
one_two.matched.MIte.results <- pool(one_two.matched.MIte.models)
summary_MIte_one_two <- summary(one_two.matched.MIte.results, conf.int = TRUE)
set.seed(1234)
full.matched.MIte.models <- with(data = full.matched.MIte.datasets,
                                 expr = svyglm(formula1, family = quasibinomial))
full.matched.MIte.results <- pool(full.matched.MIte.models)
summary_MIte_full <- summary(full.matched.MIte.results, conf.int = TRUE)

set.seed(1234)
subc.MIte.models <- with(data = subc.MIte.datasets,
                         expr = svyglm(formula1, family = quasibinomial))
subc.MIte.results <- pool(subc.MIte.models)
summary_MIte_subc <-summary(subc.MIte.results, conf.int = TRUE)
set.seed(1234)
# IPTW
weighted.MIte.models <- with(data = weighted.MIte.datasets, expr = svyglm(formula1, family = quasibinomial))
weighted.MIte.results <- pool(weighted.MIte.models)
summary_MIte_iptw <-summary(weighted.MIte.results, conf.int = TRUE)

NAFLD.T2D.MIte.HR.est<-c()
NAFLD.T2D.MIte.logHR.est<-c()
NAFLD.T2D.MIte.se<-c()
NAFLD.T2D.MIte.pvalue<-c()
NAFLD.T2D.MIte.lowerCI<-c()
NAFLD.T2D.MIte.upperCI<-c()

NAFLD.T2D.MIte.HR.est[1] <-exp(summary_MIte_greedy[2,2])
NAFLD.T2D.MIte.logHR.est[1]<-summary_MIte_greedy[2,2]
NAFLD.T2D.MIte.se[1]<-summary_MIte_greedy[2,3]
NAFLD.T2D.MIte.pvalue[1]<-summary_MIte_greedy[2,6]
NAFLD.T2D.MIte.lowerCI[1]<- exp(summary_MIte_greedy[2,7])
NAFLD.T2D.MIte.upperCI[1]<- exp(summary_MIte_greedy[2,8])

NAFLD.T2D.MIte.HR.est[2] <-exp(summary_MIte_optimal[2,2])
NAFLD.T2D.MIte.logHR.est[2]<-summary_MIte_optimal[2,2]
NAFLD.T2D.MIte.se[2]<-summary_MIte_optimal[2,3]
NAFLD.T2D.MIte.pvalue[2]<-summary_MIte_optimal[2,6]
NAFLD.T2D.MIte.lowerCI[2]<- exp(summary_MIte_optimal[2,7])
NAFLD.T2D.MIte.upperCI[2]<- exp(summary_MIte_optimal[2,8])

NAFLD.T2D.MIte.HR.est[3] <-exp(summary_MIte_one_two[2,2])
NAFLD.T2D.MIte.logHR.est[3]<-summary_MIte_one_two[2,2]
NAFLD.T2D.MIte.se[3]<-summary_MIte_one_two[2,3]
NAFLD.T2D.MIte.pvalue[3]<-summary_MIte_one_two[2,6]
NAFLD.T2D.MIte.lowerCI[3]<- exp(summary_MIte_one_two[2,7])
NAFLD.T2D.MIte.upperCI[3]<- exp(summary_MIte_one_two[2,8])

NAFLD.T2D.MIte.HR.est[4] <-exp(summary_MIte_full[2,2])
NAFLD.T2D.MIte.logHR.est[4]<-summary_MIte_full[2,2]
NAFLD.T2D.MIte.se[4]<-summary_MIte_full[2,3]
NAFLD.T2D.MIte.pvalue[4]<-summary_MIte_full[2,6]
NAFLD.T2D.MIte.lowerCI[4]<- exp(summary_MIte_full[2,7])
NAFLD.T2D.MIte.upperCI[4]<- exp(summary_MIte_full[2,8])

NAFLD.T2D.MIte.HR.est[5] <-exp(summary_MIte_subc[2,2])
NAFLD.T2D.MIte.logHR.est[5]<-summary_MIte_subc[2,2]
NAFLD.T2D.MIte.se[5]<-summary_MIte_subc[2,3]
NAFLD.T2D.MIte.pvalue[5]<-summary_MIte_subc[2,6]
NAFLD.T2D.MIte.lowerCI[5]<- exp(summary_MIte_subc[2,7])
NAFLD.T2D.MIte.upperCI[5]<- exp(summary_MIte_subc[2,8])

NAFLD.T2D.MIte.HR.est[6] <-exp(summary_MIte_iptw[2,2])
NAFLD.T2D.MIte.logHR.est[6]<-summary_MIte_iptw[2,2]
NAFLD.T2D.MIte.se[6]<-summary_MIte_iptw[2,3]
NAFLD.T2D.MIte.pvalue[6]<-summary_MIte_iptw[2,6]
NAFLD.T2D.MIte.lowerCI[6]<- exp(summary_MIte_iptw[2,7])
NAFLD.T2D.MIte.upperCI[6]<- exp(summary_MIte_iptw[2,8])

NAFLD.T2D.MIte.HR.est[7] <-exp(summary_glm_mi$coefficients[2,1])
NAFLD.T2D.MIte.logHR.est[7]<-summary_glm_mi$coefficients[2,1]
NAFLD.T2D.MIte.se[7]<-summary_glm_mi$coefficients[2,2]
NAFLD.T2D.MIte.pvalue[7]<-summary_glm_mi$coefficients[2,4]
NAFLD.T2D.MIte.lowerCI[7]<- exp(summary_glm_mi$coefficients[2,1]-1.96*summary_glm_mi$coefficients[2,2])
NAFLD.T2D.MIte.upperCI[7]<- exp(summary_glm_mi$coefficients[2,1]+1.96*summary_glm_mi$coefficients[2,2])

NAFLDoutcome.T2D.MIte.result <- 
  structure(list(
    mean  = c(NA, NA, NAFLD.T2D.MIte.HR.est), 
    lower = c(NA, NA, NAFLD.T2D.MIte.lowerCI),
    upper = c(NA, NA, NAFLD.T2D.MIte.upperCI)),
    .Names = c("mean", "lower", "upper"), 
    row.names = c(NA, -8L), 
    class = "data.frame")

A <- cbind2(c("","Method","Greedy Matching","Optimal Matching","1:2 Matching",
              "Full Matching","Stratification with 5 groups", "IPTW","Crude"),
            c("","Effect", as.character(round(NAFLD.T2D.MIte.HR.est,3))))
B<- cbind2(c("","SE", as.character(round(NAFLD.T2D.MIte.se,3))),
           c("","p-value", ifelse(NAFLD.T2D.MIte.pvalue<0.001, "<0.001", round(NAFLD.T2D.MIte.pvalue,3))))
tabletext <- cbind2(A ,B)

forestplot(tabletext, 
           NAFLDoutcome.T2D.MIte.result,new_page = TRUE,
           col = fpColors(box="royalblue",line="darkblue"),
           xlab = "Estimate with 95% CI",
           hrzl_lines= gpar(col = "#444444"),
           is.summary = c(TRUE, TRUE, rep(FALSE, 10)),
           clip = c(0,5.5), zero=1,
           txt_gp=fpTxtGp(label = gpar(cex = 0.8),
                          title = gpar(cex = 1),
                          ticks = gpar(cex = 0.7),
                          xlab = gpar(cex = 0.7)),
           grid = structure(seq(1,5, by=0.25), 
                            gp = gpar(lty = 2, col = "#CCCCFF")),
           xticks=c(0.5,1, 1.5))
grid.text("Exposure of T2D on NAFLD by MIte", .5, 0.98, gp=gpar(fontface="bold"))
```
## MIps
```{r}
################################
############MIps################
################################
set.seed(1234)
## Greedy matching
greedy.matched.MIps.across.datasets <- matchthem(ps.formula, mi.data,
                                                 approach = 'across',
                                                 method = 'nearest',
                                                 caliper = 0.05)
greedy.matched.MIps.across.datasets

set.seed(1234)
## Optimal matching
optimal.matched.MIps.across.datasets <- matchthem(ps.formula, mi.data,
                                                  approach = 'across',
                                                  method = 'optimal',
                                                  caliper = 0.05)
optimal.matched.MIps.across.datasets

set.seed(1234)
## 1:2 matching
one_two.matched.MIps.across.datasets <- matchthem(ps.formula, mi.data,
                                                  approach = 'across',
                                                  method = 'nearest',
                                                  caliper = 0.05, ratio = 2)
one_two.matched.MIps.across.datasets

set.seed(1234)
## Full matching
full.matched.MIps.across.datasets <- matchthem(ps.formula,mi.data,
                                               approach = 'across',
                                               caliper = 0.05,
                                               method = "full")
full.matched.MIps.across.datasets

set.seed(1234)
## Subclassification with full matching
subc.MIps.across.datasets <- matchthem(ps.formula, mi.data,
                                       approach = 'across',
                                       method = "subclass",
                                       subclass = 5)
subc.MIps.across.datasets
plot(subc.MIps.across.datasets, type = "jitter")

set.seed(1234)
# IPTW
weighted.across.datasets <- weightthem(ps.formula, mi.data,
                                       approach = 'across', 
                                       method = 'ps', estimand = 'ATM')
weighted.across.datasets

bal.tab(greedy.matched.MIps.across.datasets, abs = TRUE)
bal.tab(optimal.matched.MIps.across.datasets, abs = TRUE)
bal.tab(one_two.matched.MIps.across.datasets, abs = TRUE)
bal.tab(full.matched.MIps.across.datasets, abs = TRUE)
bal.tab(subc.MIps.across.datasets, abs = TRUE)
bal.tab(weighted.across.datasets, abs = TRUE)

formula1<-as.formula((paste("NAFLD_status","~ T2D+ ",paste(newvariables.bootstrap,collapse = "+"))))
set.seed(1234)
greedy.matched.MIps.across.models <- with(data = greedy.matched.MIps.across.datasets,
                                          expr = svyglm(formula1, family = quasibinomial))
greedy.matched.MIps.across.results <- pool(greedy.matched.MIps.across.models)
summary_MIps_greedy <- summary(greedy.matched.MIps.across.results, conf.int = TRUE)

set.seed(1234)
optimal.matched.MIps.across.models <- with(data = optimal.matched.MIps.across.datasets,
                                           expr = svyglm(formula1, family =quasibinomial))
optimal.matched.MIps.across.results <- pool(optimal.matched.MIps.across.models)
summary_MIps_optimal <-summary(optimal.matched.MIps.across.results, conf.int = TRUE)

set.seed(1234)
one_two.matched.MIps.across.models <- with(data = one_two.matched.MIps.across.datasets,
                                           expr = svyglm(formula1, family = quasibinomial))
one_two.matched.MIps.across.results <- pool(one_two.matched.MIps.across.models)
summary_MIps_one_two <- summary(one_two.matched.MIps.across.results, conf.int = TRUE)

set.seed(1234)
full.matched.MIps.across.models <- with(data = full.matched.MIps.across.datasets,
                                        expr = svyglm(formula1, family = quasibinomial))
full.matched.MIps.across.results <- pool(full.matched.MIps.across.models)
summary_MIps_full <- summary(full.matched.MIps.across.results, conf.int = TRUE)

set.seed(1234)
subc.MIps.across.models <- with(data = subc.MIps.across.datasets,
                                expr = svyglm(formula1, family = quasibinomial))
subc.MIps.across.results <- pool(subc.MIps.across.models)
summary_MIps_subc <-summary(subc.MIps.across.results, conf.int = TRUE)

# IPTW
set.seed(1234)
weighted.across.models <- with(data = weighted.across.datasets, expr = svyglm(formula1, family = quasibinomial))
weighted.across.results <- pool(weighted.across.models)
summary_MIps_iptw <-summary(weighted.across.results, conf.int = TRUE)

NAFLD.T2D.MIps.HR.est<-c()
NAFLD.T2D.MIps.logHR.est<-c()
NAFLD.T2D.MIps.se<-c()
NAFLD.T2D.MIps.pvalue<-c()
NAFLD.T2D.MIps.lowerCI<-c()
NAFLD.T2D.MIps.upperCI<-c()

NAFLD.T2D.MIps.HR.est[1] <-exp(summary_MIps_greedy[2,2])
NAFLD.T2D.MIps.logHR.est[1]<-summary_MIps_greedy[2,2]
NAFLD.T2D.MIps.se[1]<-summary_MIps_greedy[2,3]
NAFLD.T2D.MIps.pvalue[1]<-summary_MIps_greedy[2,6]
NAFLD.T2D.MIps.lowerCI[1]<- exp(summary_MIps_greedy[2,7])
NAFLD.T2D.MIps.upperCI[1]<- exp(summary_MIps_greedy[2,8])

NAFLD.T2D.MIps.HR.est[2] <-exp(summary_MIps_optimal[2,2])
NAFLD.T2D.MIps.logHR.est[2]<-summary_MIps_optimal[2,2]
NAFLD.T2D.MIps.se[2]<-summary_MIps_optimal[2,3]
NAFLD.T2D.MIps.pvalue[2]<-summary_MIps_optimal[2,6]
NAFLD.T2D.MIps.lowerCI[2]<- exp(summary_MIps_optimal[2,7])
NAFLD.T2D.MIps.upperCI[2]<- exp(summary_MIps_optimal[2,8])

NAFLD.T2D.MIps.HR.est[3] <-exp(summary_MIps_one_two[2,2])
NAFLD.T2D.MIps.logHR.est[3]<-summary_MIps_one_two[2,2]
NAFLD.T2D.MIps.se[3]<-summary_MIps_one_two[2,3]
NAFLD.T2D.MIps.pvalue[3]<-summary_MIps_one_two[2,6]
NAFLD.T2D.MIps.lowerCI[3]<- exp(summary_MIps_one_two[2,7])
NAFLD.T2D.MIps.upperCI[3]<- exp(summary_MIps_one_two[2,8])

NAFLD.T2D.MIps.HR.est[4] <-exp(summary_MIps_full[2,2])
NAFLD.T2D.MIps.logHR.est[4]<-summary_MIps_full[2,2]
NAFLD.T2D.MIps.se[4]<-summary_MIps_full[2,3]
NAFLD.T2D.MIps.pvalue[4]<-summary_MIps_full[2,6]
NAFLD.T2D.MIps.lowerCI[4]<- exp(summary_MIps_full[2,7])
NAFLD.T2D.MIps.upperCI[4]<- exp(summary_MIps_full[2,8])

NAFLD.T2D.MIps.HR.est[5] <-exp(summary_MIps_subc[2,2])
NAFLD.T2D.MIps.logHR.est[5]<-summary_MIps_subc[2,2]
NAFLD.T2D.MIps.se[5]<-summary_MIps_subc[2,3]
NAFLD.T2D.MIps.pvalue[5]<-summary_MIps_subc[2,6]
NAFLD.T2D.MIps.lowerCI[5]<- exp(summary_MIps_subc[2,7])
NAFLD.T2D.MIps.upperCI[5]<- exp(summary_MIps_subc[2,8])

NAFLD.T2D.MIps.HR.est[6] <-exp(summary_MIps_iptw[2,2])
NAFLD.T2D.MIps.logHR.est[6]<-summary_MIps_iptw[2,2]
NAFLD.T2D.MIps.se[6]<-summary_MIps_iptw[2,3]
NAFLD.T2D.MIps.pvalue[6]<-summary_MIps_iptw[2,6]
NAFLD.T2D.MIps.lowerCI[6]<- exp(summary_MIps_iptw[2,7])
NAFLD.T2D.MIps.upperCI[6]<- exp(summary_MIps_iptw[2,8])

NAFLD.T2D.MIps.HR.est[7] <-exp(summary_glm_mi$coefficients[2,1])
NAFLD.T2D.MIps.logHR.est[7]<-summary_glm_mi$coefficients[2,1]
NAFLD.T2D.MIps.se[7]<-summary_glm_mi$coefficients[2,2]
NAFLD.T2D.MIps.pvalue[7]<-summary_glm_mi$coefficients[2,4]
NAFLD.T2D.MIps.lowerCI[7]<- exp(summary_glm_mi$coefficients[2,1]-1.96*summary_glm_mi$coefficients[2,2])
NAFLD.T2D.MIps.upperCI[7]<- exp(summary_glm_mi$coefficients[2,1]+1.96*summary_glm_mi$coefficients[2,2])

NAFLDoutcome.T2D.MIps.result <- 
  structure(list(
    mean  = c(NA, NA, NAFLD.T2D.MIps.HR.est), 
    lower = c(NA, NA, NAFLD.T2D.MIps.lowerCI),
    upper = c(NA, NA, NAFLD.T2D.MIps.upperCI)),
    .Names = c("mean", "lower", "upper"), 
    row.names = c(NA, -9L), 
    class = "data.frame")


A <- cbind2(c("","Method","Greedy Matching","Optimal Matching","1:2 Matching",
              "Full Matching","Stratification with 5 groups", "IPTW","Crude"),
               c("","Effect", as.character(round(NAFLD.T2D.MIps.HR.est,3))))
B<- cbind2(c("","SE", as.character(round(NAFLD.T2D.MIps.se,3))),
           c("","p-value", ifelse(NAFLD.T2D.MIps.pvalue<0.001, "<0.001", 
                                          round(NAFLD.T2D.MIps.pvalue,3))))
tabletext <- cbind2(A ,B)

forestplot(tabletext, 
           NAFLDoutcome.T2D.MIps.result,new_page = TRUE,
           col = fpColors(box="royalblue",line="darkblue"),
           xlab = "Estimate with 95% CI",
           hrzl_lines= gpar(col = "#444444"),
           is.summary = c(TRUE, TRUE, rep(FALSE, 10)),
           clip = c(0.5,5.5), zero=1,
           txt_gp=fpTxtGp(label = gpar(cex = 0.8),
                          title = gpar(cex = 1),
                          ticks = gpar(cex = 0.8),
                          xlab = gpar(cex = 0.7)),
           grid = structure(seq(1, 5.5, by=0.25), 
                            gp = gpar(lty = 2, col = "#CCCCFF")),
           xticks=c(0.5,1, 1.5))
grid.text("Exposure of T2D on NAFLD by MIps", .5, 0.98, gp=gpar(fontface="bold"))
```

```{r}
NAFLD.T2D.bootsrap<-data.frame(MLapproach=rep("Bootstrap LASSO",21),MIapproach=c(rep("CCA",7),rep("MIte",7),rep("MIps",7)),
                      PSmethod=c(rep(c("Greedy Matching","Optimal Matching","1:2 Matching",
                                       "Full Matching","Stratification with 5 groups", "IPTW","Crude"),3)),
                      est=c(round(NAFLD.T2D.HR.est,3),round(NAFLD.T2D.MIte.HR.est,3),
                            round(NAFLD.T2D.MIps.HR.est,3)),
                      log.est=c(round(NAFLD.T2D.logHR.est,3),round(NAFLD.T2D.MIte.logHR.est,3),round(NAFLD.T2D.MIps.logHR.est,3)),
                      se=c(round(NAFLD.T2D.se,3),round(NAFLD.T2D.MIte.se,3),round(NAFLD.T2D.MIps.se,3)),
                      pvalue=c(round(NAFLD.T2D.pvalue,3),round(NAFLD.T2D.MIte.pvalue,3),round(NAFLD.T2D.MIps.pvalue,3)),
                      lowerCI=c(round(NAFLD.T2D.lowerCI,3),round(NAFLD.T2D.MIte.lowerCI,3),round(NAFLD.T2D.MIps.lowerCI,3)),
                      upperCI=c(round(NAFLD.T2D.upperCI,3),round(NAFLD.T2D.MIte.upperCI,3),round(NAFLD.T2D.MIps.upperCI,3)))

NAFLD.T2D.greedy<-subset(NAFLD.T2D.bootsrap,PSmethod=="Greedy Matching")
NAFLD.T2D.optimal<-subset(NAFLD.T2D.bootsrap,PSmethod=="Optimal Matching")
NAFLD.T2D.one_two<-subset(NAFLD.T2D.bootsrap,PSmethod=="1:2 Matching")
NAFLD.T2D.full<-subset(NAFLD.T2D.bootsrap,PSmethod=="Full Matching")
NAFLD.T2D.subc<-subset(NAFLD.T2D.bootsrap,PSmethod=="Stratification with 5 groups")
NAFLD.T2D.iptw<-subset(NAFLD.T2D.bootsrap,PSmethod=="IPTW")


Forstplot<-function(method,title){
  
  A <- cbind2(c("","MI Approach","CCA","MIte","MIps"), 
                     c("","Effect", as.character(method$est)))

  B <-cbind2(c("","SE", as.character(method$se)),
                     c("","p-value", ifelse(method$pvalue<0.001, "<0.001", method$pvalue)))
  
  tabletext <- cbind2(A,B)
  NAFLD.T2D.result <- 
    structure(list(
      mean  = c(NA, NA, method$est), 
      lower = c(NA, NA, method$lowerCI),
      upper = c(NA, NA, method$upperCI)),
      .Names = c("mean", "lower", "upper"), 
      row.names = c(NA, -5L), 
      class = "data.frame")
  
  forestplot(tabletext, 
             NAFLD.T2D.result,
             new_page = TRUE,
             xlab = "Estimate with 95% CI",
             col = fpColors(box="royalblue",line="darkblue"),
             hrzl_lines= gpar(col = "#444444"),
             is.summary = c(TRUE, TRUE, rep(FALSE, 18)),
             clip = c(0.5,5.5), zero=1,
             txt_gp=fpTxtGp(label = gpar(cex = 0.8),
                            title = gpar(cex = 1),
                            ticks = gpar(cex = 0.7),
                            xlab = gpar(cex = 0.7)),
             grid = structure(seq(1, 5.5, by=0.5), 
                              gp = gpar(lty = 2, col = "#CCCCFF")),
             xticks=c(0.5,1, 1.5),
             title=title)
}

Forstplot(NAFLD.T2D.greedy,"Exposure of T2D on of Greedy Matching")
Forstplot(NAFLD.T2D.optimal,"Exposure of T2D on of Optimal Matching")
Forstplot(NAFLD.T2D.one_two,"Exposure of T2D on of 1:2 Matching")
Forstplot(NAFLD.T2D.full,"Exposure of T2D on of Full Matching")
Forstplot(NAFLD.T2D.subc,"Exposure of T2D on of Stratification with 5 groups")
Forstplot(NAFLD.T2D.iptw,"Exposure of T2D on of IPTW ")
```

```{r}

A<-c("","PS Method","Greedy Matching","","","","Optimal Matching","","","","1:2 Matching","","","",
                                       "Full Matching","","","","Stratification with 5 groups", "","","","IPTW","","","","Crude","","")
  
B <- cbind2(c("","MI Approach",rep(c("CCA","MIte","MIps"," "),6),"CCA","MIte","MIps"), 
                     c("","Effect", NAFLD.T2D.greedy$est,"",NAFLD.T2D.optimal$est,"",NAFLD.T2D.one_two$est,"",NAFLD.T2D.full$est,"",NAFLD.T2D.subc$est,"",NAFLD.T2D.iptw$est,"",NAFLD.T2D.crude$est))
  
C <-cbind2(c("","SE", as.character(NAFLD.T2D.greedy$se),"",as.character(NAFLD.T2D.optimal$se),"",
               as.character(NAFLD.T2D.one_two$se),"",as.character(NAFLD.T2D.full$se),"",
               as.character(NAFLD.T2D.subc$se),"",as.character(NAFLD.T2D.iptw$se),"",
               as.character(NAFLD.T2D.crude$se)),
             c("","p-value", as.character(ifelse(NAFLD.T2D.greedy$pvalue<0.001, "<0.001",
                                                 round(NAFLD.T2D.greedy$pvalue,3))),"",
               as.character(ifelse(NAFLD.T2D.optimal$pvalue<0.001, "<0.001",
                                   round(NAFLD.T2D.optimal$pvalue,3))),"",
               as.character(ifelse(NAFLD.T2D.one_two$pvalue<0.001, "<0.001", 
                                          round(NAFLD.T2D.one_two$pvalue,3))),
               "",as.character(ifelse(NAFLD.T2D.full$pvalue<0.001, "<0.001", round(NAFLD.T2D.full$pvalue,3))),"",
               as.character(ifelse(NAFLD.T2D.subc$pvalue<0.001, "<0.001", round(NAFLD.T2D.subc$pvalue,3))),"",
               as.character(ifelse(NAFLD.T2D.iptw$pvalue<0.001, "<0.001", round(NAFLD.T2D.iptw$pvalue,3))),"",
               as.character(ifelse(NAFLD.T2D.crude$pvalue<0.001, "<0.001", round(NAFLD.T2D.curde$pvalue,3)))))
D <-cbind2(A,B)
tabletext <- cbind2(D,C)
NAFLD.T2D.result <- 
    structure(list(
      mean  = c(NA, NA, NAFLD.T2D.greedy$est,NA,NAFLD.T2D.optimal$est,NA,NAFLD.T2D.one_two$est,NA,NAFLD.T2D.full$est,NA,NAFLD.T2D.subc$est,NA,NAFLD.T2D.iptw$est,NA,NAFLD.T2D.crude$est), 
      lower = c(NA, NA, NAFLD.T2D.greedy$lowerCI,NA,NAFLD.T2D.optimal$lowerCI,NA,NAFLD.T2D.one_two$lowerCI,NA,NAFLD.T2D.full$lowerCI,NA,NAFLD.T2D.subc$lowerCI,NA,NAFLD.T2D.iptw$lowerCI,NA,NAFLD.T2D.crude$lowerCI),
      upper = c(NA, NA, NAFLD.T2D.greedy$upperCI,NA,NAFLD.T2D.optimal$upperCI,NA,NAFLD.T2D.one_two$upperCI,NA,NAFLD.T2D.full$upperCI,NA,NAFLD.T2D.subc$upperCI,NA,NAFLD.T2D.iptw$upperCI,NA,NAFLD.T2D.crude$upperCI)),
      .Names = c("mean", "lower", "upper"), 
      row.names = c(NA, -29L), 
      class = "data.frame")

forestplot(tabletext, 
             NAFLD.T2D.result,
             new_page = TRUE,
             col = fpColors(box="royalblue",line="darkblue"),
             hrzl_lines= gpar(col = "#444444"),
             is.summary = c(TRUE, TRUE, rep(FALSE, 29)),
             clip = c(0.5,2.5), zero=1,
             txt_gp=fpTxtGp(label = gpar(cex = 0.8),
                            title = gpar(cex = 1),
                            ticks = gpar(cex = 0.7),
                            xlab = gpar(cex = 0.7)),
             grid = structure(seq(0, 1, by=0.5), 
                              gp = gpar(lty = 0.5, col = "#CCCCFF")),
           xticks=c(0.5,1, 1.5),
           xlab = "Estimate with 95% CI",
           title="Forest Plot of Bootstrap LASSO")

```

# Bootstrap LASSO (with interaction)

```{r}
#################################
######## Bootstrap LASSO ########
####### (with interaction) ######
#################################
newvariables.bootstrap.interaction<-c("Waist_circumference", "Glycated_haemoglobin__HbA1c_:Waist_circumference")
ps.formula <- as.formula((paste("T2D ~",paste(newvariables.bootstrap.interaction,collapse = "+"))))
set.seed(1234)
param<-matchit(ps.formula,data = omitNAFLD)
omitNAFLD$param_ps<-param$distance
ggplot(data = omitNAFLD,aes(param_ps,fill=factor(T2D)))+
  geom_histogram(binwidth = 0.005,alpha = 0.5,position="identity")
logitPS<-sd(-log(1/omitNAFLD$param_ps-1))
```
## CCA
```{r}
################################
############# CCA ##############
################################
set.seed(1234)
## Greedy matching
greedy<-matchit(ps.formula,data=omitNAFLD,
                distance="logit",
                caliper=0.1*sd(logitPS),
                method="nearest")
greedy

set.seed(1234)
## Optimal matching
optimal <- matchit(ps.formula,data= omitNAFLD,
                   distance="logit",
                   method = "optimal")
optimal

set.seed(1234)
## 1:2 matching
one_two <- matchit(ps.formula,data=omitNAFLD,
                   distance="logit",
                   caliper=0.1*sd(logitPS),
                   method = "nearest", ratio = 2)
one_two

set.seed(1234)
## Full matching
full <- matchit(ps.formula,data=omitNAFLD,
                distance="logit",
                caliper=0.1*sd(logitPS),
                method = "full")
full

## Subclassification
omitNAFLD <- omitNAFLD %>% mutate(subclass = ntile(param_ps, 5))

set.seed(1234)
## Subclassification with full matching
subc <- matchit(ps.formula, data = omitNAFLD,
                method = "subclass",
                subclass = 5)
subc

plot(subc, type = "jitter")

### Weighting
set.seed(1234)
## IPTW with stabilization
omitNAFLD$iptw<- ifelse(omitNAFLD$T2D == 1, (mean(omitNAFLD$param_ps))/omitNAFLD$param_ps, 
                        (mean(1-omitNAFLD$param_ps))/(1-omitNAFLD$param_ps))
iptw <- dx.wts(omitNAFLD$iptw, data = as.data.frame(omitNAFLD), treat.var="T2D",estimand = "ATT")
# NAFLD_status~T2D
formula1<-as.formula((paste("NAFLD_status","~ T2D+ ",paste(newvariables.bootstrap.interaction,collapse = "+"))))
set.seed(1234)
## Greedy matching
matched_greedy <- match.data(greedy,subclass = "block")
glm_NAFLD_greedy <- glm(formula1,
                        data = matched_greedy,
                        family = binomial)
summary_greedy <- summary(glm_NAFLD_greedy)
exp(coef(glm_NAFLD_greedy))

set.seed(1234)
## Optimal matching
matched_optimal <- match.data(optimal,subclass = "block")
glm_NAFLD_optimal <- glm(formula1,
                         data = matched_optimal,
                         family = binomial)
summary_optimal <- summary(glm_NAFLD_optimal)
exp(coef(glm_NAFLD_optimal))

set.seed(1234)
## 1:2 matching
matched_one_two <- match.data(one_two,subclass = "block")
glm_NAFLD_one_two <- glm(formula1, 
                         data = matched_one_two,
                         family = binomial)
summary_one_two <- summary(glm_NAFLD_one_two)
exp(coef(glm_NAFLD_one_two))

set.seed(1234)
## Full matching
matched_full <- match.data(full,subclass = "block")
glm_NAFLD_full <- glm(formula1,
                      data = matched_full,
                      family = binomial, weights = weights)
summary_full <-summary(glm_NAFLD_full)
exp(coef(glm_NAFLD_full))

set.seed(1234)
## Subclassification with full matching
subced <- match.data(subc,subclass = "block")
design <- svydesign(id = ~1, strata = ~subclass, weights = ~weights, nested = TRUE, data = subced)
svyglm_NAFLD_subc <- svyglm(formula1, design = design, family = binomial)
summary_subc <- summary(svyglm_NAFLD_subc)
exp(coef(svyglm_NAFLD_subc))

set.seed(1234)
## Weighting by IPTW with stabilization
glm_NAFLD_iptw <- glm(formula1,
                      data = omitNAFLD,
                      weights = iptw,
                      family = binomial)
summary_iptw <-summary(glm_NAFLD_iptw)
exp(coef(glm_NAFLD_iptw))

NAFLD.T2D.HR.est<-c()
NAFLD.T2D.logHR.est<-c()
NAFLD.T2D.se<-c()
NAFLD.T2D.pvalue<-c()
NAFLD.T2D.lowerCI<-c()
NAFLD.T2D.upperCI<-c()

NAFLD.T2D.HR.est[1] <-exp(summary_greedy$coefficients[2,1])
NAFLD.T2D.logHR.est[1]<-summary_greedy$coefficients[2,1]
NAFLD.T2D.se[1]<-summary_greedy$coefficients[2,2]
NAFLD.T2D.pvalue[1]<-summary_greedy$coefficients[2,4]
NAFLD.T2D.lowerCI[1]<- exp(summary_greedy$coefficients[2,1]-1.96*summary_greedy$coefficients[2,2])
NAFLD.T2D.upperCI[1]<- exp(summary_greedy$coefficients[2,1]+1.96*summary_greedy$coefficients[2,2])

NAFLD.T2D.HR.est[2] <-exp(summary_optimal$coefficients[2,1])
NAFLD.T2D.logHR.est[2]<-summary_optimal$coefficients[2,1]
NAFLD.T2D.se[2]<-summary_optimal$coefficients[2,2]
NAFLD.T2D.pvalue[2]<-summary_optimal$coefficients[2,4]
NAFLD.T2D.lowerCI[2]<- exp(summary_optimal$coefficients[2,1]-1.96*summary_optimal$coefficients[2,2])
NAFLD.T2D.upperCI[2]<- exp(summary_optimal$coefficients[2,1]+1.96*summary_optimal$coefficients[2,2])

NAFLD.T2D.HR.est[3] <-exp(summary_one_two$coefficients[2,1])
NAFLD.T2D.logHR.est[3]<-summary_one_two$coefficients[2,1]
NAFLD.T2D.se[3]<-summary_one_two$coefficients[2,2]
NAFLD.T2D.pvalue[3]<-summary_one_two$coefficients[2,4]
NAFLD.T2D.lowerCI[3]<- exp(summary_one_two$coefficients[2,1]-1.96*summary_one_two$coefficients[2,2])
NAFLD.T2D.upperCI[3]<- exp(summary_one_two$coefficients[2,1]+1.96*summary_one_two$coefficients[2,2])

NAFLD.T2D.HR.est[4] <-exp(summary_full$coefficients[2,1])
NAFLD.T2D.logHR.est[4]<-summary_full$coefficients[2,1]
NAFLD.T2D.se[4]<-summary_full$coefficients[2,2]
NAFLD.T2D.pvalue[4]<-summary_full$coefficients[2,4]
NAFLD.T2D.lowerCI[4]<- exp(summary_full$coefficients[2,1]-1.96*summary_full$coefficients[2,2])
NAFLD.T2D.upperCI[4]<- exp(summary_full$coefficients[2,1]+1.96*summary_full$coefficients[2,2])

NAFLD.T2D.HR.est[5] <-exp(summary_subc$coefficients[2,1])
NAFLD.T2D.logHR.est[5]<-summary_subc$coefficients[2,1]
NAFLD.T2D.se[5]<-summary_subc$coefficients[2,2]
NAFLD.T2D.pvalue[5]<-summary_subc$coefficients[2,4]
NAFLD.T2D.lowerCI[5]<- exp(summary_subc$coefficients[2,1]-1.96*summary_subc$coefficients[2,2])
NAFLD.T2D.upperCI[5]<- exp(summary_subc$coefficients[2,1]+1.96*summary_subc$coefficients[2,2])

NAFLD.T2D.HR.est[6] <-exp(summary_iptw$coefficients[2,1])
NAFLD.T2D.logHR.est[6]<-summary_iptw$coefficients[2,1]
NAFLD.T2D.se[6]<-summary_iptw$coefficients[2,2]
NAFLD.T2D.pvalue[6]<-summary_iptw$coefficients[2,4]
NAFLD.T2D.lowerCI[6]<- exp(summary_iptw$coefficients[2,1]-1.96*summary_iptw$coefficients[2,2])
NAFLD.T2D.upperCI[6]<- exp(summary_iptw$coefficients[2,1]+1.96*summary_iptw$coefficients[2,2])

NAFLD.T2D.HR.est[7] <-exp(summary_glm$coefficients[2,1])
NAFLD.T2D.logHR.est[7]<-summary_glm$coefficients[2,1]
NAFLD.T2D.se[7]<-summary_glm$coefficients[2,2]
NAFLD.T2D.pvalue[7]<-summary_glm$coefficients[2,4]
NAFLD.T2D.lowerCI[7]<- exp(summary_glm$coefficients[2,1]-1.96*summary_glm$coefficients[2,2])
NAFLD.T2D.upperCI[7]<- exp(summary_glm$coefficients[2,1]+1.96*summary_glm$coefficients[2,2])

NAFLDoutcome.T2D.result <- 
  structure(list(
    mean  = c(NA, NA, NAFLD.T2D.HR.est), 
    lower = c(NA, NA, NAFLD.T2D.lowerCI),
    upper = c(NA, NA, NAFLD.T2D.upperCI)),
    .Names = c("mean", "lower", "upper"), 
    row.names = c(NA, -8L), 
    class = "data.frame")

A <- cbind2(c("","Method","Greedy Matching","Optimal Matching","1:2 Matching",
              "Full Matching","Stratification with 5 groups", "IPTW","Crude"),
                 c("","Effect", as.character(round(NAFLD.T2D.HR.est,3))))
B<- cbind2(c("","SE", as.character(round(NAFLD.T2D.se,3))),
           c("","p-value", ifelse(NAFLD.T2D.pvalue<0.001, "<0.001", round(NAFLD.T2D.pvalue,3))))
tabletext <- cbind2(A ,B)

forestplot(tabletext, 
           NAFLDoutcome.T2D.result,new_page = TRUE,
           col = fpColors(box="royalblue",line="darkblue"),
           xlab = "Estimate with 95% CI",
           hrzl_lines= gpar(col = "#444444"),
           is.summary = c(TRUE, TRUE, rep(FALSE, 10)),
           clip = c(0.5,5.5), zero=0.5,
           txt_gp=fpTxtGp(label = gpar(cex = 0.8),
                          title = gpar(cex = 1),
                          ticks = gpar(cex = 0.7),
                          xlab = gpar(cex = 0.7)),
           grid = structure(seq(0.5, 5.5, by=0.25), 
                            gp = gpar(lty = 2, col = "#CCCCFF")))
grid.text("Exposure of T2D on NAFLD", .5, 0.98, gp=gpar(fontface="bold"))
```

## MIte
```{r}
################################
############# MI ###############
################################



################################
############MIte################
################################
set.seed(1234)
## Greedy matching
greedy.matched.MIte.datasets <- matchthem(ps.formula, mi.data,
                                          approach = 'within',
                                          method = 'nearest',
                                          caliper = 0.05)
greedy.matched.MIte.datasets

set.seed(1234)
## Optimal matching
optimal.matched.MIte.datasets <- matchthem(ps.formula, mi.data,
                                           approach = 'within',
                                           method = 'optimal',
                                           caliper = 0.05)
optimal.matched.MIte.datasets

set.seed(1234)
## 1:2 matching
one_two.matched.MIte.datasets <- matchthem(ps.formula, mi.data,
                                           approach = 'within',
                                           method = 'nearest',
                                           caliper = 0.05, ratio = 2)
one_two.matched.MIte.datasets 

set.seed(1234)
## Full matching
full.matched.MIte.datasets <- matchthem(ps.formula,mi.data,
                                        approach = 'within',
                                        caliper = 0.05,
                                        method = "full")
full.matched.MIte.datasets

set.seed(1234)
## Subclassification with full matching
subc.MIte.datasets <- matchthem(ps.formula, mi.data,
                                approach = 'within',
                                method = "subclass",
                                subclass = 5)
subc.MIte.datasets
plot(subc.MIte.datasets, type = "jitter")

set.seed(1234)
# IPTW
weighted.MIte.datasets <- weightthem(ps.formula, mi.data,
                                     approach = 'within', 
                                     method = 'ps', estimand = 'ATM')
weighted.MIte.datasets

library(cobalt)
bal.tab(greedy.matched.MIte.datasets, abs = TRUE)
bal.tab(optimal.matched.MIte.datasets, abs = TRUE)
bal.tab(one_two.matched.MIte.datasets, abs = TRUE)
bal.tab(full.matched.MIte.datasets, abs = TRUE)
bal.tab(subc.MIte.datasets, abs = TRUE)
bal.tab(weighted.MIte.datasets, abs = TRUE)

library(survey)
formula1<-as.formula((paste("NAFLD_status","~ T2D+ ",paste(newvariables.bootstrap.interaction,collapse = "+"))))

set.seed(1234)
greedy.matched.MIte.models <- with(data = greedy.matched.MIte.datasets,
                                   expr = svyglm(formula1, family = quasibinomial))
greedy.matched.MIte.results <- pool(greedy.matched.MIte.models)
summary_MIte_greedy <- summary(greedy.matched.MIte.results, conf.int = TRUE)

set.seed(1234)
optimal.matched.MIte.models <- with(data = optimal.matched.MIte.datasets,
                                    expr = svyglm(formula1, family =quasibinomial))
optimal.matched.MIte.results <- pool(optimal.matched.MIte.models)
summary_MIte_optimal <-summary(optimal.matched.MIte.results, conf.int = TRUE)

set.seed(1234)
one_two.matched.MIte.models <- with(data = one_two.matched.MIte.datasets,
                                    expr = svyglm(formula1, family = quasibinomial))
one_two.matched.MIte.results <- pool(one_two.matched.MIte.models)
summary_MIte_one_two <- summary(one_two.matched.MIte.results, conf.int = TRUE)

set.seed(1234)
full.matched.MIte.models <- with(data = full.matched.MIte.datasets,
                                 expr = svyglm(formula1, family = quasibinomial))
full.matched.MIte.results <- pool(full.matched.MIte.models)
summary_MIte_full <- summary(full.matched.MIte.results, conf.int = TRUE)

set.seed(1234)
subc.MIte.models <- with(data = subc.MIte.datasets,
                         expr = svyglm(formula1, family = quasibinomial))
subc.MIte.results <- pool(subc.MIte.models)
summary_MIte_subc <-summary(subc.MIte.results, conf.int = TRUE)

set.seed(1234)
# IPTW
weighted.MIte.models <- with(data = weighted.MIte.datasets, expr = svyglm(formula1, family = quasibinomial))
weighted.MIte.results <- pool(weighted.MIte.models)
summary_MIte_iptw <-summary(weighted.MIte.results, conf.int = TRUE)

NAFLD.T2D.MIte.HR.est<-c()
NAFLD.T2D.MIte.logHR.est<-c()
NAFLD.T2D.MIte.se<-c()
NAFLD.T2D.MIte.pvalue<-c()
NAFLD.T2D.MIte.lowerCI<-c()
NAFLD.T2D.MIte.upperCI<-c()

NAFLD.T2D.MIte.HR.est[1] <-exp(summary_MIte_greedy[2,2])
NAFLD.T2D.MIte.logHR.est[1]<-summary_MIte_greedy[2,2]
NAFLD.T2D.MIte.se[1]<-summary_MIte_greedy[2,3]
NAFLD.T2D.MIte.pvalue[1]<-summary_MIte_greedy[2,6]
NAFLD.T2D.MIte.lowerCI[1]<- exp(summary_MIte_greedy[2,7])
NAFLD.T2D.MIte.upperCI[1]<- exp(summary_MIte_greedy[2,8])

NAFLD.T2D.MIte.HR.est[2] <-exp(summary_MIte_optimal[2,2])
NAFLD.T2D.MIte.logHR.est[2]<-summary_MIte_optimal[2,2]
NAFLD.T2D.MIte.se[2]<-summary_MIte_optimal[2,3]
NAFLD.T2D.MIte.pvalue[2]<-summary_MIte_optimal[2,6]
NAFLD.T2D.MIte.lowerCI[2]<- exp(summary_MIte_optimal[2,7])
NAFLD.T2D.MIte.upperCI[2]<- exp(summary_MIte_optimal[2,8])

NAFLD.T2D.MIte.HR.est[3] <-exp(summary_MIte_one_two[2,2])
NAFLD.T2D.MIte.logHR.est[3]<-summary_MIte_one_two[2,2]
NAFLD.T2D.MIte.se[3]<-summary_MIte_one_two[2,3]
NAFLD.T2D.MIte.pvalue[3]<-summary_MIte_one_two[2,6]
NAFLD.T2D.MIte.lowerCI[3]<- exp(summary_MIte_one_two[2,7])
NAFLD.T2D.MIte.upperCI[3]<- exp(summary_MIte_one_two[2,8])

NAFLD.T2D.MIte.HR.est[4] <-exp(summary_MIte_full[2,2])
NAFLD.T2D.MIte.logHR.est[4]<-summary_MIte_full[2,2]
NAFLD.T2D.MIte.se[4]<-summary_MIte_full[2,3]
NAFLD.T2D.MIte.pvalue[4]<-summary_MIte_full[2,6]
NAFLD.T2D.MIte.lowerCI[4]<- exp(summary_MIte_full[2,7])
NAFLD.T2D.MIte.upperCI[4]<- exp(summary_MIte_full[2,8])

NAFLD.T2D.MIte.HR.est[5] <-exp(summary_MIte_subc[2,2])
NAFLD.T2D.MIte.logHR.est[5]<-summary_MIte_subc[2,2]
NAFLD.T2D.MIte.se[5]<-summary_MIte_subc[2,3]
NAFLD.T2D.MIte.pvalue[5]<-summary_MIte_subc[2,6]
NAFLD.T2D.MIte.lowerCI[5]<- exp(summary_MIte_subc[2,7])
NAFLD.T2D.MIte.upperCI[5]<- exp(summary_MIte_subc[2,8])

NAFLD.T2D.MIte.HR.est[6] <-exp(summary_MIte_iptw[2,2])
NAFLD.T2D.MIte.logHR.est[6]<-summary_MIte_iptw[2,2]
NAFLD.T2D.MIte.se[6]<-summary_MIte_iptw[2,3]
NAFLD.T2D.MIte.pvalue[6]<-summary_MIte_iptw[2,6]
NAFLD.T2D.MIte.lowerCI[6]<- exp(summary_MIte_iptw[2,7])
NAFLD.T2D.MIte.upperCI[6]<- exp(summary_MIte_iptw[2,8])

NAFLD.T2D.MIte.HR.est[7] <-exp(summary_glm_mi$coefficients[2,1])
NAFLD.T2D.MIte.logHR.est[7]<-summary_glm_mi$coefficients[2,1]
NAFLD.T2D.MIte.se[7]<-summary_glm_mi$coefficients[2,2]
NAFLD.T2D.MIte.pvalue[7]<-summary_glm_mi$coefficients[2,4]
NAFLD.T2D.MIte.lowerCI[7]<- exp(summary_glm_mi$coefficients[2,1]-1.96*summary_glm_mi$coefficients[2,2])
NAFLD.T2D.MIte.upperCI[7]<- exp(summary_glm_mi$coefficients[2,1]+1.96*summary_glm_mi$coefficients[2,2])

NAFLDoutcome.T2D.MIte.result <- 
  structure(list(
    mean  = c(NA, NA, NAFLD.T2D.MIte.HR.est), 
    lower = c(NA, NA, NAFLD.T2D.MIte.lowerCI),
    upper = c(NA, NA, NAFLD.T2D.MIte.upperCI)),
    .Names = c("mean", "lower", "upper"), 
    row.names = c(NA, -8L), 
    class = "data.frame")

A <- cbind2(c("","Method","Greedy Matching","Optimal Matching","1:2 Matching",
              "Full Matching","Stratification with 5 groups", "IPTW","Crude"),
            c("","Effect", as.character(round(NAFLD.T2D.MIte.HR.est,3))))
B<- cbind2(c("","SE", as.character(round(NAFLD.T2D.MIte.se,3))),
           c("","p-value", ifelse(NAFLD.T2D.MIte.pvalue<0.001, "<0.001", round(NAFLD.T2D.MIte.pvalue,3))))
tabletext <- cbind2(A ,B)

forestplot(tabletext, 
           NAFLDoutcome.T2D.MIte.result,new_page = TRUE,
           col = fpColors(box="royalblue",line="darkblue"),
           xlab = "Estimate with 95% CI",
           hrzl_lines= gpar(col = "#444444"),
           is.summary = c(TRUE, TRUE, rep(FALSE, 10)),
           clip = c(0,5.5), zero=1,
           txt_gp=fpTxtGp(label = gpar(cex = 0.8),
                          title = gpar(cex = 1),
                          ticks = gpar(cex = 0.7),
                          xlab = gpar(cex = 0.7)),
           grid = structure(seq(1,5, by=0.25), 
                            gp = gpar(lty = 2, col = "#CCCCFF")),
           xticks=c(0.5,1, 1.5))
grid.text("Exposure of T2D on NAFLD by MIte", .5, 0.98, gp=gpar(fontface="bold"))
```
## MIps
```{r}
################################
############MIps################
################################
set.seed(1234)
## Greedy matching
greedy.matched.MIps.across.datasets <- matchthem(ps.formula, mi.data,
                                                 approach = 'across',
                                                 method = 'nearest',
                                                 caliper = 0.05)
greedy.matched.MIps.across.datasets

set.seed(1234)
## Optimal matching
optimal.matched.MIps.across.datasets <- matchthem(ps.formula, mi.data,
                                                  approach = 'across',
                                                  method = 'optimal',
                                                  caliper = 0.05)
optimal.matched.MIps.across.datasets

set.seed(1234)
## 1:2 matching
one_two.matched.MIps.across.datasets <- matchthem(ps.formula, mi.data,
                                                  approach = 'across',
                                                  method = 'nearest',
                                                  caliper = 0.05, ratio = 2)
one_two.matched.MIps.across.datasets

set.seed(1234)
## Full matching
full.matched.MIps.across.datasets <- matchthem(ps.formula,mi.data,
                                               approach = 'across',
                                               caliper = 0.05,
                                               method = "full")
full.matched.MIps.across.datasets

set.seed(1234)
## Subclassification with full matching
subc.MIps.across.datasets <- matchthem(ps.formula, mi.data,
                                       approach = 'across',
                                       method = "subclass",
                                       subclass = 5)
subc.MIps.across.datasets
plot(subc.MIps.across.datasets, type = "jitter")

set.seed(1234)
# IPTW
weighted.across.datasets <- weightthem(ps.formula, mi.data,
                                       approach = 'across', 
                                       method = 'ps', estimand = 'ATM')
weighted.across.datasets

bal.tab(greedy.matched.MIps.across.datasets, abs = TRUE)
bal.tab(optimal.matched.MIps.across.datasets, abs = TRUE)
bal.tab(one_two.matched.MIps.across.datasets, abs = TRUE)
bal.tab(full.matched.MIps.across.datasets, abs = TRUE)
bal.tab(subc.MIps.across.datasets, abs = TRUE)
bal.tab(weighted.across.datasets, abs = TRUE)

formula1<-as.formula((paste("NAFLD_status","~ T2D+ ",paste(newvariables.bootstrap.interaction,collapse = "+"))))

set.seed(1234)
greedy.matched.MIps.across.models <- with(data = greedy.matched.MIps.across.datasets,
                                          expr = svyglm(formula1, family = quasibinomial))
greedy.matched.MIps.across.results <- pool(greedy.matched.MIps.across.models)
summary_MIps_greedy <- summary(greedy.matched.MIps.across.results, conf.int = TRUE)

set.seed(1234)
optimal.matched.MIps.across.models <- with(data = optimal.matched.MIps.across.datasets,
                                           expr = svyglm(formula1, family =quasibinomial))
optimal.matched.MIps.across.results <- pool(optimal.matched.MIps.across.models)
summary_MIps_optimal <-summary(optimal.matched.MIps.across.results, conf.int = TRUE)

set.seed(1234)
one_two.matched.MIps.across.models <- with(data = one_two.matched.MIps.across.datasets,
                                           expr = svyglm(formula1, family = quasibinomial))
one_two.matched.MIps.across.results <- pool(one_two.matched.MIps.across.models)
summary_MIps_one_two <- summary(one_two.matched.MIps.across.results, conf.int = TRUE)

set.seed(1234)
full.matched.MIps.across.models <- with(data = full.matched.MIps.across.datasets,
                                        expr = svyglm(formula1, family = quasibinomial))
full.matched.MIps.across.results <- pool(full.matched.MIps.across.models)
summary_MIps_full <- summary(full.matched.MIps.across.results, conf.int = TRUE)

set.seed(1234)
subc.MIps.across.models <- with(data = subc.MIps.across.datasets,
                                expr = svyglm(formula1, family = quasibinomial))
subc.MIps.across.results <- pool(subc.MIps.across.models)
summary_MIps_subc <-summary(subc.MIps.across.results, conf.int = TRUE)

# IPTW
set.seed(1234)
weighted.across.models <- with(data = weighted.across.datasets, expr = svyglm(formula1, family = quasibinomial))
weighted.across.results <- pool(weighted.across.models)
summary_MIps_iptw <-summary(weighted.across.results, conf.int = TRUE)

NAFLD.T2D.MIps.HR.est<-c()
NAFLD.T2D.MIps.logHR.est<-c()
NAFLD.T2D.MIps.se<-c()
NAFLD.T2D.MIps.pvalue<-c()
NAFLD.T2D.MIps.lowerCI<-c()
NAFLD.T2D.MIps.upperCI<-c()

NAFLD.T2D.MIps.HR.est[1] <-exp(summary_MIps_greedy[2,2])
NAFLD.T2D.MIps.logHR.est[1]<-summary_MIps_greedy[2,2]
NAFLD.T2D.MIps.se[1]<-summary_MIps_greedy[2,3]
NAFLD.T2D.MIps.pvalue[1]<-summary_MIps_greedy[2,6]
NAFLD.T2D.MIps.lowerCI[1]<- exp(summary_MIps_greedy[2,7])
NAFLD.T2D.MIps.upperCI[1]<- exp(summary_MIps_greedy[2,8])

NAFLD.T2D.MIps.HR.est[2] <-exp(summary_MIps_optimal[2,2])
NAFLD.T2D.MIps.logHR.est[2]<-summary_MIps_optimal[2,2]
NAFLD.T2D.MIps.se[2]<-summary_MIps_optimal[2,3]
NAFLD.T2D.MIps.pvalue[2]<-summary_MIps_optimal[2,6]
NAFLD.T2D.MIps.lowerCI[2]<- exp(summary_MIps_optimal[2,7])
NAFLD.T2D.MIps.upperCI[2]<- exp(summary_MIps_optimal[2,8])

NAFLD.T2D.MIps.HR.est[3] <-exp(summary_MIps_one_two[2,2])
NAFLD.T2D.MIps.logHR.est[3]<-summary_MIps_one_two[2,2]
NAFLD.T2D.MIps.se[3]<-summary_MIps_one_two[2,3]
NAFLD.T2D.MIps.pvalue[3]<-summary_MIps_one_two[2,6]
NAFLD.T2D.MIps.lowerCI[3]<- exp(summary_MIps_one_two[2,7])
NAFLD.T2D.MIps.upperCI[3]<- exp(summary_MIps_one_two[2,8])

NAFLD.T2D.MIps.HR.est[4] <-exp(summary_MIps_full[2,2])
NAFLD.T2D.MIps.logHR.est[4]<-summary_MIps_full[2,2]
NAFLD.T2D.MIps.se[4]<-summary_MIps_full[2,3]
NAFLD.T2D.MIps.pvalue[4]<-summary_MIps_full[2,6]
NAFLD.T2D.MIps.lowerCI[4]<- exp(summary_MIps_full[2,7])
NAFLD.T2D.MIps.upperCI[4]<- exp(summary_MIps_full[2,8])

NAFLD.T2D.MIps.HR.est[5] <-exp(summary_MIps_subc[2,2])
NAFLD.T2D.MIps.logHR.est[5]<-summary_MIps_subc[2,2]
NAFLD.T2D.MIps.se[5]<-summary_MIps_subc[2,3]
NAFLD.T2D.MIps.pvalue[5]<-summary_MIps_subc[2,6]
NAFLD.T2D.MIps.lowerCI[5]<- exp(summary_MIps_subc[2,7])
NAFLD.T2D.MIps.upperCI[5]<- exp(summary_MIps_subc[2,8])

NAFLD.T2D.MIps.HR.est[6] <-exp(summary_MIps_iptw[2,2])
NAFLD.T2D.MIps.logHR.est[6]<-summary_MIps_iptw[2,2]
NAFLD.T2D.MIps.se[6]<-summary_MIps_iptw[2,3]
NAFLD.T2D.MIps.pvalue[6]<-summary_MIps_iptw[2,6]
NAFLD.T2D.MIps.lowerCI[6]<- exp(summary_MIps_iptw[2,7])
NAFLD.T2D.MIps.upperCI[6]<- exp(summary_MIps_iptw[2,8])

NAFLD.T2D.MIps.HR.est[7] <-exp(summary_glm_mi$coefficients[2,1])
NAFLD.T2D.MIps.logHR.est[7]<-summary_glm_mi$coefficients[2,1]
NAFLD.T2D.MIps.se[7]<-summary_glm_mi$coefficients[2,2]
NAFLD.T2D.MIps.pvalue[7]<-summary_glm_mi$coefficients[2,4]
NAFLD.T2D.MIps.lowerCI[7]<- exp(summary_glm_mi$coefficients[2,1]-1.96*summary_glm_mi$coefficients[2,2])
NAFLD.T2D.MIps.upperCI[7]<- exp(summary_glm_mi$coefficients[2,1]+1.96*summary_glm_mi$coefficients[2,2])

NAFLDoutcome.T2D.MIps.result <- 
  structure(list(
    mean  = c(NA, NA, NAFLD.T2D.MIps.HR.est), 
    lower = c(NA, NA, NAFLD.T2D.MIps.lowerCI),
    upper = c(NA, NA, NAFLD.T2D.MIps.upperCI)),
    .Names = c("mean", "lower", "upper"), 
    row.names = c(NA, -9L), 
    class = "data.frame")


A <- cbind2(c("","Method","Greedy Matching","Optimal Matching","1:2 Matching",
              "Full Matching","Stratification with 5 groups", "IPTW","Crude"),
               c("","Effect", as.character(round(NAFLD.T2D.MIps.HR.est,3))))
B<- cbind2(c("","SE", as.character(round(NAFLD.T2D.MIps.se,3))),
           c("","p-value", ifelse(NAFLD.T2D.MIps.pvalue<0.001, "<0.001", 
                                          round(NAFLD.T2D.MIps.pvalue,3))))
tabletext <- cbind2(A ,B)

forestplot(tabletext, 
           NAFLDoutcome.T2D.MIps.result,new_page = TRUE,
           col = fpColors(box="royalblue",line="darkblue"),
           xlab = "Estimate with 95% CI",
           hrzl_lines= gpar(col = "#444444"),
           is.summary = c(TRUE, TRUE, rep(FALSE, 10)),
           clip = c(0.5,5.5), zero=1,
           txt_gp=fpTxtGp(label = gpar(cex = 0.8),
                          title = gpar(cex = 1),
                          ticks = gpar(cex = 0.8),
                          xlab = gpar(cex = 0.7)),
           grid = structure(seq(1, 5.5, by=0.25), 
                            gp = gpar(lty = 2, col = "#CCCCFF")),
           xticks=c(0.5,1, 1.5))
grid.text("Exposure of T2D on NAFLD by MIps", .5, 0.98, gp=gpar(fontface="bold"))
```

```{r}
NAFLD.T2D.bootsrap.interaction<-data.frame(MLapproach=rep("Bootstap LASSO with interaction",21),MIapproach=c(rep("CCA",7),rep("MIte",7),rep("MIps",7)),
                      PSmethod=c(rep(c("Greedy Matching","Optimal Matching","1:2 Matching",
                                       "Full Matching","Stratification with 5 groups", "IPTW","Crude"),3)),
                      est=c(round(NAFLD.T2D.HR.est,3),round(NAFLD.T2D.MIte.HR.est,3),
                            round(NAFLD.T2D.MIps.HR.est,3)),
                      log.est=c(round(NAFLD.T2D.logHR.est,3),round(NAFLD.T2D.MIte.logHR.est,3),round(NAFLD.T2D.MIps.logHR.est,3)),
                      se=c(round(NAFLD.T2D.se,3),round(NAFLD.T2D.MIte.se,3),round(NAFLD.T2D.MIps.se,3)),
                      pvalue=c(round(NAFLD.T2D.pvalue,3),round(NAFLD.T2D.MIte.pvalue,3),round(NAFLD.T2D.MIps.pvalue,3)),
                      lowerCI=c(round(NAFLD.T2D.lowerCI,3),round(NAFLD.T2D.MIte.lowerCI,3),round(NAFLD.T2D.MIps.lowerCI,3)),
                      upperCI=c(round(NAFLD.T2D.upperCI,3),round(NAFLD.T2D.MIte.upperCI,3),round(NAFLD.T2D.MIps.upperCI,3)))

NAFLD.T2D.greedy<-subset(NAFLD.T2D.bootsrap.interaction,PSmethod=="Greedy Matching")
NAFLD.T2D.optimal<-subset(NAFLD.T2D.bootsrap.interaction,PSmethod=="Optimal Matching")
NAFLD.T2D.one_two<-subset(NAFLD.T2D.bootsrap.interaction,PSmethod=="1:2 Matching")
NAFLD.T2D.full<-subset(NAFLD.T2D.bootsrap.interaction,PSmethod=="Full Matching")
NAFLD.T2D.subc<-subset(NAFLD.T2D.bootsrap.interaction,PSmethod=="Stratification with 5 groups")
NAFLD.T2D.iptw<-subset(NAFLD.T2D.bootsrap.interaction,PSmethod=="IPTW")
NAFLD.T2D.crude<-subset(NAFLD.T2D.bootsrap.interaction,PSmethod=="Crude")


Forstplot<-function(method,title){
  
  A <- cbind2(c("","MI Approach","CCA","MIte","MIps"), 
                     c("","Effect", as.character(method$est)))

  B <-cbind2(c("","SE", as.character(method$se)),
                     c("","p-value", ifelse(method$pvalue<0.001, "<0.001", method$pvalue)))
  
  tabletext <- cbind2(A,B)
  NAFLD.T2D.result <- 
    structure(list(
      mean  = c(NA, NA, method$est), 
      lower = c(NA, NA, method$lowerCI),
      upper = c(NA, NA, method$upperCI)),
      .Names = c("mean", "lower", "upper"), 
      row.names = c(NA, -5L), 
      class = "data.frame")
  
  forestplot(tabletext, 
             NAFLD.T2D.result,
             new_page = TRUE,
             xlab = "Estimate with 95% CI",
             col = fpColors(box="royalblue",line="darkblue"),
             hrzl_lines= gpar(col = "#444444"),
             is.summary = c(TRUE, TRUE, rep(FALSE, 18)),
             clip = c(0.5,5.5), zero=1,
             txt_gp=fpTxtGp(label = gpar(cex = 0.8),
                            title = gpar(cex = 1),
                            ticks = gpar(cex = 0.7),
                            xlab = gpar(cex = 0.7)),
             grid = structure(seq(1, 5.5, by=0.5), 
                              gp = gpar(lty = 2, col = "#CCCCFF")),
             xticks=c(0.5,1, 1.5),
             title=title)
}

Forstplot(NAFLD.T2D.greedy,"Exposure of T2D on of Greedy Matching")
Forstplot(NAFLD.T2D.optimal,"Exposure of T2D on of Optimal Matching")
Forstplot(NAFLD.T2D.one_two,"Exposure of T2D on of 1:2 Matching")
Forstplot(NAFLD.T2D.full,"Exposure of T2D on of Full Matching")
Forstplot(NAFLD.T2D.subc,"Exposure of T2D on of Stratification with 5 groups")
Forstplot(NAFLD.T2D.iptw,"Exposure of T2D on of IPTW ")
```

```{r}

A<-c("","PS Method","Greedy Matching","","","","Optimal Matching","","","","1:2 Matching","","","",
                                       "Full Matching","","","","Stratification with 5 groups", "","","","IPTW","","","","Crude","","")
  
B <- cbind2(c("","MI Approach",rep(c("CCA","MIte","MIps"," "),6),"CCA","MIte","MIps"), 
                     c("","Effect", NAFLD.T2D.greedy$est,"",NAFLD.T2D.optimal$est,"",NAFLD.T2D.one_two$est,"",NAFLD.T2D.full$est,"",NAFLD.T2D.subc$est,"",NAFLD.T2D.iptw$est,"",NAFLD.T2D.crude$est))
  
C <-cbind2(c("","SE", as.character(NAFLD.T2D.greedy$se),"",as.character(NAFLD.T2D.optimal$se),"",
               as.character(NAFLD.T2D.one_two$se),"",as.character(NAFLD.T2D.full$se),"",
               as.character(NAFLD.T2D.subc$se),"",as.character(NAFLD.T2D.iptw$se),"",
               as.character(NAFLD.T2D.crude$se)),
             c("","p-value", as.character(ifelse(NAFLD.T2D.greedy$pvalue<0.001, "<0.001",
                                                 round(NAFLD.T2D.greedy$pvalue,3))),"",
               as.character(ifelse(NAFLD.T2D.optimal$pvalue<0.001, "<0.001",
                                   round(NAFLD.T2D.optimal$pvalue,3))),"",
               as.character(ifelse(NAFLD.T2D.one_two$pvalue<0.001, "<0.001", 
                                          round(NAFLD.T2D.one_two$pvalue,3))),
               "",as.character(ifelse(NAFLD.T2D.full$pvalue<0.001, "<0.001", round(NAFLD.T2D.full$pvalue,3))),"",
               as.character(ifelse(NAFLD.T2D.subc$pvalue<0.001, "<0.001", round(NAFLD.T2D.subc$pvalue,3))),"",
               as.character(ifelse(NAFLD.T2D.iptw$pvalue<0.001, "<0.001", round(NAFLD.T2D.iptw$pvalue,3))),"",
               as.character(ifelse(NAFLD.T2D.crude$pvalue<0.001, "<0.001", round(NAFLD.T2D.curde$pvalue,3)))))
D <-cbind2(A,B)
tabletext <- cbind2(D,C)
NAFLD.T2D.result <- 
    structure(list(
      mean  = c(NA, NA, NAFLD.T2D.greedy$est,NA,NAFLD.T2D.optimal$est,NA,NAFLD.T2D.one_two$est,NA,NAFLD.T2D.full$est,NA,NAFLD.T2D.subc$est,NA,NAFLD.T2D.iptw$est,NA,NAFLD.T2D.crude$est), 
      lower = c(NA, NA, NAFLD.T2D.greedy$lowerCI,NA,NAFLD.T2D.optimal$lowerCI,NA,NAFLD.T2D.one_two$lowerCI,NA,NAFLD.T2D.full$lowerCI,NA,NAFLD.T2D.subc$lowerCI,NA,NAFLD.T2D.iptw$lowerCI,NA,NAFLD.T2D.crude$lowerCI),
      upper = c(NA, NA, NAFLD.T2D.greedy$upperCI,NA,NAFLD.T2D.optimal$upperCI,NA,NAFLD.T2D.one_two$upperCI,NA,NAFLD.T2D.full$upperCI,NA,NAFLD.T2D.subc$upperCI,NA,NAFLD.T2D.iptw$upperCI,NA,NAFLD.T2D.crude$upperCI)),
      .Names = c("mean", "lower", "upper"), 
      row.names = c(NA, -29L), 
      class = "data.frame")

forestplot(tabletext, 
             NAFLD.T2D.result,
             new_page = TRUE,
             col = fpColors(box="royalblue",line="darkblue"),
             hrzl_lines= gpar(col = "#444444"),
             is.summary = c(TRUE, TRUE, rep(FALSE, 29)),
             clip = c(0.5,2.5), zero=1,
             txt_gp=fpTxtGp(label = gpar(cex = 0.8),
                            title = gpar(cex = 1),
                            ticks = gpar(cex = 0.7),
                            xlab = gpar(cex = 0.7)),
             grid = structure(seq(0, 1, by=0.5), 
                              gp = gpar(lty = 0.5, col = "#CCCCFF")),
           xticks=c(0.5,1, 1.5),
           xlab = "Estimate with 95% CI",
           title="Forest Plot of Bootstap LASSO with interaction")

```

# Bootstrap with feature sampling LASSO

```{r}
###############################################################
############# Bootstrap with feature sampling LASSO ###########
###############################################################

newvariables.bootstrap.sampling<-c("Glycated_haemoglobin__HbA1c_", "Systolic_Blood_Pressure","Waist_circumference")
ps.formula <- as.formula((paste("T2D ~",paste(newvariables.bootstrap.sampling,collapse = "+"))))
set.seed(1234)
param<-matchit(ps.formula,data = omitNAFLD)
omitNAFLD$param_ps<-param$distance
ggplot(data = omitNAFLD,aes(param_ps,fill=factor(T2D)))+
  geom_histogram(binwidth = 0.005,alpha = 0.5,position="identity")
logitPS<-sd(-log(1/omitNAFLD$param_ps-1))
```
## CCA
```{r}
################################
############# CCA ##############
################################
set.seed(1234)
## Greedy matching
greedy<-matchit(ps.formula,data=omitNAFLD,
                distance="logit",
                caliper=0.1*sd(logitPS),
                method="nearest")
greedy

set.seed(1234)
## Optimal matching
optimal <- matchit(ps.formula,data= omitNAFLD,
                   distance="logit",
                   method = "optimal")
optimal

set.seed(1234)
## 1:2 matching
one_two <- matchit(ps.formula,data=omitNAFLD,
                   distance="logit",
                   caliper=0.1*sd(logitPS),
                   method = "nearest", ratio = 2)
one_two

set.seed(1234)
## Full matching
full <- matchit(ps.formula,data=omitNAFLD,
                distance="logit",
                caliper=0.1*sd(logitPS),
                method = "full")
full

## Subclassification
omitNAFLD <- omitNAFLD %>% mutate(subclass = ntile(param_ps, 5))
set.seed(1234)
## Subclassification with full matching
subc <- matchit(ps.formula, data = omitNAFLD,
                method = "subclass",
                subclass = 5)
subc

plot(subc, type = "jitter")

### Weighting
set.seed(1234)
## IPTW with stabilization
omitNAFLD$iptw<- ifelse(omitNAFLD$T2D == 1, (mean(omitNAFLD$param_ps))/omitNAFLD$param_ps, 
                        (mean(1-omitNAFLD$param_ps))/(1-omitNAFLD$param_ps))
iptw <- dx.wts(omitNAFLD$iptw, data = as.data.frame(omitNAFLD),treat.var="T2D",estimand = "ATT")

# NAFLD_status~T2D
formula1<-as.formula((paste("NAFLD_status","~ T2D+ ",paste(newvariables.bootstrap.sampling,collapse = "+"))))

set.seed(1234)
## Greedy matching
matched_greedy <- match.data(greedy,subclass = "block")
glm_NAFLD_greedy <- glm(formula1,
                        data = matched_greedy,
                        family = binomial)
summary_greedy <- summary(glm_NAFLD_greedy)
exp(coef(glm_NAFLD_greedy))

set.seed(1234)
## Optimal matching
matched_optimal <- match.data(optimal,subclass = "block")
glm_NAFLD_optimal <- glm(formula1,
                         data = matched_optimal,
                         family = binomial)
summary_optimal <- summary(glm_NAFLD_optimal)
exp(coef(glm_NAFLD_optimal))

set.seed(1234)
## 1:2 matching
matched_one_two <- match.data(one_two,subclass = "block")
glm_NAFLD_one_two <- glm(formula1, 
                         data = matched_one_two,
                         family = binomial)
summary_one_two <- summary(glm_NAFLD_one_two)
exp(coef(glm_NAFLD_one_two))

set.seed(1234)
## Full matching
matched_full <- match.data(full,subclass = "block")
glm_NAFLD_full <- glm(formula1,
                      data = matched_full,
                      family = binomial, weights = weights)
summary_full <-summary(glm_NAFLD_full)
exp(coef(glm_NAFLD_full))

set.seed(1234)
## Subclassification with full matching
subced <- match.data(subc,subclass = "block")
design <- svydesign(id = ~1, strata = ~subclass, weights = ~weights, nested = TRUE, data = subced)
svyglm_NAFLD_subc <- svyglm(formula1, design = design, family = binomial)
summary_subc <- summary(svyglm_NAFLD_subc)
exp(coef(svyglm_NAFLD_subc))

set.seed(1234)
## Weighting by IPTW with stabilization
glm_NAFLD_iptw <- glm(formula1,
                      data = omitNAFLD,
                      weights = iptw,
                      family = binomial)
summary_iptw <-summary(glm_NAFLD_iptw)
exp(coef(glm_NAFLD_iptw))

NAFLD.T2D.HR.est<-c()
NAFLD.T2D.logHR.est<-c()
NAFLD.T2D.se<-c()
NAFLD.T2D.pvalue<-c()
NAFLD.T2D.lowerCI<-c()
NAFLD.T2D.upperCI<-c()

NAFLD.T2D.HR.est[1] <-exp(summary_greedy$coefficients[2,1])
NAFLD.T2D.logHR.est[1]<-summary_greedy$coefficients[2,1]
NAFLD.T2D.se[1]<-summary_greedy$coefficients[2,2]
NAFLD.T2D.pvalue[1]<-summary_greedy$coefficients[2,4]
NAFLD.T2D.lowerCI[1]<- exp(summary_greedy$coefficients[2,1]-1.96*summary_greedy$coefficients[2,2])
NAFLD.T2D.upperCI[1]<- exp(summary_greedy$coefficients[2,1]+1.96*summary_greedy$coefficients[2,2])

NAFLD.T2D.HR.est[2] <-exp(summary_optimal$coefficients[2,1])
NAFLD.T2D.logHR.est[2]<-summary_optimal$coefficients[2,1]
NAFLD.T2D.se[2]<-summary_optimal$coefficients[2,2]
NAFLD.T2D.pvalue[2]<-summary_optimal$coefficients[2,4]
NAFLD.T2D.lowerCI[2]<- exp(summary_optimal$coefficients[2,1]-1.96*summary_optimal$coefficients[2,2])
NAFLD.T2D.upperCI[2]<- exp(summary_optimal$coefficients[2,1]+1.96*summary_optimal$coefficients[2,2])

NAFLD.T2D.HR.est[3] <-exp(summary_one_two$coefficients[2,1])
NAFLD.T2D.logHR.est[3]<-summary_one_two$coefficients[2,1]
NAFLD.T2D.se[3]<-summary_one_two$coefficients[2,2]
NAFLD.T2D.pvalue[3]<-summary_one_two$coefficients[2,4]
NAFLD.T2D.lowerCI[3]<- exp(summary_one_two$coefficients[2,1]-1.96*summary_one_two$coefficients[2,2])
NAFLD.T2D.upperCI[3]<- exp(summary_one_two$coefficients[2,1]+1.96*summary_one_two$coefficients[2,2])

NAFLD.T2D.HR.est[4] <-exp(summary_full$coefficients[2,1])
NAFLD.T2D.logHR.est[4]<-summary_full$coefficients[2,1]
NAFLD.T2D.se[4]<-summary_full$coefficients[2,2]
NAFLD.T2D.pvalue[4]<-summary_full$coefficients[2,4]
NAFLD.T2D.lowerCI[4]<- exp(summary_full$coefficients[2,1]-1.96*summary_full$coefficients[2,2])
NAFLD.T2D.upperCI[4]<- exp(summary_full$coefficients[2,1]+1.96*summary_full$coefficients[2,2])

NAFLD.T2D.HR.est[5] <-exp(summary_subc$coefficients[2,1])
NAFLD.T2D.logHR.est[5]<-summary_subc$coefficients[2,1]
NAFLD.T2D.se[5]<-summary_subc$coefficients[2,2]
NAFLD.T2D.pvalue[5]<-summary_subc$coefficients[2,4]
NAFLD.T2D.lowerCI[5]<- exp(summary_subc$coefficients[2,1]-1.96*summary_subc$coefficients[2,2])
NAFLD.T2D.upperCI[5]<- exp(summary_subc$coefficients[2,1]+1.96*summary_subc$coefficients[2,2])

NAFLD.T2D.HR.est[6] <-exp(summary_iptw$coefficients[2,1])
NAFLD.T2D.logHR.est[6]<-summary_iptw$coefficients[2,1]
NAFLD.T2D.se[6]<-summary_iptw$coefficients[2,2]
NAFLD.T2D.pvalue[6]<-summary_iptw$coefficients[2,4]
NAFLD.T2D.lowerCI[6]<- exp(summary_iptw$coefficients[2,1]-1.96*summary_iptw$coefficients[2,2])
NAFLD.T2D.upperCI[6]<- exp(summary_iptw$coefficients[2,1]+1.96*summary_iptw$coefficients[2,2])

NAFLD.T2D.HR.est[7] <-exp(summary_glm$coefficients[2,1])
NAFLD.T2D.logHR.est[7]<-summary_glm$coefficients[2,1]
NAFLD.T2D.se[7]<-summary_glm$coefficients[2,2]
NAFLD.T2D.pvalue[7]<-summary_glm$coefficients[2,4]
NAFLD.T2D.lowerCI[7]<- exp(summary_glm$coefficients[2,1]-1.96*summary_glm$coefficients[2,2])
NAFLD.T2D.upperCI[7]<- exp(summary_glm$coefficients[2,1]+1.96*summary_glm$coefficients[2,2])

NAFLDoutcome.T2D.result <- 
  structure(list(
    mean  = c(NA, NA, NAFLD.T2D.HR.est), 
    lower = c(NA, NA, NAFLD.T2D.lowerCI),
    upper = c(NA, NA, NAFLD.T2D.upperCI)),
    .Names = c("mean", "lower", "upper"), 
    row.names = c(NA, -8L), 
    class = "data.frame")

A <- cbind2(c("","Method","Greedy Matching","Optimal Matching","1:2 Matching",
              "Full Matching","Stratification with 5 groups", "IPTW","Crude"),
                 c("","Effect", as.character(round(NAFLD.T2D.HR.est,3))))
B<- cbind2(c("","SE", as.character(round(NAFLD.T2D.se,3))),
           c("","p-value", ifelse(NAFLD.T2D.pvalue<0.001, "<0.001", round(NAFLD.T2D.pvalue,3))))
tabletext <- cbind2(A ,B)

forestplot(tabletext, 
           NAFLDoutcome.T2D.result,new_page = TRUE,
           col = fpColors(box="royalblue",line="darkblue"),
           xlab = "Estimate with 95% CI",
           hrzl_lines= gpar(col = "#444444"),
           is.summary = c(TRUE, TRUE, rep(FALSE, 10)),
           clip = c(0.5,5.5), zero=0.5,
           txt_gp=fpTxtGp(label = gpar(cex = 0.8),
                          title = gpar(cex = 1),
                          ticks = gpar(cex = 0.7),
                          xlab = gpar(cex = 0.7)),
           grid = structure(seq(0.5, 5.5, by=0.25), 
                            gp = gpar(lty = 2, col = "#CCCCFF")),
           xticks=c(0.5,1, 1.5))
grid.text("Exposure of T2D on NAFLD", .5, 0.98, gp=gpar(fontface="bold"))
```
## MIte
```{r}
################################
############# MI ###############
################################



################################
############MIte################
################################
set.seed(1234)
## Greedy matching
greedy.matched.MIte.datasets <- matchthem(ps.formula, mi.data,
                                          approach = 'within',
                                          method = 'nearest',
                                          caliper = 0.05)
greedy.matched.MIte.datasets

set.seed(1234)
## Optimal matching
optimal.matched.MIte.datasets <- matchthem(ps.formula, mi.data,
                                           approach = 'within',
                                           method = 'optimal',
                                           caliper = 0.05)
optimal.matched.MIte.datasets

set.seed(1234)
## 1:2 matching
one_two.matched.MIte.datasets <- matchthem(ps.formula, mi.data,
                                           approach = 'within',
                                           method = 'nearest',
                                           caliper = 0.05, ratio = 2)
one_two.matched.MIte.datasets 

set.seed(1234)
## Full matching
full.matched.MIte.datasets <- matchthem(ps.formula,mi.data,
                                        approach = 'within',
                                        caliper = 0.05,
                                        method = "full")
full.matched.MIte.datasets

set.seed(1234)
## Subclassification with full matching
subc.MIte.datasets <- matchthem(ps.formula, mi.data,
                                approach = 'within',
                                method = "subclass",
                                subclass = 5)
subc.MIte.datasets
plot(subc.MIte.datasets, type = "jitter")

set.seed(1234)
# IPTW
weighted.MIte.datasets <- weightthem(ps.formula, mi.data,
                                     approach = 'within', 
                                     method = 'ps', estimand = 'ATM')
weighted.MIte.datasets

library(cobalt)
bal.tab(greedy.matched.MIte.datasets, abs = TRUE)
bal.tab(optimal.matched.MIte.datasets, abs = TRUE)
bal.tab(one_two.matched.MIte.datasets, abs = TRUE)
bal.tab(full.matched.MIte.datasets, abs = TRUE)
bal.tab(subc.MIte.datasets, abs = TRUE)
bal.tab(weighted.MIte.datasets, abs = TRUE)

library(survey)
formula1<-as.formula((paste("NAFLD_status","~ T2D+ ",paste(newvariables.bootstrap.sampling,collapse = "+"))))
set.seed(1234)
greedy.matched.MIte.models <- with(data = greedy.matched.MIte.datasets,
                                   expr = svyglm(formula1, family = quasibinomial))
greedy.matched.MIte.results <- pool(greedy.matched.MIte.models)
summary_MIte_greedy <- summary(greedy.matched.MIte.results, conf.int = TRUE)

set.seed(1234)
optimal.matched.MIte.models <- with(data = optimal.matched.MIte.datasets,
                                    expr = svyglm(formula1, family =quasibinomial))
optimal.matched.MIte.results <- pool(optimal.matched.MIte.models)
summary_MIte_optimal <-summary(optimal.matched.MIte.results, conf.int = TRUE)

set.seed(1234)
one_two.matched.MIte.models <- with(data = one_two.matched.MIte.datasets,
                                    expr = svyglm(formula1, family = quasibinomial))
one_two.matched.MIte.results <- pool(one_two.matched.MIte.models)
summary_MIte_one_two <- summary(one_two.matched.MIte.results, conf.int = TRUE)

set.seed(1234)
full.matched.MIte.models <- with(data = full.matched.MIte.datasets,
                                 expr = svyglm(formula1, family = quasibinomial))
full.matched.MIte.results <- pool(full.matched.MIte.models)
summary_MIte_full <- summary(full.matched.MIte.results, conf.int = TRUE)

set.seed(1234)
subc.MIte.models <- with(data = subc.MIte.datasets,
                         expr = svyglm(formula1, family = quasibinomial))
subc.MIte.results <- pool(subc.MIte.models)
summary_MIte_subc <-summary(subc.MIte.results, conf.int = TRUE)

# IPTW
set.seed(1234)
weighted.MIte.models <- with(data = weighted.MIte.datasets, expr = svyglm(formula1, family = quasibinomial))
weighted.MIte.results <- pool(weighted.MIte.models)
summary_MIte_iptw <-summary(weighted.MIte.results, conf.int = TRUE)

NAFLD.T2D.MIte.HR.est<-c()
NAFLD.T2D.MIte.logHR.est<-c()
NAFLD.T2D.MIte.se<-c()
NAFLD.T2D.MIte.pvalue<-c()
NAFLD.T2D.MIte.lowerCI<-c()
NAFLD.T2D.MIte.upperCI<-c()

NAFLD.T2D.MIte.HR.est[1] <-exp(summary_MIte_greedy[2,2])
NAFLD.T2D.MIte.logHR.est[1]<-summary_MIte_greedy[2,2]
NAFLD.T2D.MIte.se[1]<-summary_MIte_greedy[2,3]
NAFLD.T2D.MIte.pvalue[1]<-summary_MIte_greedy[2,6]
NAFLD.T2D.MIte.lowerCI[1]<- exp(summary_MIte_greedy[2,7])
NAFLD.T2D.MIte.upperCI[1]<- exp(summary_MIte_greedy[2,8])

NAFLD.T2D.MIte.HR.est[2] <-exp(summary_MIte_optimal[2,2])
NAFLD.T2D.MIte.logHR.est[2]<-summary_MIte_optimal[2,2]
NAFLD.T2D.MIte.se[2]<-summary_MIte_optimal[2,3]
NAFLD.T2D.MIte.pvalue[2]<-summary_MIte_optimal[2,6]
NAFLD.T2D.MIte.lowerCI[2]<- exp(summary_MIte_optimal[2,7])
NAFLD.T2D.MIte.upperCI[2]<- exp(summary_MIte_optimal[2,8])

NAFLD.T2D.MIte.HR.est[3] <-exp(summary_MIte_one_two[2,2])
NAFLD.T2D.MIte.logHR.est[3]<-summary_MIte_one_two[2,2]
NAFLD.T2D.MIte.se[3]<-summary_MIte_one_two[2,3]
NAFLD.T2D.MIte.pvalue[3]<-summary_MIte_one_two[2,6]
NAFLD.T2D.MIte.lowerCI[3]<- exp(summary_MIte_one_two[2,7])
NAFLD.T2D.MIte.upperCI[3]<- exp(summary_MIte_one_two[2,8])

NAFLD.T2D.MIte.HR.est[4] <-exp(summary_MIte_full[2,2])
NAFLD.T2D.MIte.logHR.est[4]<-summary_MIte_full[2,2]
NAFLD.T2D.MIte.se[4]<-summary_MIte_full[2,3]
NAFLD.T2D.MIte.pvalue[4]<-summary_MIte_full[2,6]
NAFLD.T2D.MIte.lowerCI[4]<- exp(summary_MIte_full[2,7])
NAFLD.T2D.MIte.upperCI[4]<- exp(summary_MIte_full[2,8])

NAFLD.T2D.MIte.HR.est[5] <-exp(summary_MIte_subc[2,2])
NAFLD.T2D.MIte.logHR.est[5]<-summary_MIte_subc[2,2]
NAFLD.T2D.MIte.se[5]<-summary_MIte_subc[2,3]
NAFLD.T2D.MIte.pvalue[5]<-summary_MIte_subc[2,6]
NAFLD.T2D.MIte.lowerCI[5]<- exp(summary_MIte_subc[2,7])
NAFLD.T2D.MIte.upperCI[5]<- exp(summary_MIte_subc[2,8])

NAFLD.T2D.MIte.HR.est[6] <-exp(summary_MIte_iptw[2,2])
NAFLD.T2D.MIte.logHR.est[6]<-summary_MIte_iptw[2,2]
NAFLD.T2D.MIte.se[6]<-summary_MIte_iptw[2,3]
NAFLD.T2D.MIte.pvalue[6]<-summary_MIte_iptw[2,6]
NAFLD.T2D.MIte.lowerCI[6]<- exp(summary_MIte_iptw[2,7])
NAFLD.T2D.MIte.upperCI[6]<- exp(summary_MIte_iptw[2,8])

NAFLD.T2D.MIte.HR.est[7] <-exp(summary_glm_mi$coefficients[2,1])
NAFLD.T2D.MIte.logHR.est[7]<-summary_glm_mi$coefficients[2,1]
NAFLD.T2D.MIte.se[7]<-summary_glm_mi$coefficients[2,2]
NAFLD.T2D.MIte.pvalue[7]<-summary_glm_mi$coefficients[2,4]
NAFLD.T2D.MIte.lowerCI[7]<- exp(summary_glm_mi$coefficients[2,1]-1.96*summary_glm_mi$coefficients[2,2])
NAFLD.T2D.MIte.upperCI[7]<- exp(summary_glm_mi$coefficients[2,1]+1.96*summary_glm_mi$coefficients[2,2])

NAFLDoutcome.T2D.MIte.result <- 
  structure(list(
    mean  = c(NA, NA, NAFLD.T2D.MIte.HR.est), 
    lower = c(NA, NA, NAFLD.T2D.MIte.lowerCI),
    upper = c(NA, NA, NAFLD.T2D.MIte.upperCI)),
    .Names = c("mean", "lower", "upper"), 
    row.names = c(NA, -8L), 
    class = "data.frame")

A <- cbind2(c("","Method","Greedy Matching","Optimal Matching","1:2 Matching",
              "Full Matching","Stratification with 5 groups", "IPTW","Crude"),
            c("","Effect", as.character(round(NAFLD.T2D.MIte.HR.est,3))))
B<- cbind2(c("","SE", as.character(round(NAFLD.T2D.MIte.se,3))),
           c("","p-value", ifelse(NAFLD.T2D.MIte.pvalue<0.001, "<0.001", round(NAFLD.T2D.MIte.pvalue,3))))
tabletext <- cbind2(A ,B)

forestplot(tabletext, 
           NAFLDoutcome.T2D.MIte.result,new_page = TRUE,
           col = fpColors(box="royalblue",line="darkblue"),
           xlab = "Estimate with 95% CI",
           hrzl_lines= gpar(col = "#444444"),
           is.summary = c(TRUE, TRUE, rep(FALSE, 10)),
           clip = c(0,5.5), zero=1,
           txt_gp=fpTxtGp(label = gpar(cex = 0.8),
                          title = gpar(cex = 1),
                          ticks = gpar(cex = 0.7),
                          xlab = gpar(cex = 0.7)),
           grid = structure(seq(1,5, by=0.25), 
                            gp = gpar(lty = 2, col = "#CCCCFF")),
           xticks=c(0.5,1, 1.5))
grid.text("Exposure of T2D on NAFLD by MIte", .5, 0.98, gp=gpar(fontface="bold"))
```
## MIps
```{r}
################################
############MIps################
################################
set.seed(1234)
## Greedy matching
greedy.matched.MIps.across.datasets <- matchthem(ps.formula, mi.data,
                                                 approach = 'across',
                                                 method = 'nearest',
                                                 caliper = 0.05)
greedy.matched.MIps.across.datasets

set.seed(1234)
## Optimal matching
optimal.matched.MIps.across.datasets <- matchthem(ps.formula, mi.data,
                                                  approach = 'across',
                                                  method = 'optimal',
                                                  caliper = 0.05)
optimal.matched.MIps.across.datasets

set.seed(1234)
## 1:2 matching
one_two.matched.MIps.across.datasets <- matchthem(ps.formula, mi.data,
                                                  approach = 'across',
                                                  method = 'nearest',
                                                  caliper = 0.05, ratio = 2)
one_two.matched.MIps.across.datasets

set.seed(1234)
## Full matching
full.matched.MIps.across.datasets <- matchthem(ps.formula,mi.data,
                                               approach = 'across',
                                               caliper = 0.05,
                                               method = "full")
full.matched.MIps.across.datasets

set.seed(1234)
## Subclassification with full matching
subc.MIps.across.datasets <- matchthem(ps.formula, mi.data,
                                       approach = 'across',
                                       method = "subclass",
                                       subclass = 5)
subc.MIps.across.datasets
plot(subc.MIps.across.datasets, type = "jitter")

set.seed(1234)
# IPTW
weighted.across.datasets <- weightthem(ps.formula, mi.data,
                                       approach = 'across', 
                                       method = 'ps', estimand = 'ATM')
weighted.across.datasets

bal.tab(greedy.matched.MIps.across.datasets, abs = TRUE)
bal.tab(optimal.matched.MIps.across.datasets, abs = TRUE)
bal.tab(one_two.matched.MIps.across.datasets, abs = TRUE)
bal.tab(full.matched.MIps.across.datasets, abs = TRUE)
bal.tab(subc.MIps.across.datasets, abs = TRUE)
bal.tab(weighted.across.datasets, abs = TRUE)

formula1<-as.formula((paste("NAFLD_status","~ T2D+ ",paste(newvariables.bootstrap.sampling,collapse = "+"))))

set.seed(1234)
greedy.matched.MIps.across.models <- with(data = greedy.matched.MIps.across.datasets,
                                          expr = svyglm(formula1, family = quasibinomial))
greedy.matched.MIps.across.results <- pool(greedy.matched.MIps.across.models)
summary_MIps_greedy <- summary(greedy.matched.MIps.across.results, conf.int = TRUE)

set.seed(1234)
optimal.matched.MIps.across.models <- with(data = optimal.matched.MIps.across.datasets,
                                           expr = svyglm(formula1, family =quasibinomial))
optimal.matched.MIps.across.results <- pool(optimal.matched.MIps.across.models)
summary_MIps_optimal <-summary(optimal.matched.MIps.across.results, conf.int = TRUE)

set.seed(1234)
one_two.matched.MIps.across.models <- with(data = one_two.matched.MIps.across.datasets,
                                           expr = svyglm(formula1, family = quasibinomial))
one_two.matched.MIps.across.results <- pool(one_two.matched.MIps.across.models)
summary_MIps_one_two <- summary(one_two.matched.MIps.across.results, conf.int = TRUE)

set.seed(1234)
full.matched.MIps.across.models <- with(data = full.matched.MIps.across.datasets,
                                        expr = svyglm(formula1, family = quasibinomial))
full.matched.MIps.across.results <- pool(full.matched.MIps.across.models)
summary_MIps_full <- summary(full.matched.MIps.across.results, conf.int = TRUE)

set.seed(1234)
subc.MIps.across.models <- with(data = subc.MIps.across.datasets,
                                expr = svyglm(formula1, family = quasibinomial))
subc.MIps.across.results <- pool(subc.MIps.across.models)
summary_MIps_subc <-summary(subc.MIps.across.results, conf.int = TRUE)

# IPTW
set.seed(1234)
weighted.across.models <- with(data = weighted.across.datasets, expr = svyglm(formula1, family = quasibinomial))
weighted.across.results <- pool(weighted.across.models)
summary_MIps_iptw <-summary(weighted.across.results, conf.int = TRUE)

NAFLD.T2D.MIps.HR.est<-c()
NAFLD.T2D.MIps.logHR.est<-c()
NAFLD.T2D.MIps.se<-c()
NAFLD.T2D.MIps.pvalue<-c()
NAFLD.T2D.MIps.lowerCI<-c()
NAFLD.T2D.MIps.upperCI<-c()

NAFLD.T2D.MIps.HR.est[1] <-exp(summary_MIps_greedy[2,2])
NAFLD.T2D.MIps.logHR.est[1]<-summary_MIps_greedy[2,2]
NAFLD.T2D.MIps.se[1]<-summary_MIps_greedy[2,3]
NAFLD.T2D.MIps.pvalue[1]<-summary_MIps_greedy[2,6]
NAFLD.T2D.MIps.lowerCI[1]<- exp(summary_MIps_greedy[2,7])
NAFLD.T2D.MIps.upperCI[1]<- exp(summary_MIps_greedy[2,8])

NAFLD.T2D.MIps.HR.est[2] <-exp(summary_MIps_optimal[2,2])
NAFLD.T2D.MIps.logHR.est[2]<-summary_MIps_optimal[2,2]
NAFLD.T2D.MIps.se[2]<-summary_MIps_optimal[2,3]
NAFLD.T2D.MIps.pvalue[2]<-summary_MIps_optimal[2,6]
NAFLD.T2D.MIps.lowerCI[2]<- exp(summary_MIps_optimal[2,7])
NAFLD.T2D.MIps.upperCI[2]<- exp(summary_MIps_optimal[2,8])

NAFLD.T2D.MIps.HR.est[3] <-exp(summary_MIps_one_two[2,2])
NAFLD.T2D.MIps.logHR.est[3]<-summary_MIps_one_two[2,2]
NAFLD.T2D.MIps.se[3]<-summary_MIps_one_two[2,3]
NAFLD.T2D.MIps.pvalue[3]<-summary_MIps_one_two[2,6]
NAFLD.T2D.MIps.lowerCI[3]<- exp(summary_MIps_one_two[2,7])
NAFLD.T2D.MIps.upperCI[3]<- exp(summary_MIps_one_two[2,8])

NAFLD.T2D.MIps.HR.est[4] <-exp(summary_MIps_full[2,2])
NAFLD.T2D.MIps.logHR.est[4]<-summary_MIps_full[2,2]
NAFLD.T2D.MIps.se[4]<-summary_MIps_full[2,3]
NAFLD.T2D.MIps.pvalue[4]<-summary_MIps_full[2,6]
NAFLD.T2D.MIps.lowerCI[4]<- exp(summary_MIps_full[2,7])
NAFLD.T2D.MIps.upperCI[4]<- exp(summary_MIps_full[2,8])

NAFLD.T2D.MIps.HR.est[5] <-exp(summary_MIps_subc[2,2])
NAFLD.T2D.MIps.logHR.est[5]<-summary_MIps_subc[2,2]
NAFLD.T2D.MIps.se[5]<-summary_MIps_subc[2,3]
NAFLD.T2D.MIps.pvalue[5]<-summary_MIps_subc[2,6]
NAFLD.T2D.MIps.lowerCI[5]<- exp(summary_MIps_subc[2,7])
NAFLD.T2D.MIps.upperCI[5]<- exp(summary_MIps_subc[2,8])

NAFLD.T2D.MIps.HR.est[6] <-exp(summary_MIps_iptw[2,2])
NAFLD.T2D.MIps.logHR.est[6]<-summary_MIps_iptw[2,2]
NAFLD.T2D.MIps.se[6]<-summary_MIps_iptw[2,3]
NAFLD.T2D.MIps.pvalue[6]<-summary_MIps_iptw[2,6]
NAFLD.T2D.MIps.lowerCI[6]<- exp(summary_MIps_iptw[2,7])
NAFLD.T2D.MIps.upperCI[6]<- exp(summary_MIps_iptw[2,8])

NAFLD.T2D.MIps.HR.est[7] <-exp(summary_glm_mi$coefficients[2,1])
NAFLD.T2D.MIps.logHR.est[7]<-summary_glm_mi$coefficients[2,1]
NAFLD.T2D.MIps.se[7]<-summary_glm_mi$coefficients[2,2]
NAFLD.T2D.MIps.pvalue[7]<-summary_glm_mi$coefficients[2,4]
NAFLD.T2D.MIps.lowerCI[7]<- exp(summary_glm_mi$coefficients[2,1]-1.96*summary_glm_mi$coefficients[2,2])
NAFLD.T2D.MIps.upperCI[7]<- exp(summary_glm_mi$coefficients[2,1]+1.96*summary_glm_mi$coefficients[2,2])

NAFLDoutcome.T2D.MIps.result <- 
  structure(list(
    mean  = c(NA, NA, NAFLD.T2D.MIps.HR.est), 
    lower = c(NA, NA, NAFLD.T2D.MIps.lowerCI),
    upper = c(NA, NA, NAFLD.T2D.MIps.upperCI)),
    .Names = c("mean", "lower", "upper"), 
    row.names = c(NA, -9L), 
    class = "data.frame")


A <- cbind2(c("","Method","Greedy Matching","Optimal Matching","1:2 Matching",
              "Full Matching","Stratification with 5 groups", "IPTW","Crude"),
               c("","Effect", as.character(round(NAFLD.T2D.MIps.HR.est,3))))
B<- cbind2(c("","SE", as.character(round(NAFLD.T2D.MIps.se,3))),
           c("","p-value", ifelse(NAFLD.T2D.MIps.pvalue<0.001, "<0.001", 
                                          round(NAFLD.T2D.MIps.pvalue,3))))
tabletext <- cbind2(A ,B)

forestplot(tabletext, 
           NAFLDoutcome.T2D.MIps.result,new_page = TRUE,
           col = fpColors(box="royalblue",line="darkblue"),
           xlab = "Estimate with 95% CI",
           hrzl_lines= gpar(col = "#444444"),
           is.summary = c(TRUE, TRUE, rep(FALSE, 10)),
           clip = c(0.5,5.5), zero=1,
           txt_gp=fpTxtGp(label = gpar(cex = 0.8),
                          title = gpar(cex = 1),
                          ticks = gpar(cex = 0.8),
                          xlab = gpar(cex = 0.7)),
           grid = structure(seq(1, 5.5, by=0.25), 
                            gp = gpar(lty = 2, col = "#CCCCFF")),
           xticks=c(0.5,1, 1.5))
grid.text("Exposure of T2D on NAFLD by MIps", .5, 0.98, gp=gpar(fontface="bold"))
```

```{r}
NAFLD.T2D.bootstrap.sampling<-data.frame(MLapproach=rep("Bootstap with feature sampling LASSO",21),MIapproach=c(rep("CCA",7),rep("MIte",7),rep("MIps",7)),
                      PSmethod=c(rep(c("Greedy Matching","Optimal Matching","1:2 Matching",
                                       "Full Matching","Stratification with 5 groups", "IPTW","Crude"),3)),
                      est=c(round(NAFLD.T2D.HR.est,3),round(NAFLD.T2D.MIte.HR.est,3),
                            round(NAFLD.T2D.MIps.HR.est,3)),
                      log.est=c(round(NAFLD.T2D.logHR.est,3),round(NAFLD.T2D.MIte.logHR.est,3),round(NAFLD.T2D.MIps.logHR.est,3)),
                      se=c(round(NAFLD.T2D.se,3),round(NAFLD.T2D.MIte.se,3),round(NAFLD.T2D.MIps.se,3)),
                      pvalue=c(round(NAFLD.T2D.pvalue,3),round(NAFLD.T2D.MIte.pvalue,3),round(NAFLD.T2D.MIps.pvalue,3)),
                      lowerCI=c(round(NAFLD.T2D.lowerCI,3),round(NAFLD.T2D.MIte.lowerCI,3),round(NAFLD.T2D.MIps.lowerCI,3)),
                      upperCI=c(round(NAFLD.T2D.upperCI,3),round(NAFLD.T2D.MIte.upperCI,3),round(NAFLD.T2D.MIps.upperCI,3)))

NAFLD.T2D.greedy<-subset(NAFLD.T2D.bootstrap.sampling,PSmethod=="Greedy Matching")
NAFLD.T2D.optimal<-subset(NAFLD.T2D.bootstrap.sampling,PSmethod=="Optimal Matching")
NAFLD.T2D.one_two<-subset(NAFLD.T2D.bootstrap.sampling,PSmethod=="1:2 Matching")
NAFLD.T2D.full<-subset(NAFLD.T2D.bootstrap.sampling,PSmethod=="Full Matching")
NAFLD.T2D.subc<-subset(NAFLD.T2D.bootstrap.sampling,PSmethod=="Stratification with 5 groups")
NAFLD.T2D.iptw<-subset(NAFLD.T2D.bootstrap.sampling,PSmethod=="IPTW")
NAFLD.T2D.crude<-subset(NAFLD.T2D.bootstrap.sampling,PSmethod=="Crude")

Forstplot<-function(method,title){
  
  A <- cbind2(c("","MI Approach","CCA","MIte","MIps"), 
                     c("","Effect", as.character(method$est)))

  B <-cbind2(c("","SE", as.character(method$se)),
                     c("","p-value", ifelse(method$pvalue<0.001, "<0.001", method$pvalue)))
  
  tabletext <- cbind2(A,B)
  NAFLD.T2D.result <- 
    structure(list(
      mean  = c(NA, NA, method$est), 
      lower = c(NA, NA, method$lowerCI),
      upper = c(NA, NA, method$upperCI)),
      .Names = c("mean", "lower", "upper"), 
      row.names = c(NA, -5L), 
      class = "data.frame")
  
  forestplot(tabletext, 
             NAFLD.T2D.result,
             new_page = TRUE,
             xlab = "Estimate with 95% CI",
             col = fpColors(box="royalblue",line="darkblue"),
             hrzl_lines= gpar(col = "#444444"),
             is.summary = c(TRUE, TRUE, rep(FALSE, 18)),
             clip = c(0.5,5.5), zero=1,
             txt_gp=fpTxtGp(label = gpar(cex = 0.8),
                            title = gpar(cex = 1),
                            ticks = gpar(cex = 0.7),
                            xlab = gpar(cex = 0.7)),
             grid = structure(seq(1, 5.5, by=0.5), 
                              gp = gpar(lty = 2, col = "#CCCCFF")),
             xticks=c(0.5,1, 1.5),
             title=title)
}

Forstplot(NAFLD.T2D.greedy,"Exposure of T2D on of Greedy Matching")
Forstplot(NAFLD.T2D.optimal,"Exposure of T2D on of Optimal Matching")
Forstplot(NAFLD.T2D.one_two,"Exposure of T2D on of 1:2 Matching")
Forstplot(NAFLD.T2D.full,"Exposure of T2D on of Full Matching")
Forstplot(NAFLD.T2D.subc,"Exposure of T2D on of Stratification with 5 groups")
Forstplot(NAFLD.T2D.iptw,"Exposure of T2D on of IPTW ")
```

```{r}

A<-c("","PS Method","Greedy Matching","","","","Optimal Matching","","","","1:2 Matching","","","",
                                       "Full Matching","","","","Stratification with 5 groups", "","","","IPTW","","","","Crude","","")
  
B <- cbind2(c("","MI Approach",rep(c("CCA","MIte","MIps"," "),6),"CCA","MIte","MIps"), 
                     c("","Effect", NAFLD.T2D.greedy$est,"",NAFLD.T2D.optimal$est,"",NAFLD.T2D.one_two$est,"",NAFLD.T2D.full$est,"",NAFLD.T2D.subc$est,"",NAFLD.T2D.iptw$est,"",NAFLD.T2D.crude$est))
  
C <-cbind2(c("","SE", as.character(NAFLD.T2D.greedy$se),"",as.character(NAFLD.T2D.optimal$se),"",
               as.character(NAFLD.T2D.one_two$se),"",as.character(NAFLD.T2D.full$se),"",
               as.character(NAFLD.T2D.subc$se),"",as.character(NAFLD.T2D.iptw$se),"",
               as.character(NAFLD.T2D.crude$se)),
             c("","p-value", as.character(ifelse(NAFLD.T2D.greedy$pvalue<0.001, 
                                                 "<0.001",  round(NAFLD.T2D.greedy$pvalue,3))),"",
               as.character(ifelse(NAFLD.T2D.optimal$pvalue<0.001, "<0.001",round(NAFLD.T2D.optimal$pvalue,3))),"",
               as.character(ifelse(NAFLD.T2D.one_two$pvalue<0.001, "<0.001",round(NAFLD.T2D.one_two$pvalue,3))),"",                as.character(ifelse(NAFLD.T2D.full$pvalue<0.001, "<0.001", round(NAFLD.T2D.full$pvalue,3))),"",
               as.character(ifelse(NAFLD.T2D.subc$pvalue<0.001, "<0.001", round(NAFLD.T2D.subc$pvalue,3))),"",
               as.character(ifelse(NAFLD.T2D.iptw$pvalue<0.001, "<0.001", round(NAFLD.T2D.iptw$pvalue,3))),"",
               as.character(ifelse(NAFLD.T2D.crude$pvalue<0.001, "<0.001", round(NAFLD.T2D.curde$pvalue,3)))))
D <-cbind2(A,B)
tabletext <- cbind2(D,C)
NAFLD.T2D.result <- 
    structure(list(
      mean  = c(NA, NA, NAFLD.T2D.greedy$est,NA,NAFLD.T2D.optimal$est,NA,NAFLD.T2D.one_two$est,NA,NAFLD.T2D.full$est,NA,NAFLD.T2D.subc$est,NA,NAFLD.T2D.iptw$est,NA,NAFLD.T2D.crude$est), 
      lower = c(NA, NA, NAFLD.T2D.greedy$lowerCI,NA,NAFLD.T2D.optimal$lowerCI,NA,NAFLD.T2D.one_two$lowerCI,NA,NAFLD.T2D.full$lowerCI,NA,NAFLD.T2D.subc$lowerCI,NA,NAFLD.T2D.iptw$lowerCI,NA,NAFLD.T2D.crude$lowerCI),
      upper = c(NA, NA, NAFLD.T2D.greedy$upperCI,NA,NAFLD.T2D.optimal$upperCI,NA,NAFLD.T2D.one_two$upperCI,NA,NAFLD.T2D.full$upperCI,NA,NAFLD.T2D.subc$upperCI,NA,NAFLD.T2D.iptw$upperCI,NA,NAFLD.T2D.crude$upperCI)),
      .Names = c("mean", "lower", "upper"), 
      row.names = c(NA, -29L), 
      class = "data.frame")

forestplot(tabletext, 
             NAFLD.T2D.result,
             new_page = TRUE,
             col = fpColors(box="royalblue",line="darkblue"),
             hrzl_lines= gpar(col = "#444444"),
             is.summary = c(TRUE, TRUE, rep(FALSE, 29)),
             clip = c(0.5,2.5), zero=1,
             txt_gp=fpTxtGp(label = gpar(cex = 0.8),
                            title = gpar(cex = 1),
                            ticks = gpar(cex = 0.7),
                            xlab = gpar(cex = 0.7)),
             grid = structure(seq(0, 1, by=0.5), 
                              gp = gpar(lty = 0.5, col = "#CCCCFF")),
           xticks=c(0.5,1, 1.5),
           xlab = "Estimate with 95% CI",
           title="Forest Plot of Bootstap with feature sampling LASSO")

```

# Bootstrap with feature sampling LASSO (with interaction)

```{r}
###############################################################
############# Bootstrap with feature sampling LASSO ###########
###################### (with interaction) #####################
###############################################################

newvariables.bootstrap.sampling.interaction<-c("BMIdich:Glycated_haemoglobin__HbA1c_", "BMIdich:LDL","BMIdich:Triglycerides","BMIdich:Waist_circumference", "Glycated_haemoglobin__HbA1c_:HDL_cholesterol", "Glycated_haemoglobin__HbA1c_:LDL","Glycated_haemoglobin__HbA1c_:Sex",                    "Glycated_haemoglobin__HbA1c_:Systolic_Blood_Pressure","Glycated_haemoglobin__HbA1c_:Triglycerides",           "Glycated_haemoglobin__HbA1c_:Waist_circumference", "HDL_cholesterol:LDL",                                "HDL_cholesterol:Systolic_Blood_Pressure","HDL_cholesterol:Triglycerides","LDL:Sex","LDL:Systolic_Blood_Pressure","LDL:Triglycerides", "LDL:Waist_circumference","Sex:Systolic_Blood_Pressure","Sex:Waist_circumference", "Systolic_Blood_Pressure:Triglycerides","Systolic_Blood_Pressure:Waist_circumference", "Triglycerides:Waist_circumference")
ps.formula <- as.formula((paste("T2D ~",paste(newvariables.bootstrap.sampling.interaction,collapse = "+"))))
set.seed(1234)
param<-matchit(ps.formula,data = omitNAFLD)
omitNAFLD$param_ps<-param$distance
ggplot(data = omitNAFLD,aes(param_ps,fill=factor(T2D)))+
  geom_histogram(binwidth = 0.005,alpha = 0.5,position="identity")
logitPS<-sd(-log(1/omitNAFLD$param_ps-1))
```
## CCA
```{r}
################################
############# CCA ##############
################################
## Greedy matching
set.seed(1234)
greedy<-matchit(ps.formula,data=omitNAFLD,
                distance="logit",
                caliper=0.1*sd(logitPS),
                method="nearest")
greedy

set.seed(1234)
## Optimal matching
optimal <- matchit(ps.formula,data= omitNAFLD,
                   distance="logit",
                   method = "optimal")
optimal

set.seed(1234)
## 1:2 matching
one_two <- matchit(ps.formula,data=omitNAFLD,
                   distance="logit",
                   caliper=0.1*sd(logitPS),
                   method = "nearest", ratio = 2)
one_two

set.seed(1234)
## Full matching
full <- matchit(ps.formula,data=omitNAFLD,
                distance="logit",
                caliper=0.1*sd(logitPS),
                method = "full")
full

## Subclassification
omitNAFLD <- omitNAFLD %>% mutate(subclass = ntile(param_ps, 5))

set.seed(1234)
## Subclassification with full matching
subc <- matchit(ps.formula, data = omitNAFLD,
                method = "subclass",
                subclass = 5)
subc

plot(subc, type = "jitter")

### Weighting

## IPTW with stabilization
omitNAFLD$iptw<- ifelse(omitNAFLD$T2D == 1, (mean(omitNAFLD$param_ps))/omitNAFLD$param_ps, 
                        (mean(1-omitNAFLD$param_ps))/(1-omitNAFLD$param_ps))
iptw <- dx.wts(omitNAFLD$iptw, data = as.data.frame(omitNAFLD),treat.var="T2D",estimand = "ATT")

# NAFLD_status~T2D
formula1<-as.formula((paste("NAFLD_status","~ T2D+ ",paste(newvariables.bootstrap.sampling.interaction,collapse = "+"))))

set.seed(1234)
## Greedy matching
matched_greedy <- match.data(greedy,subclass = "block")
glm_NAFLD_greedy <- glm(formula1,
                        data = matched_greedy,
                        family = binomial)
summary_greedy <- summary(glm_NAFLD_greedy)
exp(coef(glm_NAFLD_greedy))

set.seed(1234)
## Optimal matching
matched_optimal <- match.data(optimal,subclass = "block")
glm_NAFLD_optimal <- glm(formula1,
                         data = matched_optimal,
                         family = binomial)
summary_optimal <- summary(glm_NAFLD_optimal)
exp(coef(glm_NAFLD_optimal))

set.seed(1234)
## 1:2 matching
matched_one_two <- match.data(one_two,subclass = "block")
glm_NAFLD_one_two <- glm(formula1, 
                         data = matched_one_two,
                         family = binomial)
summary_one_two <- summary(glm_NAFLD_one_two)
exp(coef(glm_NAFLD_one_two))

set.seed(1234)
## Full matching
matched_full <- match.data(full,subclass = "block")
glm_NAFLD_full <- glm(formula1,
                      data = matched_full,
                      family = binomial, weights = weights)
summary_full <-summary(glm_NAFLD_full)
exp(coef(glm_NAFLD_full))

set.seed(1234)
## Subclassification with full matching
subced <- match.data(subc,subclass = "block")
design <- svydesign(id = ~1, strata = ~subclass, weights = ~weights, nested = TRUE, data = subced)
svyglm_NAFLD_subc <- svyglm(formula1, design = design, family = binomial)
summary_subc <- summary(svyglm_NAFLD_subc)
exp(coef(svyglm_NAFLD_subc))

set.seed(1234)
## Weighting by IPTW with stabilization
glm_NAFLD_iptw <- glm(formula1,
                      data = omitNAFLD,
                      weights = iptw,
                      family = binomial)
summary_iptw <-summary(glm_NAFLD_iptw)
exp(coef(glm_NAFLD_iptw))

NAFLD.T2D.HR.est<-c()
NAFLD.T2D.logHR.est<-c()
NAFLD.T2D.se<-c()
NAFLD.T2D.pvalue<-c()
NAFLD.T2D.lowerCI<-c()
NAFLD.T2D.upperCI<-c()

NAFLD.T2D.HR.est[1] <-exp(summary_greedy$coefficients[2,1])
NAFLD.T2D.logHR.est[1]<-summary_greedy$coefficients[2,1]
NAFLD.T2D.se[1]<-summary_greedy$coefficients[2,2]
NAFLD.T2D.pvalue[1]<-summary_greedy$coefficients[2,4]
NAFLD.T2D.lowerCI[1]<- exp(summary_greedy$coefficients[2,1]-1.96*summary_greedy$coefficients[2,2])
NAFLD.T2D.upperCI[1]<- exp(summary_greedy$coefficients[2,1]+1.96*summary_greedy$coefficients[2,2])

NAFLD.T2D.HR.est[2] <-exp(summary_optimal$coefficients[2,1])
NAFLD.T2D.logHR.est[2]<-summary_optimal$coefficients[2,1]
NAFLD.T2D.se[2]<-summary_optimal$coefficients[2,2]
NAFLD.T2D.pvalue[2]<-summary_optimal$coefficients[2,4]
NAFLD.T2D.lowerCI[2]<- exp(summary_optimal$coefficients[2,1]-1.96*summary_optimal$coefficients[2,2])
NAFLD.T2D.upperCI[2]<- exp(summary_optimal$coefficients[2,1]+1.96*summary_optimal$coefficients[2,2])

NAFLD.T2D.HR.est[3] <-exp(summary_one_two$coefficients[2,1])
NAFLD.T2D.logHR.est[3]<-summary_one_two$coefficients[2,1]
NAFLD.T2D.se[3]<-summary_one_two$coefficients[2,2]
NAFLD.T2D.pvalue[3]<-summary_one_two$coefficients[2,4]
NAFLD.T2D.lowerCI[3]<- exp(summary_one_two$coefficients[2,1]-1.96*summary_one_two$coefficients[2,2])
NAFLD.T2D.upperCI[3]<- exp(summary_one_two$coefficients[2,1]+1.96*summary_one_two$coefficients[2,2])

NAFLD.T2D.HR.est[4] <-exp(summary_full$coefficients[2,1])
NAFLD.T2D.logHR.est[4]<-summary_full$coefficients[2,1]
NAFLD.T2D.se[4]<-summary_full$coefficients[2,2]
NAFLD.T2D.pvalue[4]<-summary_full$coefficients[2,4]
NAFLD.T2D.lowerCI[4]<- exp(summary_full$coefficients[2,1]-1.96*summary_full$coefficients[2,2])
NAFLD.T2D.upperCI[4]<- exp(summary_full$coefficients[2,1]+1.96*summary_full$coefficients[2,2])

NAFLD.T2D.HR.est[5] <-exp(summary_subc$coefficients[2,1])
NAFLD.T2D.logHR.est[5]<-summary_subc$coefficients[2,1]
NAFLD.T2D.se[5]<-summary_subc$coefficients[2,2]
NAFLD.T2D.pvalue[5]<-summary_subc$coefficients[2,4]
NAFLD.T2D.lowerCI[5]<- exp(summary_subc$coefficients[2,1]-1.96*summary_subc$coefficients[2,2])
NAFLD.T2D.upperCI[5]<- exp(summary_subc$coefficients[2,1]+1.96*summary_subc$coefficients[2,2])

NAFLD.T2D.HR.est[6] <-exp(summary_iptw$coefficients[2,1])
NAFLD.T2D.logHR.est[6]<-summary_iptw$coefficients[2,1]
NAFLD.T2D.se[6]<-summary_iptw$coefficients[2,2]
NAFLD.T2D.pvalue[6]<-summary_iptw$coefficients[2,4]
NAFLD.T2D.lowerCI[6]<- exp(summary_iptw$coefficients[2,1]-1.96*summary_iptw$coefficients[2,2])
NAFLD.T2D.upperCI[6]<- exp(summary_iptw$coefficients[2,1]+1.96*summary_iptw$coefficients[2,2])

NAFLD.T2D.HR.est[7] <-exp(summary_glm$coefficients[2,1])
NAFLD.T2D.logHR.est[7]<-summary_glm$coefficients[2,1]
NAFLD.T2D.se[7]<-summary_glm$coefficients[2,2]
NAFLD.T2D.pvalue[7]<-summary_glm$coefficients[2,4]
NAFLD.T2D.lowerCI[7]<- exp(summary_glm$coefficients[2,1]-1.96*summary_glm$coefficients[2,2])
NAFLD.T2D.upperCI[7]<- exp(summary_glm$coefficients[2,1]+1.96*summary_glm$coefficients[2,2])

NAFLDoutcome.T2D.result <- 
  structure(list(
    mean  = c(NA, NA, NAFLD.T2D.HR.est), 
    lower = c(NA, NA, NAFLD.T2D.lowerCI),
    upper = c(NA, NA, NAFLD.T2D.upperCI)),
    .Names = c("mean", "lower", "upper"), 
    row.names = c(NA, -8L), 
    class = "data.frame")

A <- cbind2(c("","Method","Greedy Matching","Optimal Matching","1:2 Matching",
              "Full Matching","Stratification with 5 groups", "IPTW","Crude"),
                 c("","Effect", as.character(round(NAFLD.T2D.HR.est,3))))
B<- cbind2(c("","SE", as.character(round(NAFLD.T2D.se,3))),
           c("","p-value", ifelse(NAFLD.T2D.pvalue<0.001, "<0.001", round(NAFLD.T2D.pvalue,3))))
tabletext <- cbind2(A ,B)

forestplot(tabletext, 
           NAFLDoutcome.T2D.result,new_page = TRUE,
           col = fpColors(box="royalblue",line="darkblue"),
           xlab = "Estimate with 95% CI",
           hrzl_lines= gpar(col = "#444444"),
           is.summary = c(TRUE, TRUE, rep(FALSE, 10)),
           clip = c(0.5,5.5), zero=0.5,
           txt_gp=fpTxtGp(label = gpar(cex = 0.8),
                          title = gpar(cex = 1),
                          ticks = gpar(cex = 0.7),
                          xlab = gpar(cex = 0.7)),
           grid = structure(seq(0.5, 5.5, by=0.25), 
                            gp = gpar(lty = 2, col = "#CCCCFF")))
grid.text("Exposure of T2D on NAFLD", .5, 0.98, gp=gpar(fontface="bold"))
```
## MIte
```{r}
################################
############# MI ###############
################################



################################
############MIte################
################################
set.seed(1234)
## Greedy matching
greedy.matched.MIte.datasets <- matchthem(ps.formula, mi.data,
                                          approach = 'within',
                                          method = 'nearest',
                                          caliper = 0.05)
greedy.matched.MIte.datasets

set.seed(1234)
## Optimal matching
optimal.matched.MIte.datasets <- matchthem(ps.formula, mi.data,
                                           approach = 'within',
                                           method = 'optimal',
                                           caliper = 0.05)
optimal.matched.MIte.datasets

set.seed(1234)
## 1:2 matching
one_two.matched.MIte.datasets <- matchthem(ps.formula, mi.data,
                                           approach = 'within',
                                           method = 'nearest',
                                           caliper = 0.05, ratio = 2)
one_two.matched.MIte.datasets 

set.seed(1234)
## Full matching
full.matched.MIte.datasets <- matchthem(ps.formula,mi.data,
                                        approach = 'within',
                                        caliper = 0.05,
                                        method = "full")
full.matched.MIte.datasets

set.seed(1234)
## Subclassification with full matching
subc.MIte.datasets <- matchthem(ps.formula, mi.data,
                                approach = 'within',
                                method = "subclass",
                                subclass = 5)
subc.MIte.datasets
plot(subc.MIte.datasets, type = "jitter")

set.seed(1234)
# IPTW
weighted.MIte.datasets <- weightthem(ps.formula, mi.data,
                                     approach = 'within', 
                                     method = 'ps', estimand = 'ATM')
weighted.MIte.datasets

library(cobalt)
bal.tab(greedy.matched.MIte.datasets, abs = TRUE)
bal.tab(optimal.matched.MIte.datasets, abs = TRUE)
bal.tab(one_two.matched.MIte.datasets, abs = TRUE)
bal.tab(full.matched.MIte.datasets, abs = TRUE)
bal.tab(subc.MIte.datasets, abs = TRUE)
bal.tab(weighted.MIte.datasets, abs = TRUE)

library(survey)
formula1<-as.formula((paste("NAFLD_status","~ T2D+ ",paste(newvariables.bootstrap.sampling.interaction,collapse = "+"))))

set.seed(1234)
greedy.matched.MIte.models <- with(data = greedy.matched.MIte.datasets,
                                   expr = svyglm(formula1, family = quasibinomial))
greedy.matched.MIte.results <- pool(greedy.matched.MIte.models)
summary_MIte_greedy <- summary(greedy.matched.MIte.results, conf.int = TRUE)

set.seed(1234)
optimal.matched.MIte.models <- with(data = optimal.matched.MIte.datasets,
                                    expr = svyglm(formula1, family =quasibinomial))
optimal.matched.MIte.results <- pool(optimal.matched.MIte.models)
summary_MIte_optimal <-summary(optimal.matched.MIte.results, conf.int = TRUE)

set.seed(1234)
one_two.matched.MIte.models <- with(data = one_two.matched.MIte.datasets,
                                    expr = svyglm(formula1, family = quasibinomial))
one_two.matched.MIte.results <- pool(one_two.matched.MIte.models)
summary_MIte_one_two <- summary(one_two.matched.MIte.results, conf.int = TRUE)

set.seed(1234)
full.matched.MIte.models <- with(data = full.matched.MIte.datasets,
                                 expr = svyglm(formula1, family = quasibinomial))
full.matched.MIte.results <- pool(full.matched.MIte.models)
summary_MIte_full <- summary(full.matched.MIte.results, conf.int = TRUE)

set.seed(1234)
subc.MIte.models <- with(data = subc.MIte.datasets,
                         expr = svyglm(formula1, family = quasibinomial))
subc.MIte.results <- pool(subc.MIte.models)
summary_MIte_subc <-summary(subc.MIte.results, conf.int = TRUE)

set.seed(1234)
# IPTW
weighted.MIte.models <- with(data = weighted.MIte.datasets, expr = svyglm(formula1, family = quasibinomial))
weighted.MIte.results <- pool(weighted.MIte.models)
summary_MIte_iptw <-summary(weighted.MIte.results, conf.int = TRUE)

NAFLD.T2D.MIte.HR.est<-c()
NAFLD.T2D.MIte.logHR.est<-c()
NAFLD.T2D.MIte.se<-c()
NAFLD.T2D.MIte.pvalue<-c()
NAFLD.T2D.MIte.lowerCI<-c()
NAFLD.T2D.MIte.upperCI<-c()

NAFLD.T2D.MIte.HR.est[1] <-exp(summary_MIte_greedy[2,2])
NAFLD.T2D.MIte.logHR.est[1]<-summary_MIte_greedy[2,2]
NAFLD.T2D.MIte.se[1]<-summary_MIte_greedy[2,3]
NAFLD.T2D.MIte.pvalue[1]<-summary_MIte_greedy[2,6]
NAFLD.T2D.MIte.lowerCI[1]<- exp(summary_MIte_greedy[2,7])
NAFLD.T2D.MIte.upperCI[1]<- exp(summary_MIte_greedy[2,8])

NAFLD.T2D.MIte.HR.est[2] <-exp(summary_MIte_optimal[2,2])
NAFLD.T2D.MIte.logHR.est[2]<-summary_MIte_optimal[2,2]
NAFLD.T2D.MIte.se[2]<-summary_MIte_optimal[2,3]
NAFLD.T2D.MIte.pvalue[2]<-summary_MIte_optimal[2,6]
NAFLD.T2D.MIte.lowerCI[2]<- exp(summary_MIte_optimal[2,7])
NAFLD.T2D.MIte.upperCI[2]<- exp(summary_MIte_optimal[2,8])

NAFLD.T2D.MIte.HR.est[3] <-exp(summary_MIte_one_two[2,2])
NAFLD.T2D.MIte.logHR.est[3]<-summary_MIte_one_two[2,2]
NAFLD.T2D.MIte.se[3]<-summary_MIte_one_two[2,3]
NAFLD.T2D.MIte.pvalue[3]<-summary_MIte_one_two[2,6]
NAFLD.T2D.MIte.lowerCI[3]<- exp(summary_MIte_one_two[2,7])
NAFLD.T2D.MIte.upperCI[3]<- exp(summary_MIte_one_two[2,8])

NAFLD.T2D.MIte.HR.est[4] <-exp(summary_MIte_full[2,2])
NAFLD.T2D.MIte.logHR.est[4]<-summary_MIte_full[2,2]
NAFLD.T2D.MIte.se[4]<-summary_MIte_full[2,3]
NAFLD.T2D.MIte.pvalue[4]<-summary_MIte_full[2,6]
NAFLD.T2D.MIte.lowerCI[4]<- exp(summary_MIte_full[2,7])
NAFLD.T2D.MIte.upperCI[4]<- exp(summary_MIte_full[2,8])

NAFLD.T2D.MIte.HR.est[5] <-exp(summary_MIte_subc[2,2])
NAFLD.T2D.MIte.logHR.est[5]<-summary_MIte_subc[2,2]
NAFLD.T2D.MIte.se[5]<-summary_MIte_subc[2,3]
NAFLD.T2D.MIte.pvalue[5]<-summary_MIte_subc[2,6]
NAFLD.T2D.MIte.lowerCI[5]<- exp(summary_MIte_subc[2,7])
NAFLD.T2D.MIte.upperCI[5]<- exp(summary_MIte_subc[2,8])

NAFLD.T2D.MIte.HR.est[6] <-exp(summary_MIte_iptw[2,2])
NAFLD.T2D.MIte.logHR.est[6]<-summary_MIte_iptw[2,2]
NAFLD.T2D.MIte.se[6]<-summary_MIte_iptw[2,3]
NAFLD.T2D.MIte.pvalue[6]<-summary_MIte_iptw[2,6]
NAFLD.T2D.MIte.lowerCI[6]<- exp(summary_MIte_iptw[2,7])
NAFLD.T2D.MIte.upperCI[6]<- exp(summary_MIte_iptw[2,8])

NAFLD.T2D.MIte.HR.est[7] <-exp(summary_glm_mi$coefficients[2,1])
NAFLD.T2D.MIte.logHR.est[7]<-summary_glm_mi$coefficients[2,1]
NAFLD.T2D.MIte.se[7]<-summary_glm_mi$coefficients[2,2]
NAFLD.T2D.MIte.pvalue[7]<-summary_glm_mi$coefficients[2,4]
NAFLD.T2D.MIte.lowerCI[7]<- exp(summary_glm_mi$coefficients[2,1]-1.96*summary_glm_mi$coefficients[2,2])
NAFLD.T2D.MIte.upperCI[7]<- exp(summary_glm_mi$coefficients[2,1]+1.96*summary_glm_mi$coefficients[2,2])

NAFLDoutcome.T2D.MIte.result <- 
  structure(list(
    mean  = c(NA, NA, NAFLD.T2D.MIte.HR.est), 
    lower = c(NA, NA, NAFLD.T2D.MIte.lowerCI),
    upper = c(NA, NA, NAFLD.T2D.MIte.upperCI)),
    .Names = c("mean", "lower", "upper"), 
    row.names = c(NA, -8L), 
    class = "data.frame")

A <- cbind2(c("","Method","Greedy Matching","Optimal Matching","1:2 Matching",
              "Full Matching","Stratification with 5 groups", "IPTW","Crude"),
            c("","Effect", as.character(round(NAFLD.T2D.MIte.HR.est,3))))
B<- cbind2(c("","SE", as.character(round(NAFLD.T2D.MIte.se,3))),
           c("","p-value", ifelse(NAFLD.T2D.MIte.pvalue<0.001, "<0.001", round(NAFLD.T2D.MIte.pvalue,3))))
tabletext <- cbind2(A ,B)

forestplot(tabletext, 
           NAFLDoutcome.T2D.MIte.result,new_page = TRUE,
           col = fpColors(box="royalblue",line="darkblue"),
           xlab = "Estimate with 95% CI",
           hrzl_lines= gpar(col = "#444444"),
           is.summary = c(TRUE, TRUE, rep(FALSE, 10)),
           clip = c(0,5.5), zero=1,
           txt_gp=fpTxtGp(label = gpar(cex = 0.8),
                          title = gpar(cex = 1),
                          ticks = gpar(cex = 0.7),
                          xlab = gpar(cex = 0.7)),
           grid = structure(seq(1,5, by=0.25), 
                            gp = gpar(lty = 2, col = "#CCCCFF")))
grid.text("Exposure of T2D on NAFLD by MIte", .5, 0.98, gp=gpar(fontface="bold"))
```
## MIps
```{r}
################################
############MIps################
################################
set.seed(1234)
## Greedy matching
greedy.matched.MIps.across.datasets <- matchthem(ps.formula, mi.data,
                                                 approach = 'across',
                                                 method = 'nearest',
                                                 caliper = 0.05)
greedy.matched.MIps.across.datasets

set.seed(1234)
## Optimal matching
optimal.matched.MIps.across.datasets <- matchthem(ps.formula, mi.data,
                                                  approach = 'across',
                                                  method = 'optimal',
                                                  caliper = 0.05)
optimal.matched.MIps.across.datasets

set.seed(1234)
## 1:2 matching
one_two.matched.MIps.across.datasets <- matchthem(ps.formula, mi.data,
                                                  approach = 'across',
                                                  method = 'nearest',
                                                  caliper = 0.05, ratio = 2)
one_two.matched.MIps.across.datasets

set.seed(1234)
## Full matching
full.matched.MIps.across.datasets <- matchthem(ps.formula,mi.data,
                                               approach = 'across',
                                               caliper = 0.05,
                                               method = "full")
full.matched.MIps.across.datasets

set.seed(1234)
## Subclassification with full matching
subc.MIps.across.datasets <- matchthem(ps.formula, mi.data,
                                       approach = 'across',
                                       method = "subclass",
                                       subclass = 5)
subc.MIps.across.datasets
plot(subc.MIps.across.datasets, type = "jitter")

set.seed(1234)
# IPTW
weighted.across.datasets <- weightthem(ps.formula, mi.data,
                                       approach = 'across', 
                                       method = 'ps', estimand = 'ATM')
weighted.across.datasets

bal.tab(greedy.matched.MIps.across.datasets, abs = TRUE)
bal.tab(optimal.matched.MIps.across.datasets, abs = TRUE)
bal.tab(one_two.matched.MIps.across.datasets, abs = TRUE)
bal.tab(full.matched.MIps.across.datasets, abs = TRUE)
bal.tab(subc.MIps.across.datasets, abs = TRUE)
bal.tab(weighted.across.datasets, abs = TRUE)

formula1<-as.formula((paste("NAFLD_status","~ T2D+ ",paste(newvariables.bootstrap.sampling.interaction,collapse = "+"))))

set.seed(1234)
greedy.matched.MIps.across.models <- with(data = greedy.matched.MIps.across.datasets,
                                          expr = svyglm(formula1, family = quasibinomial))
greedy.matched.MIps.across.results <- pool(greedy.matched.MIps.across.models)
summary_MIps_greedy <- summary(greedy.matched.MIps.across.results, conf.int = TRUE)

set.seed(1234)
optimal.matched.MIps.across.models <- with(data = optimal.matched.MIps.across.datasets,
                                           expr = svyglm(formula1, family =quasibinomial))
optimal.matched.MIps.across.results <- pool(optimal.matched.MIps.across.models)
summary_MIps_optimal <-summary(optimal.matched.MIps.across.results, conf.int = TRUE)

set.seed(1234)
one_two.matched.MIps.across.models <- with(data = one_two.matched.MIps.across.datasets,
                                           expr = svyglm(formula1, family = quasibinomial))
one_two.matched.MIps.across.results <- pool(one_two.matched.MIps.across.models)
summary_MIps_one_two <- summary(one_two.matched.MIps.across.results, conf.int = TRUE)

set.seed(1234)
full.matched.MIps.across.models <- with(data = full.matched.MIps.across.datasets,
                                        expr = svyglm(formula1, family = quasibinomial))
full.matched.MIps.across.results <- pool(full.matched.MIps.across.models)
summary_MIps_full <- summary(full.matched.MIps.across.results, conf.int = TRUE)

set.seed(1234)
subc.MIps.across.models <- with(data = subc.MIps.across.datasets,
                                expr = svyglm(formula1, family = quasibinomial))
subc.MIps.across.results <- pool(subc.MIps.across.models)
summary_MIps_subc <-summary(subc.MIps.across.results, conf.int = TRUE)

# IPTW
set.seed(1234)
weighted.across.models <- with(data = weighted.across.datasets, expr = svyglm(formula1, family = quasibinomial))
weighted.across.results <- pool(weighted.across.models)
summary_MIps_iptw <-summary(weighted.across.results, conf.int = TRUE)

NAFLD.T2D.MIps.HR.est<-c()
NAFLD.T2D.MIps.logHR.est<-c()
NAFLD.T2D.MIps.se<-c()
NAFLD.T2D.MIps.pvalue<-c()
NAFLD.T2D.MIps.lowerCI<-c()
NAFLD.T2D.MIps.upperCI<-c()

NAFLD.T2D.MIps.HR.est[1] <-exp(summary_MIps_greedy[2,2])
NAFLD.T2D.MIps.logHR.est[1]<-summary_MIps_greedy[2,2]
NAFLD.T2D.MIps.se[1]<-summary_MIps_greedy[2,3]
NAFLD.T2D.MIps.pvalue[1]<-summary_MIps_greedy[2,6]
NAFLD.T2D.MIps.lowerCI[1]<- exp(summary_MIps_greedy[2,7])
NAFLD.T2D.MIps.upperCI[1]<- exp(summary_MIps_greedy[2,8])

NAFLD.T2D.MIps.HR.est[2] <-exp(summary_MIps_optimal[2,2])
NAFLD.T2D.MIps.logHR.est[2]<-summary_MIps_optimal[2,2]
NAFLD.T2D.MIps.se[2]<-summary_MIps_optimal[2,3]
NAFLD.T2D.MIps.pvalue[2]<-summary_MIps_optimal[2,6]
NAFLD.T2D.MIps.lowerCI[2]<- exp(summary_MIps_optimal[2,7])
NAFLD.T2D.MIps.upperCI[2]<- exp(summary_MIps_optimal[2,8])

NAFLD.T2D.MIps.HR.est[3] <-exp(summary_MIps_one_two[2,2])
NAFLD.T2D.MIps.logHR.est[3]<-summary_MIps_one_two[2,2]
NAFLD.T2D.MIps.se[3]<-summary_MIps_one_two[2,3]
NAFLD.T2D.MIps.pvalue[3]<-summary_MIps_one_two[2,6]
NAFLD.T2D.MIps.lowerCI[3]<- exp(summary_MIps_one_two[2,7])
NAFLD.T2D.MIps.upperCI[3]<- exp(summary_MIps_one_two[2,8])

NAFLD.T2D.MIps.HR.est[4] <-exp(summary_MIps_full[2,2])
NAFLD.T2D.MIps.logHR.est[4]<-summary_MIps_full[2,2]
NAFLD.T2D.MIps.se[4]<-summary_MIps_full[2,3]
NAFLD.T2D.MIps.pvalue[4]<-summary_MIps_full[2,6]
NAFLD.T2D.MIps.lowerCI[4]<- exp(summary_MIps_full[2,7])
NAFLD.T2D.MIps.upperCI[4]<- exp(summary_MIps_full[2,8])

NAFLD.T2D.MIps.HR.est[5] <-exp(summary_MIps_subc[2,2])
NAFLD.T2D.MIps.logHR.est[5]<-summary_MIps_subc[2,2]
NAFLD.T2D.MIps.se[5]<-summary_MIps_subc[2,3]
NAFLD.T2D.MIps.pvalue[5]<-summary_MIps_subc[2,6]
NAFLD.T2D.MIps.lowerCI[5]<- exp(summary_MIps_subc[2,7])
NAFLD.T2D.MIps.upperCI[5]<- exp(summary_MIps_subc[2,8])

NAFLD.T2D.MIps.HR.est[6] <-exp(summary_MIps_iptw[2,2])
NAFLD.T2D.MIps.logHR.est[6]<-summary_MIps_iptw[2,2]
NAFLD.T2D.MIps.se[6]<-summary_MIps_iptw[2,3]
NAFLD.T2D.MIps.pvalue[6]<-summary_MIps_iptw[2,6]
NAFLD.T2D.MIps.lowerCI[6]<- exp(summary_MIps_iptw[2,7])
NAFLD.T2D.MIps.upperCI[6]<- exp(summary_MIps_iptw[2,8])

NAFLD.T2D.MIps.HR.est[7] <-exp(summary_glm_mi$coefficients[2,1])
NAFLD.T2D.MIps.logHR.est[7]<-summary_glm_mi$coefficients[2,1]
NAFLD.T2D.MIps.se[7]<-summary_glm_mi$coefficients[2,2]
NAFLD.T2D.MIps.pvalue[7]<-summary_glm_mi$coefficients[2,4]
NAFLD.T2D.MIps.lowerCI[7]<- exp(summary_glm_mi$coefficients[2,1]-1.96*summary_glm_mi$coefficients[2,2])
NAFLD.T2D.MIps.upperCI[7]<- exp(summary_glm_mi$coefficients[2,1]+1.96*summary_glm_mi$coefficients[2,2])

NAFLDoutcome.T2D.MIps.result <- 
  structure(list(
    mean  = c(NA, NA, NAFLD.T2D.MIps.HR.est), 
    lower = c(NA, NA, NAFLD.T2D.MIps.lowerCI),
    upper = c(NA, NA, NAFLD.T2D.MIps.upperCI)),
    .Names = c("mean", "lower", "upper"), 
    row.names = c(NA, -9L), 
    class = "data.frame")


A <- cbind2(c("","Method","Greedy Matching","Optimal Matching","1:2 Matching",
              "Full Matching","Stratification with 5 groups", "IPTW","Crude"),
               c("","Effect", as.character(round(NAFLD.T2D.MIps.HR.est,3))))
B<- cbind2(c("","SE", as.character(round(NAFLD.T2D.MIps.se,3))),
           c("","p-value", ifelse(NAFLD.T2D.MIps.pvalue<0.001, "<0.001", 
                                          round(NAFLD.T2D.MIps.pvalue,3))))
tabletext <- cbind2(A ,B)

forestplot(tabletext, 
           NAFLDoutcome.T2D.MIps.result,new_page = TRUE,
           col = fpColors(box="royalblue",line="darkblue"),
           xlab = "Estimate with 95% CI",
           hrzl_lines= gpar(col = "#444444"),
           is.summary = c(TRUE, TRUE, rep(FALSE, 10)),
           clip = c(0.5,5.5), zero=1,
           txt_gp=fpTxtGp(label = gpar(cex = 0.8),
                          title = gpar(cex = 1),
                          ticks = gpar(cex = 0.8),
                          xlab = gpar(cex = 0.7)),
           grid = structure(seq(1, 5.5, by=0.25), 
                            gp = gpar(lty = 2, col = "#CCCCFF")))
grid.text("Exposure of T2D on NAFLD by MIps", .5, 0.98, gp=gpar(fontface="bold"))
```

```{r}
NAFLD.T2D.bootstrap.sampling.interaction<-data.frame(MLapproach=rep("Bootstap with feature sampling LASSO (with interaction)",21),MIapproach=c(rep("CCA",7),rep("MIte",7),rep("MIps",7)),
                      PSmethod=c(rep(c("Greedy Matching","Optimal Matching","1:2 Matching",
                                       "Full Matching","Stratification with 5 groups", "IPTW","Crude"),3)),
                      est=c(round(NAFLD.T2D.HR.est,3),round(NAFLD.T2D.MIte.HR.est,3),
                            round(NAFLD.T2D.MIps.HR.est,3)),
                      log.est=c(round(NAFLD.T2D.logHR.est,3),round(NAFLD.T2D.MIte.logHR.est,3),round(NAFLD.T2D.MIps.logHR.est,3)),
                      se=c(round(NAFLD.T2D.se,3),round(NAFLD.T2D.MIte.se,3),round(NAFLD.T2D.MIps.se,3)),
                      pvalue=c(round(NAFLD.T2D.pvalue,3),round(NAFLD.T2D.MIte.pvalue,3),round(NAFLD.T2D.MIps.pvalue,3)),
                      lowerCI=c(round(NAFLD.T2D.lowerCI,3),round(NAFLD.T2D.MIte.lowerCI,3),round(NAFLD.T2D.MIps.lowerCI,3)),
                      upperCI=c(round(NAFLD.T2D.upperCI,3),round(NAFLD.T2D.MIte.upperCI,3),round(NAFLD.T2D.MIps.upperCI,3)))

NAFLD.T2D.greedy<-subset(NAFLD.T2D.bootstrap.sampling.interaction,PSmethod=="Greedy Matching")
NAFLD.T2D.optimal<-subset(NAFLD.T2D.bootstrap.sampling.interaction,PSmethod=="Optimal Matching")
NAFLD.T2D.one_two<-subset(NAFLD.T2D.bootstrap.sampling.interaction,PSmethod=="1:2 Matching")
NAFLD.T2D.full<-subset(NAFLD.T2D.bootstrap.sampling.interaction,PSmethod=="Full Matching")
NAFLD.T2D.subc<-subset(NAFLD.T2D.bootstrap.sampling.interaction,PSmethod=="Stratification with 5 groups")
NAFLD.T2D.iptw<-subset(NAFLD.T2D.bootstrap.sampling.interaction,PSmethod=="IPTW")
NAFLD.T2D.crude<-subset(NAFLD.T2D.bootstrap.sampling.interaction,PSmethod=="Crude")


Forstplot<-function(method,title){
  
  A <- cbind2(c("","MI Approach","CCA","MIte","MIps"), 
                     c("","Effect", as.character(method$est)))

  B <-cbind2(c("","SE", as.character(method$se)),
                     c("","p-value", ifelse(method$pvalue<0.001, "<0.001", method$pvalue)))
  
  tabletext <- cbind2(A,B)
  NAFLD.T2D.result <- 
    structure(list(
      mean  = c(NA, NA, method$est), 
      lower = c(NA, NA, method$lowerCI),
      upper = c(NA, NA, method$upperCI)),
      .Names = c("mean", "lower", "upper"), 
      row.names = c(NA, -5L), 
      class = "data.frame")
  
  forestplot(tabletext, 
             NAFLD.T2D.result,
             new_page = TRUE,
             xlab = "Estimate with 95% CI",
             col = fpColors(box="royalblue",line="darkblue"),
             hrzl_lines= gpar(col = "#444444"),
             is.summary = c(TRUE, TRUE, rep(FALSE, 18)),
             clip = c(0.5,5.5), zero=1,
             txt_gp=fpTxtGp(label = gpar(cex = 0.8),
                            title = gpar(cex = 1),
                            ticks = gpar(cex = 0.7),
                            xlab = gpar(cex = 0.7)),
             grid = structure(seq(1, 5.5, by=0.5), 
                              gp = gpar(lty = 2, col = "#CCCCFF")),
             title=title)
}

Forstplot(NAFLD.T2D.greedy,"Exposure of T2D on of Greedy Matching")
Forstplot(NAFLD.T2D.optimal,"Exposure of T2D on of Optimal Matching")
Forstplot(NAFLD.T2D.one_two,"Exposure of T2D on of 1:2 Matching")
Forstplot(NAFLD.T2D.full,"Exposure of T2D on of Full Matching")
Forstplot(NAFLD.T2D.subc,"Exposure of T2D on of Stratification with 5 groups")
Forstplot(NAFLD.T2D.iptw,"Exposure of T2D on of IPTW ")
```

```{r}

A<-c("","PS Method","Greedy Matching","","","","Optimal Matching","","","","1:2 Matching","","","",
                                       "Full Matching","","","","Stratification with 5 groups", "","","","IPTW","","","","Crude","","")
  
B <- cbind2(c("","MI Approach",rep(c("CCA","MIte","MIps"," "),6),"CCA","MIte","MIps"), 
                     c("","Effect", NAFLD.T2D.greedy$est,"",NAFLD.T2D.optimal$est,"",NAFLD.T2D.one_two$est,"",NAFLD.T2D.full$est,"",NAFLD.T2D.subc$est,"",NAFLD.T2D.iptw$est,"",NAFLD.T2D.crude$est))
  
C <-cbind2(c("","SE", as.character(NAFLD.T2D.greedy$se),"",as.character(NAFLD.T2D.optimal$se),"",
               as.character(NAFLD.T2D.one_two$se),"",as.character(NAFLD.T2D.full$se),"",
               as.character(NAFLD.T2D.subc$se),"",as.character(NAFLD.T2D.iptw$se),"",
               as.character(NAFLD.T2D.crude$se)),
             c("","p-value", as.character(ifelse(NAFLD.T2D.greedy$pvalue<0.001, "<0.001",
                                                 round(NAFLD.T2D.greedy$pvalue,3))),"",
               as.character(ifelse(NAFLD.T2D.optimal$pvalue<0.001, "<0.001",
                                   round(NAFLD.T2D.optimal$pvalue,3))),"",
               as.character(ifelse(NAFLD.T2D.one_two$pvalue<0.001, "<0.001", 
                                          round(NAFLD.T2D.one_two$pvalue,3))),
               "",as.character(ifelse(NAFLD.T2D.full$pvalue<0.001, "<0.001", round(NAFLD.T2D.full$pvalue,3))),"",
               as.character(ifelse(NAFLD.T2D.subc$pvalue<0.001, "<0.001", round(NAFLD.T2D.subc$pvalue,3))),"",
               as.character(ifelse(NAFLD.T2D.iptw$pvalue<0.001, "<0.001", round(NAFLD.T2D.iptw$pvalue,3))),"",
               as.character(ifelse(NAFLD.T2D.crude$pvalue<0.001, "<0.001", round(NAFLD.T2D.curde$pvalue,3)))))
D <-cbind2(A,B)
tabletext <- cbind2(D,C)
NAFLD.T2D.result <- 
    structure(list(
      mean  = c(NA, NA, NAFLD.T2D.greedy$est,NA,NAFLD.T2D.optimal$est,NA,NAFLD.T2D.one_two$est,NA,NAFLD.T2D.full$est,NA,NAFLD.T2D.subc$est,NA,NAFLD.T2D.iptw$est,NA,NAFLD.T2D.crude$est), 
      lower = c(NA, NA, NAFLD.T2D.greedy$lowerCI,NA,NAFLD.T2D.optimal$lowerCI,NA,NAFLD.T2D.one_two$lowerCI,NA,NAFLD.T2D.full$lowerCI,NA,NAFLD.T2D.subc$lowerCI,NA,NAFLD.T2D.iptw$lowerCI,NA,NAFLD.T2D.crude$lowerCI),
      upper = c(NA, NA, NAFLD.T2D.greedy$upperCI,NA,NAFLD.T2D.optimal$upperCI,NA,NAFLD.T2D.one_two$upperCI,NA,NAFLD.T2D.full$upperCI,NA,NAFLD.T2D.subc$upperCI,NA,NAFLD.T2D.iptw$upperCI,NA,NAFLD.T2D.crude$upperCI)),
      .Names = c("mean", "lower", "upper"), 
      row.names = c(NA, -29L), 
      class = "data.frame")

forestplot(tabletext, 
             NAFLD.T2D.result,
             new_page = TRUE,
             col = fpColors(box="royalblue",line="darkblue"),
             hrzl_lines= gpar(col = "#444444"),
             is.summary = c(TRUE, TRUE, rep(FALSE, 29)),
             clip = c(0.5,2.5), zero=1,
             txt_gp=fpTxtGp(label = gpar(cex = 0.8),
                            title = gpar(cex = 1),
                            ticks = gpar(cex = 0.7),
                            xlab = gpar(cex = 0.7)),
             grid = structure(seq(0, 1, by=0.5), 
                              gp = gpar(lty = 0.5, col = "#CCCCFF")),
           xlab = "Estimate with 95% CI",
           title="Forest Plot of Bootstap with feature sampling LASSO (with interaction)")

```
# Total
```{r}
NAFLD.T2D.total<-rbind(NAFLD.T2D.normal,NAFLD.T2D.bootsrap,NAFLD.T2D.bootsrap.interaction,NAFLD.T2D.bootstrap.sampling,NAFLD.T2D.bootstrap.sampling.interaction)

```
```{r}
NAFLD.T2D.CCA.greedy<-subset(NAFLD.T2D.total,MIapproach=="CCA"&PSmethod=="Greedy Matching")
NAFLD.T2D.CCA.optimal<-subset(NAFLD.T2D.total,MIapproach=="CCA"&PSmethod=="Optimal Matching")
NAFLD.T2D.CCA.onetotwo<-subset(NAFLD.T2D.total,MIapproach=="CCA"&PSmethod=="1:2 Matching")
NAFLD.T2D.CCA.full<-subset(NAFLD.T2D.total,MIapproach=="CCA"& PSmethod=="Full Matching")
NAFLD.T2D.CCA.subc<-subset(NAFLD.T2D.total,MIapproach=="CCA"& PSmethod=="Stratification with 5 groups")
NAFLD.T2D.CCA.iptw<-subset(NAFLD.T2D.total,MIapproach=="CCA"& PSmethod=="IPTW")

NAFLD.T2D.MIte.greedy<-subset(NAFLD.T2D.total,MIapproach=="MIte"&PSmethod=="Greedy Matching")
NAFLD.T2D.MIte.optimal<-subset(NAFLD.T2D.total,MIapproach=="MIte"&PSmethod=="Optimal Matching")
NAFLD.T2D.MIte.onetotwo<-subset(NAFLD.T2D.total,MIapproach=="MIte"&PSmethod=="1:2 Matching")
NAFLD.T2D.MIte.full<-subset(NAFLD.T2D.total,MIapproach=="MIte"& PSmethod=="Full Matching")
NAFLD.T2D.MIte.subc<-subset(NAFLD.T2D.total,MIapproach=="MIte"& PSmethod=="Stratification with 5 groups")
NAFLD.T2D.MIte.iptw<-subset(NAFLD.T2D.total,MIapproach=="MIte"& PSmethod=="IPTW")

NAFLD.T2D.MIps.greedy<-subset(NAFLD.T2D.total,MIapproach=="MIps"&PSmethod=="Greedy Matching")
NAFLD.T2D.MIps.optimal<-subset(NAFLD.T2D.total,MIapproach=="MIps"&PSmethod=="Optimal Matching")
NAFLD.T2D.MIps.onetotwo<-subset(NAFLD.T2D.total,MIapproach=="MIps"&PSmethod=="1:2 Matching")
NAFLD.T2D.MIps.full<-subset(NAFLD.T2D.total,MIapproach=="MIps"& PSmethod=="Full Matching")
NAFLD.T2D.MIps.subc<-subset(NAFLD.T2D.total,MIapproach=="MIps"& PSmethod=="Stratification with 5 groups")
NAFLD.T2D.MIps.iptw<-subset(NAFLD.T2D.total,MIapproach=="MIps"& PSmethod=="IPTW")
Forstplot<-function(method,title){
  
  A <- cbind2(c("","ML Approach","Normal Lasso","Bootstrap Lasso","Bootstrap Lasso (with interaction)","Bootstrap with feature sampling LASSO","Bootstrap with feature sampling LASSO (with interaction)"), 
                     c("","Effect", as.character(method$est)))

  B <-cbind2(c("","SE", as.character(method$se)),
                     c("","p-value", ifelse(method$pvalue<0.001, "<0.001", method$pvalue)))
  
  tabletext <- cbind2(A,B)
  NAFLD.T2D.result <- 
    structure(list(
      mean  = c(NA, NA, method$est), 
      lower = c(NA, NA, method$lowerCI),
      upper = c(NA, NA, method$upperCI)),
      .Names = c("mean", "lower", "upper"), 
      row.names = c(NA, -5L), 
      class = "data.frame")
  
  forestplot(tabletext, 
             NAFLD.T2D.result,
             new_page = TRUE,
             xlab = "Estimate with 95% CI",
             col = fpColors(box="royalblue",line="darkblue"),
             hrzl_lines= gpar(col = "#444444"),
             is.summary = c(TRUE, TRUE, rep(FALSE, 18)),
             zero=1,
             txt_gp=fpTxtGp(label = gpar(cex = 0.6),
                            title = gpar(cex = 1),
                            ticks = gpar(cex = 0.5),
                            xlab = gpar(cex = 0.5)),
             xticks=c(0.5,1, 1.5),
             title=title)
}

Forstplot(NAFLD.T2D.CCA.greedy,"Exposure of T2D on of CCA Greedy Matching")
Forstplot(NAFLD.T2D.CCA.optimal,"Exposure of T2D on of CCA Full Matching")
Forstplot(NAFLD.T2D.CCA.full,"Exposure of T2D on of CCA Full Matching")
Forstplot(NAFLD.T2D.CCA.onetotwo,"Exposure of T2D on of CCA 1:2 Matching")
Forstplot(NAFLD.T2D.CCA.subc,"Exposure of T2D on of CCA Stratification with 5 groups")
Forstplot(NAFLD.T2D.CCA.iptw,"Exposure of T2D on of CCA IPTW")

Forstplot(NAFLD.T2D.MIte.greedy,"Exposure of T2D on of MIte Greedy Matching")
Forstplot(NAFLD.T2D.MIte.optimal,"Exposure of T2D on of MIte Full Matching")
Forstplot(NAFLD.T2D.MIte.full,"Exposure of T2D on of MIte Full Matching")
Forstplot(NAFLD.T2D.MIte.onetotwo,"Exposure of T2D on of MIte 1:2 Matching")
Forstplot(NAFLD.T2D.MIte.subc,"Exposure of T2D on of MIte Stratification with 5 groups")
Forstplot(NAFLD.T2D.MIte.iptw,"Exposure of T2D on of MIte IPTW")

Forstplot(NAFLD.T2D.MIps.greedy,"Exposure of T2D on of MIps Greedy Matching")
Forstplot(NAFLD.T2D.MIps.optimal,"Exposure of T2D on of MIps Full Matching")
Forstplot(NAFLD.T2D.MIps.full,"Exposure of T2D on of MIps Full Matching")
Forstplot(NAFLD.T2D.MIps.onetotwo,"Exposure of T2D on of MIps 1:2 Matching")
Forstplot(NAFLD.T2D.MIps.subc,"Exposure of T2D on of MIps Stratification with 5 groups")
Forstplot(NAFLD.T2D.MIps.iptw,"Exposure of T2D on of MIps IPTW")

```

